### ISSUE TITLE
Summary totalCellCount calculation incorrectly inflated

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1038]
The `totalCellCount` calculated by the '/summary' response is reported incorrectly if a project has a cell suspension that has more than 1 input sample.

![cell_counts](https://user-images.githubusercontent.com/46407464/58214708-a15d2a00-7cab-11e9-8a4e-9893d695d900.jpg)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-649)
┆Project Name: azul
┆Issue Number: AZUL-649

**Comment by hannes-ucsc** [comment]
The fix is to not use the `samples` index to compute the cell count summary but instead use an index in which each document represents exactly one cell suspension. The samples index is not suitable for aggregating cell suspensions because one cell suspension could occur in more than one document therefore inflating the sums. 

Adding a new index should not be that hard, since we practiced it for bundles and samples. Especially bundles straight forward to add.

Note that the recent change of making `contents.cell_suspensions.organ` an array potentially holding more than one element is another cause for inflated cell counts due to how ES bucket aggregations work. We should consider using a [value script](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-script). The script would concatenate the array elements into a single string using a separator that does not naturally occur in organs.

**Comment by hannes-ucsc** [comment]
@NoopDog, we didn't create a browser bug for this but you should be aware of it since users may notice.
