### ISSUE TITLE
Copy per-project matrix service output files to Data Browser S3 bucket

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1098]
The Matrix Service will generate per-project matrix output files into their own S3 bucket.
Azul will then run a script to sync the files to the same S3 bucket used to store the per-project metadata tsv files.
Later this process should be automated.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-687)
┆Project Name: azul
┆Issue Number: AZUL-687

**Comment by theathorn** [comment]
Marcus wrote: I renamed the folders in s3://hca-prepared-matrices (to exclude the project name and just used the project_uuid instead).

Example path: https://hca-prepared-matrices.s3.amazonaws.com/63910278-7763-4aeb-8b3a-15c0e199abd2.csv.zip

**Comment by GPelayo** [comment]
I copied the matrix files to the browser’s s3 bucket. Here’s the URLs to the copied matrix files. Since I modified the content disposition headers, it automatically saves the files as `project name` `datetime modified`.`file extentions` when you click the link.
http://url.data.humancellatlas.org/project-matrices/cddab57b-6868-4be4-806f-395ed9dd635a/63910278-7763-4aeb-8b3a-15c0e199abd2.csv.zip
http://url.data.humancellatlas.org/project-matrices/cddab57b-6868-4be4-806f-395ed9dd635a/92a66cb1-b36c-4a16-b10f-c3ce7173f391.loom.zip
http://url.data.humancellatlas.org/project-matrices/cddab57b-6868-4be4-806f-395ed9dd635a/9d74bd3e-caaf-4c20-8647-c62f633c6b7a.mtx.zip
http://url.data.humancellatlas.org/project-matrices/2043c65a-1cf8-4828-a656-9e247d4e64f1/39e76cf3-db67-4e9d-aaab-4b7a74d96eb8.csv.zip
http://url.data.humancellatlas.org/project-matrices/2043c65a-1cf8-4828-a656-9e247d4e64f1/06863d28-a4b1-4e35-8a27-31af8a326fd7.loom.zip
http://url.data.humancellatlas.org/project-matrices/2043c65a-1cf8-4828-a656-9e247d4e64f1/dfdd4a14-4ca0-4108-a6f7-52fa2540c61f.mtx.zip

**Comment by GPelayo** [comment]
Snippet for adding the Content-Disposition to matrix files. 

```
key = f'{key_prefix}{filename}'
obj = self.s3.Object(bucket_name, key)
project_uuid = os.path.splitext(filename)[0]
project_name = self._get_project_name(project_uuid) //extracted from azul service (See Below Snippet)
file_name = unicodedata.normalize('NFKD', project_name)
file_name = re.sub('[^\w ,.@%&-_()\\[\]/{}]', '_', file_name).strip()
timestamp = datetime.now().strftime("%Y-%m-%d %H.%M")
content_disposition = f'attachment;filename="{file_name} {timestamp}.tsv"'
assert '\\' not in file_name

with open(filepath, 'rb') as tsv_file:
obj.put(Body=tsv_file,
        ContentDisposition=content_disposition,
        ContentType='text/tab-separated-values; charset=UTF-8')
```


```
def _get_project_name(self, document_id):
        base_url = f'https://service.explore.data.humancellatlas.org/repository/projects/{document_id}'
        response = requests.get(base_url)
        response.raise_for_status()
        project_list = response.json()['projects']
        one(project_list)
        return project_list[0]['projectShortname']
```

**Comment by hannes-ucsc** [comment]
Ready for @theathorn to move to matrix-service.

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/matrix-service/351
