### ISSUE TITLE
Eliminate empty columns in full metadata TSV

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1147]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-718)
┆Project Name: azul
┆Issue Number: AZUL-718

**Comment by hannes-ucsc** [comment]
```
GET azul_bundles_aggregate_dev/_search
{
  "query": {
    "term": {
      "contents.projects.document_id.keyword": {
        "value": "2cd14cf5-f8e0-4c97-91a2-9e8957f41ea8"
      }
    }
  },
  "aggs": {
    "fields": {
      "scripted_metric": {
        "init_script": "params._agg.fields = new HashSet()",
        "map_script": "for (row in params._source.contents.metadata) { for (f in row.keySet()) { params._agg.fields.add(f)}}",
        "combine_script": "return new ArrayList(params._agg.fields)",
        "reduce_script": "Set fields = new HashSet(); for (agg in params._aggs) { fields.addAll(agg) } return new ArrayList(fields)"
      }
    }
  }
}
```

Is a search request with an aggregation that computes the content.metadata.* fields that are actually present in the response.

The problem is that the search request that is currently used to get the metadata out of the bundles index is consumed with the `scan()` helper which I think that does let you access aggregation results in the response. We'd need to issue the request twice, once with the above script aggregation (and no other aggregations) and `"size": 0` to suppress any actual hits in the response, and a second time with scan() but without the aggregation. The first request will tell you all the field names in the response and therefore the column headers for the full TSV, the second request will yield all the rows for that TSV.
