### ISSUE TITLE
Automate Azul health check provisioning in global DCP health check

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1150]
The DCP health check is manually configured and this prevents removal or reprovisioning of Azul's health check automatically. A null provisioner needs to be added to the Terraform configuration of the Azul composite health check which automatically handles removal or addition from the global DCP composite health check.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-720)
┆Project Name: azul
┆Issue Number: AZUL-720

**Comment by hannes-ucsc** [comment]
> The DCP health check is manually configured

To be precise, this is not exactly true. It is managed by TF config in a different repo (dcp-infra). But since a child health check can't be removed while it is referenced by a parent and the parent is managed externally, we need to add custom code to remove the child from the parent if it is about to be deleted and added if was just created. The null provisioner that does this should gracefully handle the absence of the parent or the absence of the child reference in the parent.
