### ISSUE TITLE
Generate service API documentation using OpenAPI

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1163]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-725)
┆Project Name: azul
┆Issue Number: AZUL-725

**Comment by jessebrennan** [comment]
Report:

Swagger/OpenAPI is sufficient for generating documentation for the API. There are several steps to accomplishing this:
- **Serve the Swagger UI from Azul.** This is mostly complete as part of my investigation.
- **Generate the Swagger/OpenAPI spec for the service.** This can be done with Chalice during build time or pulled from APIGateway once deployed. There are pros and cons to each approach, but currently I'm leaning towards the using Chalice.
- **Load the documentation from Azul's docstrings.** It's possible that updating the version of Chalice my be sufficient to accomplish this. Otherwise, if the Swagger spec is generated during build time, the annotations could be added in (with some work). If the Swagger spec is not deployed at build time, then the doc strings will have to be added in during run time which could be a hit to efficiency.
