### ISSUE TITLE
Remove keys in the Azul repo using the BFG repo cleaner

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#1194]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-744)
┆Project Name: azul
┆Issue Number: AZUL-744

**Comment by GPelayo** [comment]
The BFG can redact all the secrets and keys, except the keys in the first commit of the master branch. But this problem can be solved by making a temp commit in the master branch, run the BFG, push the new commits, and delete the new commit. I have a fork of Azul with the secrets and keys removed at https://github.com/GPelayo/azul.

**Comment by GPelayo** [comment]
@shiroyuki fork has been deleted.

**Comment by hannes-ucsc** [comment]
Outstanding work:

- [ ] Delete @shiroyuki fork
- [ ] Delete @hannes fork
- [ ] Ask Github support to delete pull refs for merged and closed branches
- [ ] Commit the BFG report mapping old commits to new commit

**Comment by hannes-ucsc** [comment]
We decided not to delete the PR refs because GH support told us that they are not able to rewrite the refs, they can only delete them. The impact of losing the PR history is not worth it. We already achieved the main goal of removing the secrets from the main branches which allowed us to removed the complicated whitelisting of secrets in Trufflehog and gitsecrets config.

**Comment by hannes-ucsc** [comment]
The repository backups should go into the config bucket, the same bucket that holds the terraform state files. @GPelayo, please reach out to me so we can decide on where in the bucket we place those files.
