### ISSUE TITLE
Review/update fields included in full manifest

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1228]
https://app.slack.com/client/T2EQJFTMJ/CD0PLMWJZ/thread/CD0PLMWJZ-1565948213.075800

From @hannes-ucsc:

My feeling is that we need to revise that list because biomaterial_id, for example, is a very important field.

Don't strip the primary key fields like document_id.

Note to self: gzip

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-765)
┆containerName: azul
┆Issue Number: AZUL-765

**Comment by hannes-ucsc** [comment]
https://github.com/HumanCellAtlas/hca_bundles_to_csv/blob/master/hca_bundle_tools/file_metadata_to_csv.py#L40

Consider including biomaterial_id. Including `process_id` and `protocol_id` makes no sense until https://github.com/DataBiosphere/azul/issues/1229 is resolved because knowing the ID of a bunch of potentially unrelated processes is of no value.

**Comment by theathorn** [comment]
From Simon Jupp:

the idea behind hiding the uuids is that the tsv is meant to be easier to read and consume for humans. As the metadata is all collapsed the use of uuids to work out the links is less of an issue. We should be encouraging programatic users towards the JSON.  I’m not against having the uuids put back in if they are useful, but I’d probably put them all in the final columns so they are somewhat hidden.

**Comment by hannes-ucsc** [comment]
For posterity, here is the field blacklist in Azul, forked from what I [posted earlier](https://github.com/DataBiosphere/azul/issues/1228#issuecomment-522719688):

https://github.com/DataBiosphere/azul/blob/develop/src/azul/project/hca/metadata_generator.py#L35

```
            "describedBy",
            "schema_type",
            "submission_date",
            "update_date",
            "biomaterial_id",
            "process_id",
            "contributors",
            "publications",
            "protocol_id",
            "project_description",
            "file_format",
            "file_name"
```

**Comment by hannes-ucsc** [comment]
This contradicts what Simon claims. In his implementation the `document_id` field is not excluded, but the `biomaterial_id` is. The Azul fork uses the same blacklist. The former is a UUID the latter isn't.

I am doubtful whether any human will exclusively consume this huge TSV visually. They may eyeball first it but in the end they will write code to consume it. Then again I have no authority to decide that.

If the full manifest primary purpose is human consumption I propose to exclude `document_id` and to include `biomaterial_id`:

```diff
--- src/azul/project/hca/metadata_generator.py	(revision 7ea596f34d9b86853a5d8c5e3a29f0d0dd20e385)
+++ src/azul/project/hca/metadata_generator.py	(date 1567111079364)
@@ -37,7 +37,7 @@
             "schema_type",
             "submission_date",
             "update_date",
-            "biomaterial_id",
+            "document_id",
             "process_id",
             "contributors",
             "publications",
``` 

If the primary purpose is programmatic consumption I propose including both

```diff
--- src/azul/project/hca/metadata_generator.py	(revision 7ea596f34d9b86853a5d8c5e3a29f0d0dd20e385)
+++ src/azul/project/hca/metadata_generator.py	(date 1567111432538)
@@ -37,7 +37,6 @@
             "schema_type",
             "submission_date",
             "update_date",
-            "biomaterial_id",
             "process_id",
             "contributors",
             "publications",
```

**Comment by theathorn** [comment]
Make the row key (file_uuid) the first column, then all the human readable columns in some reasonable order and then all the other uuid values at the end.

**Comment by mshadbolt** [comment]
I would argue that both the `biomaterial_id` and `*.provenance.document_id`(uuid) are required because one is only guaranteed to be unique across a project, while the other is unique across all the projects in the DCP. 
I would also argue that the names of these fields could be a lot more consumable. Ideally a user should be able to open a tsv and look at the field names and be able to go straight into coding against it, not have to look up documentation to understand the opaque title, e.g. that `donor_organism.provenance.document_id` actually means, the unique identifier that defines a donor

I guess it's okay to expect programmatic users like portal designers etc. to use the json files because they will put effort into understanding the structure so that they can successfully pull data into their portal on multiple occasions.

The use case I have in mind is a researcher or computational biologist who for example is doing their own research project and wants to compliment their data with HCA DCP data and may only download a HCA metadata tsv once and just wants to harmonise it with their own data. They shouldn't have to put effort into understanding our metadata structure or our json files to be able to do that. 

My ideal case would be that we have a set of default fields we provide and a user is able to select which fields they want to include, like is done in many portals, including ENCODE
![Screenshot 2019-10-08 at 11 32 19](https://user-images.githubusercontent.com/13007987/66389046-570ce900-e9bf-11e9-83c8-fb5ae72a3317.png)

@gabsie probably also has some ideas on how to ensure the way we are providing metadata serves all users that want to consume it

I don't agree all the uuids should go at the end, uuid should be paired with the biomaterial_id it links to, but I do believe the ids should go first in the properties given for that entity i.e. `donor_organism.biomaterial_core.id` `donor_organism.provenance.document_id`. This is already too verbose though and I would probably want to make it more succinct like: `donor_organism.id`, `donor_organism.uuid`

My gut feeling is that usually consumers will want to see everything we've got in terms of metadata, then once they have consumed it a few times they will get a feel for what they actually need and select columns based on that.

**Comment by hannes-ucsc** [comment]
> I would argue that both the biomaterial_id and *.provenance.document_id(uuid) are required because one is only guaranteed to be unique across a project, while the other is unique across all the projects in the DCP.

https://github.com/DataBiosphere/azul/issues/1367 covers that.

> I would also argue that the names of these fields could be a lot more consumable. Ideally a user should be able to open a tsv and look at the field names and be able to go straight into coding against it, not have to look up documentation to understand the opaque title, e.g. that donor_organism.provenance.document_id actually means, the unique identifier that defines a donor

I think it's important that the column names match the metadata field names. If we were to invent new, shorter names, this would only cause ambiguity and confusion. The metadata fields are documented on the portal and we could be doing a better job at linking to that page from Get Data dialog.

> They shouldn't have to put effort into understanding our metadata structure or our json files to be able to do that.

I think this is conflating two things: the metadata graph structure and the metadata document structure. I agree that, since the full manifest flattens the graph structure, we shouldn't (and currently don't, I think) require metadata users to understand it. But when it comes to metadata document structure, I'd be afraid of the researcher who can't figure out a column's meaning by looking it up in the documentation. Yes, some some field have awkwardly long names, but if this is stopping anyone one from using the manifest, I'd say good riddance. The column names don't need to be succinct or self-explanatory, they need to be unambiguous and consistent with the schema.

> I don't agree all the uuids should go at the end,

The full manifest is very wide, and no column ordering is going to make everyone happy. For programmatic consumption column ordering does not matter. We may want to make the ordering deterministic, by sorting them lexicographically by column name. That makes it easier to diff them.

> My ideal case would be that we have a set of default fields we provide and a user is able to select which fields they want to include, like is done in many portals, including ENCODE

Agreed, we could implement that relatively easily.

**Comment by mshadbolt** [comment]
I take your points and agree that changing names can get messy for a lot of reasons. I just really dislike the `provenance.document_id` because these fields are arguably the most important to pivot on when you are trying to understand the metadata and it is just so not obvious that this is the unique id for an entity by the name. 

We are getting some feedback from the UX team about our metadata next week so it will be good to hear 'from the horses mouth' about where users are struggling with using our metadata. 

I understand what you mean about programmatic interpretation not being reliant on ordering but do keep in mind that in many instances the first time the tsv/manifest is opened it will be probably by a human who wants to take an overview look in excel to understand the columns and general data structure before they sit down and write a program to extract the information they need.

I definitely think that improving our documentation will go a long way to making our metadata more usable and we have this as a key focus in the metadata team at the moment.

**Comment by theathorn** [comment]
Obsolete DCP/1 issue.
