### ISSUE TITLE
Invalidate cached manifest when a project is updated

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1242]
Currently we update the cache version of the project metadata tsv file once a day.

Since projects change infrequently following initial ingestion, it would be better to invalidate the cached version when a project is updated.

When would the new version be generated? On first user demand?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-772)
┆Project Name: azul
┆Issue Number: AZUL-772

**Comment by hannes-ucsc** [comment]
1) Track version of project as the maximum version of a contributing bundle

2) Incorporate project version in manifest hash

Optimizations:

3) Add a `cron` function to periodically request the full manifest for each project (not exactly part of the solution but this makes it less likely that users will have to wait for the manifest to be generated after it was invalidated)

4) Use a heuristic to prevent multiple concurrent step function executions for the same hash. This is difficult because step functions does not let you retrieve functions by name, only by ID and you don't control the ID.

**Comment by achave11** [comment]
A query that generates a Hash for a specific query.
```
{
  "size": 0, 
  "query": {
    "match_all": {}
  },
  "aggs": {
    "fields": {
      "scripted_metric": {
        "init_script": "params._agg.fields = 0",
        "map_script": "for (bundle in params._source.bundles) { params._agg.fields += (bundle.uuid + bundle.version).hashCode()}",
        "combine_script": "return params._agg.fields.hashCode()",
        "reduce_script": "int result = 0; for (agg in params._aggs) { result += agg } return result"
      }
    }
  }
}
```
