### ISSUE TITLE
Files being linked to AnalysisProtocol

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/azul#132]
In the integration environment, we get the following error:
```
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/app.py", line 125, in _index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 54, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 152, in create_documents
    bundle = api.Bundle(dss_bundle)
  File "/var/task/azul/project/hca/metadata_api/__init__.py", line 459, in __init__
    source_entity.connect_to(destination_entity, forward=True)
  File "/var/task/azul/project/hca/metadata_api/__init__.py", line 94, in connect_to
    self._connect_to(entity, forward)
  File "/var/task/azul/project/hca/metadata_api/__init__.py", line 367, in _connect_to
    raise ValueError(f"File only connects to process, not {entity}")
ValueError: File only connects to process, not AnalysisProtocol(document_id=UUID('a7d17513-ebc2-4e13-b79d-bba06b7414e3'), _json={...},...)
```
This is from bundle fqid `127858fb-0057-4f4d-afb9-93d7040a36fe.2018-07-12T003446.939647Z`.

If you look at the `links.json` of this bundle, you can see that files point to the `analysis_protocol` and the `analysis_protocol` points to files (which results in this error). We need to consult and confirm if this is a valid link. It's worth noting that this appears to be only present in analysis bundles.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-104)
┆Project Name: azul
┆Issue Number: AZUL-104

**Comment by samanehsan** [comment]
@hannes-ucsc, the files that the analysis pipeline outputs should be linked to a process, since they are the result of a particular run of the pipeline. My understanding of protocol vs. process is that the analysis protocol contains fields that are consistent between runs of a pipeline and the analysis process contains fields that vary (e.g inputs and outputs), as shown in this PR: https://github.com/HumanCellAtlas/metadata-schema/pull/396

**Comment by hannes-ucsc** [comment]
@samanehsan Ok, so we agree that we expect the link to be between `file` and `process`, not `file` and `protocol`. The bundle that @caaespin mentions links files to protocols, though, at least according to the `destination_type`:

```
{
    "describedBy": "https://schema.humancellatlas.org/bundle/1.0.0/links",
    "schema_type": "link_bundle",
    "schema_version": "1.0.0",
    "links": [
        {
            "source_type": "file",
            "source_id": "100b2f94-2909-488b-9259-93e238b8a64a",
            "destination_type": "analysis_protocol",
            "destination_id": "a7d17513-ebc2-4e13-b79d-bba06b7414e3"
        },
…
```

Is that a bug?

**Comment by samanehsan** [comment]
@hannes-ucsc, on the master branch of the `metadata-schema` repo, there's only an analysis_protocol.json file which is probably why this bundle links a `file` to a `protocol`. We realized that we actually need both an `analysis_protocol.json` and `analysis_process.json` file, so that change is now in the develop branch. So it sounds like the links.json will need to change to show that the `file` is produced by an `analysis_process`.

**Comment by hannes-ucsc** [comment]
@samanehsan, thanks the explanation. Sorry for being a bit slow here. Does this mean that linking file to protocol is valid against `metadata-schema/master`? I'm asking because none of the preview bundles in production link files that way. They all link process to file and process to protocol. Then again, they are not analysis bundles.

> So it sounds like the links.json will need to change to show that the file is produced by an analysis_process

Who needs to do that? It looks like the changes from PR396 have already landed on `metadata-schema/integration`. Did Green already implement the generation of bundles that use `analysis_protocol` and `analysis_process`. If so did Green already roll that out to `integration`?

**Comment by hannes-ucsc** [comment]
I still think this is a bug in green but it might be fixed as a side-effect of their effort to move to vx bundles. If not, this issue will be escalated and gain exposure by #217.

**Comment by samanehsan** [comment]
I know @rexwangcc mentioned he is working on linking the analysis process to analysis protocol to follow the new metadata schema changes.

**Comment by theathorn** [comment]
For Hannes to close - no longer an issue.

**Comment by hannes-ucsc** [comment]
Newly arriving analysis bundles in integration and staging don't have this issue anymore. It must have been fixed by Green inadvertently.
