### ISSUE TITLE
Allow sorting on donor count

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/azul#1378]
As per @ambrosejcarr on [#858](https://github.com/HumanCellAtlas/data-browser/issues/858):

> I was surprised that I wasn't able to sort based on those columns. At least for the cell count, as an Analysis Roadbuilder, I want to be able to find the datasets with the largest amount of cells because those datasets have the largest information content and promise to be the most effective at helping me train my cell biology-focused machine learning methods.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-841)
┆Project Name: azul
┆Issue Number: AZUL-841

**Comment by hannes-ucsc** [comment]
Azul supports sorting on cell count:

```
$ http 'https://service.explore.data.humancellatlas.org/repository/projects?filters=%7B%7D&size=15&sort=cellCount&order=desc' | jq '.hits[].cellSuspensions[].totalCells'
1480000
1330000
339089
274182
253910
230800
15175
44615
44000
30000
30000
20000
19916
16893
12404
10001
12109
2464
1432
1580
10561
5862
1638
1391
7115
2663
1961
1923
951
1718
4149
1151
5355
981
865
```

**Comment by hannes-ucsc** [comment]
For donor count, it looks like DB is counting the number of items in `hits[].donorOrganisms[0].id`. That's unreliable because I'm pretty sure we cap the number of items in that field. 

Azul should be extended to track the number of donors during aggregation. We should expose that number as a response field as `hits[].donorOrganisms[0].donorCount`. In the index, the corresponding `contents.donors[].donor_count` field should only be present in aggregate documents and it should be computed at aggregation time as the size of the `contents.donors[].biomaterial_id` field set. There may be a few novelties in this approach but I'll discuss those with the assignee.

**Comment by hannes-ucsc** [comment]
Since sorting on cell count is already possible, I changed the title accordingly.
