### ISSUE TITLE
Enforce consistent ordering of imports

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1432]
When creating a commit, PyCharm can be [configured to automatically apply some checks and formatting](https://www.jetbrains.com/help/pycharm/commit-changes-dialog.html#before_commit).

Setting these options by default for all developers should help maintain code quality, but necessitates that developers' code configurations are all in sync.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-878)
┆Project Name: azul
┆Issue Number: AZUL-878

**Comment by hannes-ucsc** [comment]
I changed the title because the source formatting aspect is already implemented. 

Yes, deterministic ordering and formatting imports would minimize diffs and reduce the potential for merge conflicts. However, there needs to be enforcement of this on CI. I would have implemented this already when I implemented `make format` but the CLI to reformatting [doesn't have a flag](https://www.jetbrains.com/help/pycharm/command-line-formatter.html) for enabling the optimization of imports:  while the [GUI does](https://www.jetbrains.com/help/pycharm-edu/reformat-file-dialog.html).

**Comment by jessebrennan** [comment]
I see. I was imagining adding something to the contributing guide, which would inform developers of our practice. Probably the configurations would need to be shared there as well.

**Comment by hannes-ucsc** [comment]
> I was imagining adding something to the contributing guide, which would inform developers of our practice.

What would that addition say, in a nutshell? The rules that PyCharm applies are fairly elaborate and would be tedious to describe and follow manually. Maybe we should just say "load the config file and be sure to always reformat with import optimization enabled".

> Probably the configurations would need to be shared there as well.

I think it's already there:

https://github.com/DataBiosphere/azul/blob/develop/.pycharm.style.xml#L17

**Comment by jessebrennan** [comment]
That's exactly what I was thinking. The only other remaining change would be to update the existing code base to optimize the imports wholesale (if you think that that is worth while).

**Comment by hannes-ucsc** [comment]
The problem is that without enforcement, people will forget, because I can't check imports are optimized when reviewing PRs (since I am not a robot). That's why I think don't think we should act on this until we have a way to enforce it on CI. Sure, we could optimize imports now only to have them slowly get unoptimized over time.

Maybe https://github.com/PyCQA/flake8-import-order is compatible enough with PyCharm's optimization algo.

**Comment by hannes-ucsc** [comment]
I gave that plug-in a whirl. To make the plugin and pycharm agree on the ordering I had to enable this option

![image](https://user-images.githubusercontent.com/5143256/69125084-d4fdee80-0a59-11ea-9d93-904e7ae1262b.png)

I need to decide if I like care about this option. If I do, we would need to write our own [import ordering style](https://github.com/PyCQA/flake8-import-order#extending-styles).

I also had to list all modules and packages in the `test` directory under --application-import-names which was cumbersome. We should probably make `azul` a namespace package so we can have an `azul` directory under `test` as well as under `src`. Unfortunately, `src/azul/__init__.py` has stuff in it which would need to go somewhere else (namespace packages aren't allowed to have an __init__.py).

PyCharm wrongly identifies the stubs in `stubs` as belonging to the application while the plugin correctly identifies them as third party. The plugin incorrectly identifies dataclasses as stdlib (it is not stdlib in 3.6, only in 3.7). So we would need to upgrade to Python 3.7 first to avoid this bug in the plugin.

The plugin gets confused by the `from lambda.service import app` crap I wrongly assumed we had already eliminated. There are also mock.patch invocation for `lambda.service.app.…`. We need to clean that up ASAP.

**Comment by hannes-ucsc** [comment]
> The plugin gets confused by the from lambda.service import app crap I wrongly assumed we had already eliminated. There are also mock.patch invocation for lambda.service.app.…. We need to clean that up ASAP.

#1461, PR #1466

**Comment by hannes-ucsc** [comment]
To summarize the marching orders: We should use the flake8 plugin on Travis and Gitlab to check if the imports are valid. Valid means no redundant imports, no unused imports and imports should be sorted. To determine how to sort them should be a matter of reconciling the PyCharm import sorting algo and whatever rules can be defined for the plugin.

Ideally, the plugin should accept the order produced by PyCharm.

But the ultimate underlying goal here is to minimize diffs. So what that implies is that the plugin should reject

```
from foo import bar
```

Because that could later change to

```
from foo import (
    bar,
    baz,
)
```

and even later back to 

```
from foo import (
    bar,
)
```
or 

```
from foo import (
    baz,
)
```

This defeats the goal of minimizing diffs. I see two solutions: 

A) ignoring PyCharm's inability to generate a multiline import even if there is only one imported symbol

```
from foo import (
    bar,
)
```

when it adds that import. The build would fail in `make pep8` and the developer would have to manually make the conversion to a multiline import. Optionally, we could offer tooling to automate the conversion `make sort_imports` but I don't know if such tooling exists.

B) Use PyCharm's `Always split imports` option:

![image](https://user-images.githubusercontent.com/5143256/81855741-992d7880-9514-11ea-8eb5-3434a7a2623c.png)

which produces this:

```diff
Index: src/azul/indexer/index_service.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/azul/indexer/index_service.py	(revision 897613af595839ca38cf29cccd09d066ab741d7a)
+++ src/azul/indexer/index_service.py	(date 1589397748645)
@@ -1,32 +1,24 @@
-from collections import (
-    Counter,
-    defaultdict,
-)
+from collections import Counter
+from collections import defaultdict
 from itertools import groupby
 import logging
 from operator import attrgetter
 import time
-from typing import (
-    Iterable,
-    List,
-    Mapping,
-    MutableMapping,
-    MutableSet,
-    Optional,
-    Sequence,
-    Tuple,
-    Union,
-)
+from typing import Iterable
+from typing import List
+from typing import Mapping
+from typing import MutableMapping
+from typing import MutableSet
+from typing import Optional
+from typing import Sequence
+from typing import Tuple
+from typing import Union
 
-from elasticsearch import (
-    ConflictError,
-    ElasticsearchException,
-)
-from elasticsearch.helpers import (
-    parallel_bulk,
-    scan,
-    streaming_bulk,
-)
+from elasticsearch import ConflictError
+from elasticsearch import ElasticsearchException
+from elasticsearch.helpers import parallel_bulk
+from elasticsearch.helpers import scan
+from elasticsearch.helpers import streaming_bulk
 from humancellatlas.data.metadata.helpers.dss import download_bundle_metadata
 from more_itertools import one
 
@@ -35,21 +27,19 @@
 import azul.dss
 from azul.es import ESClientFactory
 from azul.indexer.document_service import DocumentService
-from azul.indexer.transformer import (
-    Aggregate,
-    BundleUUID,
-    BundleVersion,
-    Contribution,
-    Document,
-    DocumentCoordinates,
-    Entities,
-    EntityID,
-    EntityReference,
-    EntityType,
-    FieldTypes,
-    Transformer,
-    VersionType,
-)
+from azul.indexer.transformer import Aggregate
+from azul.indexer.transformer import BundleUUID
+from azul.indexer.transformer import BundleVersion
+from azul.indexer.transformer import Contribution
+from azul.indexer.transformer import Document
+from azul.indexer.transformer import DocumentCoordinates
+from azul.indexer.transformer import Entities
+from azul.indexer.transformer import EntityID
+from azul.indexer.transformer import EntityReference
+from azul.indexer.transformer import EntityType
+from azul.indexer.transformer import FieldTypes
+from azul.indexer.transformer import Transformer
+from azul.indexer.transformer import VersionType
 from azul.types import (
     JSON,
 )
```

Note how it missed the singleton multiline import. Other proposed solutions are welcome, the prime directive being to minimize diffs and have strict, deterministic enforcement in CI.

**Comment by noah-aviel-dove** [comment]
Tried [flake8-import-single](https://pypi.org/project/flake8-import-single/) to enforce consistency with split imports, but it failed to report imports with unnecessary and even-multi-lined usage of parentheses. Looking at the source code for the plugin, it only checks that one name is imported per statement, and performs no actual verification of how the statements are split across lines.

**Comment by noah-aviel-dove** [comment]
Tried [flake8-strict](https://github.com/smarkets/flake8-strict), which provides a "multi-line construct lacks trailing comma" option, but once again it fails to recognize single-name parenthesized imports as multi-line, I believe because the containing parentheses are not considered distinct syntax elements.

**Comment by noah-aviel-dove** [comment]
Tried [flake8-import-order](https://pypi.org/project/flake8-import-order/) but it contradicts PyCharm's sort order and the contributing guide

**Comment by noah-aviel-dove** [comment]
Revisited flake8-import-order but still can't get it to cooperate. Specifying `import-order-style=pcyharm" helps significantly but its import classification heuristic falsely detects some azul modules as third-party instead of local, and `from` imports appear to be sorted by the imported name instead of their module of origin.

Examples of incorrect errors:
```
$ pip install flake8-import-order==0.18.1
$ flake8 --max-line-length=120 --import-order-style=pycharm test/service/test_dss_proxy.py
test/service/test_dss_proxy.py:11:1: I100 Import statements are in the wrong order. 'import requests' should be before 'from moto import mock_s3'
test/service/test_dss_proxy.py:14:1: I202 Additional newline in a group of imports. 'from app_test_case import LocalAppTestCase' is identified as Third Party and 'import responses' is identified as Third Party.
```

**Comment by hannes-ucsc** [comment]
@noah-aviel-dove to create lottery on Slack. The "winner" gets to fix all rule violation.
