### ISSUE TITLE
Queue manager should not use "special" way of enumerating queues

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1448]
Instead of [listing all queues and filtering by name pattern](https://github.com/DataBiosphere/azul/blob/911a8f2c7adb8d7c7201b2fa9159b72f8de29c6e/src/azul/queues.py#L139), `queues.py` should determine the candidate queue names from `config.all_queue_names` and gracefully ignore queues that don't exist.

All clients of the queue manger (especially `reindex.py` for example) should be checked if they can benefit from the refactoring.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-890)
┆containerName: azul
┆Issue Number: AZUL-890

**Comment by danielsotirhos** [comment]
Resolved in PR https://github.com/DataBiosphere/azul/pull/1462 by commit https://github.com/DataBiosphere/azul/pull/1462/commits/74fcd4219af822e5c05777d1bd4c2ab769136934

**Comment by achave11** [comment]
@hannes-ucsc it seems like this issue was resolved by @danielsotirhos PR, I confirmed that queues are fetched from SQS by name, compared to the previous implementation of listing all available queues from SQS and parsing out the ones not associated with Azul. I am just wondering if there is alternative work required to close this ticket, perhaps something not specified in the description?

**Comment by hannes-ucsc** [comment]
You are right, @achave11. 

@danielsotirhos to demo.
