### ISSUE TITLE
Enable direct DSS access via configuration

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1533]
The direct access code falls back to normal access but attempting direct access takes time for every bundle and file and we should be able to completely disable direct access in a particular Azul deployment.

**Comment by jessebrennan** [comment]
@hannes-ucsc and I tried modifying the policy for the DSS backend bucket so that it would allow the platform-sc account direct access. This was unsuccessful because of ACLs exist for every object in backend bucket that prevent access from an outside account. A path forwards would have been to recursively modify all of the policies so that we could access them, but this seemed unsustainable. 

Instead of modifying the ACLs, we will just disable direct access. This will get the new deployment up and running quickly. To get direct access working in the platform-sc deployment we can use an assumed role as outlined in #1453. 

Direct access should be configured by an environment variable and be deactivated by default.
