### ISSUE TITLE
Assume role to enable direct DSS access and DRS proxy across accounts

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1536]

**Comment by hannes-ucsc** [comment]
It turns out that it is not possible to enable read-access to a bucket across AWS accounts by just changing permissions on the bucket. One would have to change the permissions on every object in the bucket and ensure that these permissions are also set on new objects created in the future. This is both invasive and requires the cooperation of—and making changes to—the DSS in the destination account.

The only alternative, as @jessebrennan found out, is for the Azul indexer to assume an IAM role in the destination AWS account. This requires more extensive code changes in Azul and more invasive privilege changes to the IAM setup in the destination account.

I also forgot to mention that the files proxy and DRS/DOS emulation in Azul relies on direct access, too. So in essence, while direct access is optional for increasing performance, it is required for deletions, the DRS/DOS proxy and direct downloads from the Data Browser.

**Comment by hannes-ucsc** [comment]
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_terms-and-concepts.html#iam-term-role-chaining

> Role chaining limits your AWS CLI or AWS API role session to a maximum of one hour.

This would imply that the signed URLs handed out by the proxy have a one hour expiration.

**Comment by hannes-ucsc** [comment]
@achave11 proposed chaining the file proxies and DRS/DSS emulations. The SC instance would proxy the HCA instance which would proxy the HCA DSS instance.

**Comment by hannes-ucsc** [comment]
I've experimented with this and it works with my admin credentials to the SC account. I can assume the indexer role in the HCA sandbox and the direct access tests pass locally on my machine. I think I am going to take this on for today.

**Comment by hannes-ucsc** [comment]
Tickets #1559, #1560 and #1561 were created for left-over work.
