### ISSUE TITLE
Manifest generation fails for 'full' format when a filter is provided. 

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1596]
* The filter provided must yields a large set of results. In order to reproduce this failure.

* Small sets of results via the filter do not generate failures.

**Comment by achave11** [comment]
- [ ] Pass generated object key to request when cached object is not available.

**Comment by hannes-ucsc** [comment]
We now know what the cause is and will be implementing several measures to prevent memory exhaustion on AWS Lambda: 1) prevent a large number of pending MP upload parts from accumulating and 2) garbage collect the previous page of ES scan() results while the next one is being fetched, halfing the memory usage.

I've bumped the estimate up. It now account for the more complex investigative efforts during the spike and for the remainder of the implementation work.
