### ISSUE TITLE
In new main deployments, lambdas need to dynamically look up ES endpoint

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1704]
It is possible that Terraform might allow for the provisioning of the Chalice-Terraform lambdas with references to resources that have not been created using the Terraform syntax.
For example:
```
${aws_elasticsearch_domain.elasticsearch.endpoint}
```
Can be used instead to replace `AZUL_ES_ENDPOINT` when provisioning the lambdas.

This would allow for Terraform to replace references with valid values at creation time. Allowing for `make deploy` (command name might be replaced soon) and `make terraform` to be ran only once. 

A forceable problem is that deployments sharing an Elasticsearch domain would have difficulties provisioning the resources with the appropriate references. Whoever, this could be solved by using Terraform Data Sources. Allowing for multiple deployments to fetch/provision references to the shared resources.

**Comment by jessebrennan** [comment]
When provisioning a new deployment that will not share its ES instance, lambdas need to infer the ES endpoint dynamically. We can work around this inefficiency by deploying the lambdas again (i.e. running `make deploy` and `make terraform` a second time).

Now that the lambdas are provisioned via Terraform we can reference the [ES endpoint](https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html#endpoint) property within the lambdas' Terraform configuration. This way, the lambdas won't need to do a dynamic look-up when provisioned the first time.

Deployments that use the already provisioned ES instance of another deployment won't be able to reference the necessary Terraform property. Terraform Data Sources could be used in those cases since they give you access to the Terraform properties of cloud resource that is provisioned elsewhere.

**Comment by hannes-ucsc** [comment]
> This way, the lambdas won't need to do a dynamic look-up when provisioned the first time.

To be precise, the dynamic lookup of the ES endpoint happens *every* time the lambda needs to connect to ES, and will have to be done until the lambda is deployed (by running `make deploy && make terraform`) a *second* time.

We should also mention that this behaviour is a quirk of the fix for #1688.
