### ISSUE TITLE
Estimate link duplication

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1727]
Continuation of #1720:

If possible I'd like a measure of the duplication among all `links.json` files. I think now that we [know](https://github.com/DataBiosphere/azul/issues/1720#issuecomment-618737341) how many copies of links there exists, I'd like to know how many unique links there are. We've established that the "process" field uniquely identifies a link,  so we just need to count the number of unique process IDs, ideally per link category i.e., a value for the TBD placeholders in the screenshot below.

![image](https://user-images.githubusercontent.com/5143256/80235543-b1456280-860e-11ea-9f90-dfa582e8606f.png)

**Comment by amarjandu** [comment]
@hannes-ucsc 

```
total_processing hits: 531459
total number of unique processing ids: 239547
size in bytes of largest links_json: 1289697
{2: {'number_of_bundles': 80, 'unique_process_ids': 160},
 3: {'number_of_bundles': 134161, 'unique_process_ids': 211657},
 4: {'number_of_bundles': 2619, 'unique_process_ids': 5780},
 5: {'number_of_bundles': 1768, 'unique_process_ids': 3565},
 7: {'number_of_bundles': 10141, 'unique_process_ids': 30438},
 11: {'number_of_bundles': 1733, 'unique_process_ids': 5205},
 14: {'number_of_bundles': 6, 'unique_process_ids': 29},
 15: {'number_of_bundles': 6, 'unique_process_ids': 35},
 17: {'number_of_bundles': 3, 'unique_process_ids': 19},
 769: {'number_of_bundles': 25, 'unique_process_ids': 9637}}
```

please note that the sum of the `unique_process_ids` (266525) is different than the `total number of unique processing ids`. This is because `unique_processing_ids` is unique for a given number of links present in the links.json file, and not the overall set of `processing_ids`. For a given `processing_id` it is possible for the `processing_id` to be present in multiple subsets. 

See https://github.com/HumanCellAtlas/data-store/blob/amar-es-links/ESController.py for script inspection.

**Comment by amarjandu** [comment]
see https://github.com/HumanCellAtlas/data-store/blob/master/scripts/smugglers-box/links_inspection.py for scripts.

**Comment by hannes-ucsc** [comment]
Link gives 404.
