### ISSUE TITLE
Evaluate changes required to "HCA-SCEA Metadata Converter" for DCP/2

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1800]
Single Cell Expression Atlas has written their own [metadata converter](https://docs.google.com/document/d/1NjxZ5aF9-ZXmF20_ddEhqFUiClQAKcbC8xZYjKY3QUc) which uses the DSS 1.0 API and HCA CLI to extract metadata and fastq files from the DCP.

We need to advise/assist them in support for DCP/2 where TDR replaces DSS.

**Comment by theathorn** [comment]
Editable copy of metadata converter [doc](https://docs.google.com/document/d/1YYaTlUQLdJiJCCvAf8aWVLIFVqWimGrMMS4O6Aof2QU).

**Comment by danielsotirhos** [comment]
The ["HCA to Atlas Metadata Converter"](https://github.com/ebi-gene-expression-group/hca-cdm) is currently using HCA's DSSClient class to [request project bundles](https://github.com/ebi-gene-expression-group/hca-cdm/blob/3b21d57e0ccd71b11d294cf773d3ee7e352f6749/hcacdm/ProjectImporter.py#L65).

For DCP/2 this will need to be changed to a new client that will access the TDR and fetch data through BigQuery queries. 

Due to the way Azul flattens the nodes of a graph when indexing projects, Azul's API would not be useful to the "HCA to Atlas Metadata Converter" as a source of project metadata.

**Comment by theathorn** [comment]
I've discussed this with Kathleen Tibbetts and Tony burdett (https://humancellatlas.slack.com/archives/G011CE5UNRL/p1595878176017600) - closing.
