### ISSUE TITLE
Reindexing is slow

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#182]
Reindexing is slow because of contention on specimen documents. Many bundles touch the same specimens. If those bundles are indexed concurrently, they will incur an excessive number of retries caused by conflicts when more than one thread updates the same specimen document. If we use a separate index for the `/projects` endpoint (instead of aggregations over the specimens index), contention on project documents will be even worse.

Indexing bundles serially eliminates the contention but is also slow (12h for the preview bundles).

To solve this we will insert an SQS FIFO queue between the transformers and the code that updates the index. Each document should have its own message group in that queue. Each message in that queue will be a bundle contribution to a document. SQS FIFO queues guarantee that only one message from a particular message group is in-flight. This will serialize access to a document. ReceiveMessage on a FIFO also tries to gather multiple message from the same group and return them as a batch. This batching will allow us to further reduce the # of ES round-trips per document.

Until recently consuming a queue from a Lambda was expensive (because and the Lambda had to run continuously) and throughput was limited (because only one lambda can be started every minute). Switching to the recently introduced SQS Lambda trigger fixes both issues. We should use it for both the notification queue and the new document update queue.

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-135)
┆Project Name: azul
┆Issue Number: AZUL-135

**Comment by shiroyuki** [comment]
We could copy some idea from the Unit of Work pattern to help us in this case. But, before we discuss about how we can utilize that pattern, let's talk about what the reindexing process might look like after the original proposal.

```
Local/Reindexer -----> Lambda/Indexer --+--> Lambda/Indexer
                       (Main Listener)  |    (File FIFO Listener)
                                        |
                                        +--> Lambda/Indexer
                                        |    (Specimen FIFO Listener)
                                        |
                                        +--> Lambda/Indexer
                                             (Project FIFO Listener)
```

The idea is that the reindexer and the index record what needs to be stored eventually in the memory. At every `x` number of bundles or the last pulled bundle, the indexer will push the bundles which hasn't been marked as "stored" and then make them as "stored". The code will look like this.

```
Local/Reindexer -------+--> Lambda/Indexer
                       |    (File FIFO Listener)
                       |
                       +--> Lambda/Indexer
                       |    (Specimen FIFO Listener)
                       |
                       +--> Lambda/Indexer
                            (Project FIFO Listener)
```

**Pros:**
* Reduce the amount of messages published to any SQS queues.
* Faster reindexing

**Cons:**
* The reindexer will have to do some work of the indexer. Hence, the rate of publishing messages from the reindexer is much lower due to pre-computation.
* The machine running the reindexer will need a lot more CPU, memory or disk space to accommodate the staging data.

**Comment by hannes-ucsc** [comment]
To put things in perspective: Reindexing `prod` used to take 12 hours. It now takes 12min.
