### ISSUE TITLE
ES version is 6.8.0, `elasticsearch` requirement is 6.8.1

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1887]
Does that discrepancy matter?

**Comment by achave11** [comment]
Excerpt from [Elasticsearch Java High Level REST Client](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.8/java-rest-high-compatibility.html)

```txt
The 6.0 client is able to communicate with any 6.x Elasticsearch node, while the
6.1 client is for sure able to communicate with 6.1, 6.2 and any later 6.x version,
but there may be incompatibility issues when communicating with a previous
Elasticsearch node version, for instance between 6.1 and 6.0, in case the 6.1 client
supports new request body fields for some APIs that are not known by the 6.0 node(s).
```

IFAK we aren't running into the potential issues describe above, however, it isn't too far fetch that one might modify request body fields being passed in to the client. For that reason, it might be desirable to have a matching client and server version.

**Comment by hannes-ucsc** [comment]
Could you elaborate on why a statement about the compatibility of the Java client across minor versions applies to how the Python client behaves across patch levels versions?

**Comment by achave11** [comment]
> Could you elaborate on why a statement about the compatibility of the Java client across minor versions applies to how the Python client behaves across patch levels versions?

@hannes-ucsc Ah, this was a misunderstanding in my behalf. For some reason I assumed the patch version was a minor version. I should have been reading the elasticsearch-py documentation, and not the one in elastic.co, my bad.

In the pypi documentation for elasticsearch, under [Compatibility](https://pypi.org/project/elasticsearch/6.8.1/#compatibility), I was able to find the answer to our question. "[Does that discrepancy matter?](https://github.com/DataBiosphere/azul/issues/1887#issue-635880722)" and the answer is no, it does not matter. The documentation claims "The library is compatible with all Elasticsearch versions since 0.90.x ... For Elasticsearch 6.0 and later, use the major version 6 (6.x.y) of the library."

**Comment by hannes-ucsc** [comment]
Good. Looks like 6.8.1 is the most recent 6.x.y version so we can leave everything as is.

To demo show the respective documentation section.
