### ISSUE TITLE
Compress responses to clients sending `accept-encoding: gzip` header

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#1910]

**Comment by melainalegaspi** [comment]
@NoopDog to investigate potential gains. @noah-aviel-dove to investigate if we can enable gzip compression on API gateway.

**Comment by hannes-ucsc** [comment]
https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1618623078221900?thread_ts=1618590719.217100&cid=C705Y6G9Z

**Comment by hannes-ucsc** [comment]
We're looking at a 15% improvement

![image](https://user-images.githubusercontent.com/5143256/116167735-b6bc0980-a6b5-11eb-9b80-be76b92c6d58.png)

assuming that we can reduce the green portion of the timing diagram down to 25%

**Comment by noah-aviel-dove** [comment]
It's very easy to enable compression on API gateway. All we need to do is specify a nonnegative value for `minimum_compression_size` in the chalice config.

```
$ curl https://service.nadove.dev.singlecell.gi.ucsc.edu/index/catalogs -H 'accept-encoding: gzip'  --output -; echo
Ցъ1
     E�%�3�L]�+�R�4j�ږ6#�0�n�+
�"��>��$�9�	,mp�ld�q
                         ��4p
��O���Ѓޠ/��G��݀����uA��	��H�R,�c>J?��jl�%�y�:\��m���ZK�֊�.S�E��Fu��U�2L�?��B/������'ƺu���2�
                                                                                                 Bk�2,�Z��pf�z�{���M&��7�D0��?�����U�oM
```

**Comment by noah-aviel-dove** [comment]
I tried to time the requests to find the inflection point where compression becomes inefficient for small responses, but the round-trip elapsed time was too inconsistent regardless of payload size or compression to find any discernible pattern.

**Comment by hannes-ucsc** [comment]
This isn't observable in `prod`, only on `dev`.

`dev`:

![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/616afb8b-4c25-444f-99f0-1d1e1d79c6f6)

`prod`:

![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/9f67a452-a131-4e01-89f4-d34d550f64d0)

**Comment by hannes-ucsc** [comment]
Hannes to investigate ^^^

**Comment by theathorn** [comment]
@hannes-ucsc to file a ticket with AWS support.

**Comment by hannes-ucsc** [comment]
Case # 8354981671

**Comment by hannes-ucsc** [comment]
Response from AWS support:

> From further review, I discovered that the last recorded stage update was done on 2021-05-05T00:14:00.000Z UTC. Please note that any changes to your api are not live to the public until the updates are redeployed. To deploy from within the web console, go to 'Resources' from the navigation menu on the left. Then under 'Actions', select 'Deploy Api' and select the 'prod' stage. After a few seconds, you should be able to test with the latest saved settings.

That fixed it:

![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/5d34c9d3-42a4-490f-8b9d-f7268cf18afe)

Timings vary but improved by the expected 10-20%, barely noticeable, subjectively speaking.

![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/82075366-1c3d-4e73-94ad-ef198d5979fd)

However, we shouldn't need to manually redeploy the stage. TF should do that for us. I was gonna chalk this up to https://github.com/DataBiosphere/azul/issues/1951 but that fix was deployed at the same time, so it should have been active. My 2nd best guess is that the cause is in the vicinity of 
https://github.com/DataBiosphere/azul/issues/2992 since that also messes with deployment stages.
