### ISSUE TITLE
Large number of DRS/DOS endpoint failures in prod

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1934]
![image](https://user-images.githubusercontent.com/5143256/85805027-147f6e00-b700-11ea-8e37-1d3742f95812.png)

We need to know the distribution of HTTP statuses over endpoints. For each endpoint that was requested in the above time frame, what percentage where 2xx responses and what percentage were 4xx and 5xx responses.

We also like to know the top 100 client IP addresses.

Most importantly, I would like to track this down to a manifest requests that started all this. My hypothesis is that someone started initiated a Terra hand-over and then actually started a workflow. If that's true, there must be a manifest request at the beginning. The IP address for that client would be interesting. 

The `/aws/apigateway/azul-service-prod` log group is probably most useful for this. Note the `stats` feature of the CloudWatch insights query language.

**Comment by achave11** [comment]
The following table shows the distribution of Status codes per endpoint for the period of interest. 
|resourcePath|Status 200|Status 404|Status 500|Status 503|Status 504|
|-|-|-|-|-|-|
|/repository/summary|272||3||2|
|/repository/samples|265||17||4|
|/repository/projects/{project_id}|115|||||
|/repository/projects|526||21||4|
|/repository/files|268||17||4|
|/repository/bundles|1790||16||3|
|/integrations|37|||||
|/health/{keys}|3057|||225||
|/ga4gh/dos/v1/dataobjects/{file_uuid}|9073|12735|186490||13966|
|/fetch/manifest/files|53|||||

Next is a table of the top 100 IPs and the number of request each made in the period of interest.
|IP|Hits|
|-|-|
|107.178.200.196|1776|
|107.178.200.206|1769|
|107.178.200.203|1631|
|107.178.200.211|1617|
|107.178.200.202|1576|
|3.236.12.66|1537|
|107.178.200.233|1536|
|107.178.200.197|1488|
|107.178.200.217|1465|
|107.178.200.214|1451|
|107.178.200.237|1447|
|107.178.200.232|1446|
|107.178.200.228|1433|
|107.178.200.220|1421|
|107.178.200.216|1382|
|107.178.200.238|1359|
|107.178.200.199|1353|
|107.178.200.193|1352|
|107.178.200.201|1329|
|107.178.200.236|1288|
|107.178.200.200|1282|
|107.178.200.194|1246|
|107.178.200.231|1241|
|107.178.200.207|1225|
|107.178.200.219|1202|
|107.178.200.208|1201|
|107.178.200.224|1198|
|107.178.200.227|1188|
|107.178.200.218|1157|
|107.178.200.230|1143|
|107.178.200.212|1131|
|107.178.200.198|1118|
|107.178.232.252|1115|
|107.178.200.205|1108|
|107.178.236.14|1105|
|107.178.238.45|1076|
|107.178.200.210|1066|
|107.178.200.221|1062|
|107.178.200.226|1040|
|107.178.200.213|1038|
|107.178.200.229|1036|
|107.178.236.24|1034|
|35.203.245.183|1030|
|107.178.200.195|1027|
|107.178.239.216|1023|
|107.178.200.209|1006|
|35.203.245.118|1000|
|107.178.200.234|994|
|107.178.200.235|989|
|107.178.200.215|959|
|35.203.252.125|952|
|35.203.245.188|941|
|35.203.245.123|940|
|107.178.200.204|924|
|107.178.232.226|917|
|107.178.239.218|905|
|107.178.239.197|901|
|107.178.236.8|877|
|35.203.245.119|874|
|107.178.236.6|870|
|107.178.237.11|870|
|107.178.239.206|869|
|107.178.238.28|864|
|107.178.236.11|863|
|107.178.237.5|863|
|107.178.232.250|852|
|107.178.239.208|849|
|35.203.245.182|844|
|35.203.245.184|838|
|35.203.252.114|838|
|107.178.239.196|835|
|107.178.232.243|833|
|35.203.245.176|828|
|107.178.232.166|826|
|35.203.245.187|826|
|107.178.238.38|826|
|107.178.232.231|825|
|35.203.245.124|824|
|107.178.239.201|823|
|107.178.239.214|822|
|107.178.239.222|819|
|107.178.237.24|808|
|107.178.239.220|807|
|107.178.232.251|805|
|107.178.239.210|801|
|35.203.252.113|797|
|35.203.245.210|796|
|107.178.236.26|793|
|107.178.232.170|792|
|107.178.200.225|789|
|107.178.236.4|783|
|107.178.232.241|782|
|107.178.236.30|780|
|107.178.239.194|780|
|35.203.245.177|776|
|107.178.200.192|771|
|107.178.236.22|765|
|35.203.252.154|763|
|35.203.252.144|760|
|107.178.239.200|759|
|107.178.237.6|755|

The manifest request executed before all the errors were observed was the following: 
```
https://service.explore.data.humancellatlas.org/fetch/manifest/files?filters={"genusSpecies":{"is":["Homo sapiens"]},"projectTitle":{"is":["Single cell transcriptome analysis of human pancreas reveals transcriptional signatures of aging and somatic mutation patterns."]},"projectId":{"is":["cddab57b-6868-4be4-806f-395ed9dd635a"]},"fileFormat":{"is":["fastq.gz"]}}&format=terra.bdbag
```
Initial findings suggest that Elasticsearch was unable to keep-up and serve all the incoming request (potentially made by a Terra workflow), causing errors due to an overloaded system. 

In a post findings discussion the two following solutions were suggested:
* Switch request type in Elasticsearch from a 'search' method to a per 'document' method. ( Which might serve the request faster)
* Propagate the 429 status code response returned by the Elasticsearch client to the service response. ( Signaling the client to reduce/stop the request being made)

**Comment by achave11** [comment]
The following is the `participants.tsv.zip` obtain from the manifest request referenced above. 
[participants.tsv.zip](https://github.com/DataBiosphere/azul/files/4861897/participants.tsv.zip)

**Comment by hannes-ucsc** [comment]
Our DOS implementation makes an ES roundtrip to determine the checksums and the file name of the file. While I am not sure those two things were required by the legacy DOS standard, I don't want to change that aspect in fear of breaking existing clients.

The ES round-trip currently uses a query filter. This is necessary because the data file UUID is not the same as the entity ID, which is the UUID of the metadata file describing the data file. However, there no source filters are applied even though only certain response elements are actually used (checksums and file name). We may be able to accelerate the query further by setting size=1.

**Comment by theathorn** [comment]
Looks like we need to fix this in DCP/1 to enable secondary analysis processing in Terra.

**Comment by hannes-ucsc** [comment]
DRS/DOS proxy is deprecated. Clients use TDR's native DRS impl.
