### ISSUE TITLE
Filter parameter specification inconsistencies

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#1940]
The query parameter for `filters` is defined inconsistently within the API, the `index` endpoints have a more defined structure for creating filters, while the `manifest` endpoints appear to be more lax in its definition. 

per the API Spec page:
```
Azul provides the ability to download metadata in tabular form via the Manifests endpoints.
The resulting manifests include links to associated data files and can be used by the DCP CLI to download the listed files. 
Manifests can be generated for a selection of files using filters.
**These filters are interchangeable with the filters used by the Index endpoints**.
```

To ensure consistent parameter validation only one parameter specification should be used.

An extension to the solution would be using OpenAPI `$ref` feature; by defining one model for each parameter, then having the endpoint properties point to the applicable reference for the parameter.

https://swagger.io/docs/specification/using-ref/

**Comment by hannes-ucsc** [comment]
This is a problem, good catch.

I have to think about using `$ref`. So far we have avoided it and instead have been using Python variables and functions to deduplicate the spec. This is possible because we use Python literals to define the spec, rather than raw YAML or JSON.

The advantage of `$ref` is that it consumer of the resulting JSON spec can identify the deduplication. In our current approach the JSON spec would contain multiple identical copies of the same structure, forcing the user to compare the copies to see if they are really the same. The advantage of using Python to deduplicate is that each endpoint spec is self contained. The repeats of the `filters` spec section may also differ from each other in insignificant ways, in case the deduplicated spec section is parameterized.
