### ISSUE TITLE
Sporadic failures related to 'ConflictException' when running `make deploy` 

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1951]
The following error shows up at the end of the console output when running `make deploy` (in my case, in a new deployment). 
Note that this issue has been seen before and reference in #1775 in a [comment](https://github.com/databiosphere/azul/issues/1775#issuecomment-634895839) regarding an unrelated error not seen recently.

```output
Error: Error creating API Gateway Deployment: ConflictException: Another Deployment is in progress for rest api with id hfer3g8dil . Please try again later.

  on indexer/chalice.tf.json line 312, in resource.aws_api_gateway_deployment.rest_api:
 312:             }
```

Also note that simply running `make deploy` a second time solves the issue.

**Comment by hannes-ucsc** [comment]
I think this is caused by the fact that there is a stray `aws_api_gateway_deployment` in https://github.com/DataBiosphere/azul/blob/b1cf973a0bb98dd04aba3d4edf3afcb07f181591/terraform/api_gateway.tf.json.template.py#L94

It's amazing that it took us this long to notice.

**Comment by jessebrennan** [comment]
I tried to reproduce the original error by twice creating new deployments, but I was unable to. The first time I encountered a different error, which I have recorded but not yet reported (I wasn't able to reproduce this error either).

I did remove the stray `aws_api_gateway_deployment` that @hannes-ucsc mentions above, but I propose we make a separate ticket for that change since I'm unable to confirm the relationship Hannes suggested.

I'll bring this up in parking lot.
