### ISSUE TITLE
Perform Third Party Personnel Security for Clever Canary

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1980]

**Comment by nolunwa** [comment]
@theathorn @hannes-ucsc I have initiated the process of having an NDA with clever canary. we need to add a point of contract in UCSC that will be authorized to send documentation and information generally to the contractor. I recommend someone in the engineering team to be a point of contact someone that works closely with  Dave, thought?

**Comment by theathorn** [comment]
I will volunteer as I work most closely with Dave on SOWs, etc.

**Comment by nolunwa** [comment]
send Dave the initial draft of an NDA with UCSC disclosure of confidential information

**Comment by theathorn** [comment]
@nolunwa Is this complete (if so, close the ticket)?

**Comment by nolunwa** [comment]
Hello Trevor,

Yes, the ticket can be closed for Clever Canary.

Another ticket will be opened once we can have the managed access system
deployed and we have managed access data.

Thanks


*Nneka Olunwa*
*Sr Security Compliance Officer, MBA CISM*
*https://ucscgenomics.soe.ucsc.edu/ <https://ucscgenomics.soe.ucsc.edu/>*



This document contains information belonging to the Dockstore system and
HCA project which may be confidential and legally privileged. This
information is only for the use of the individual or entity to which it was
intended. Any disclosure, copying, distribution, or action taken in
reliance on the contents of the information contained in this document and
any accompanying documents is strictly prohibited unless otherwise
authorized by System administrators.
