### ISSUE TITLE
Extraneous `null` values in hits.protocols.* for /repository/files response

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2043]
Repro here:

https://github.com/HumanCellAtlas/data-browser/issues/1250#issuecomment-658325944

**Comment by hannes-ucsc** [comment]
The repro is on HCA prod but if it is an issue it likely affects `develop` as well.

@danielsotirhos, I'd can one of the bundles, add a test case and step through the indexer with a debugger to diagnose this. That's what the spike covers.

**Comment by NoopDog** [comment]
Hi @danielsotirhos I believe the extra null in the files is also being propagated up to the samples and projects.

**Comment by danielsotirhos** [comment]
In #1575 (Paging broken when sorting fields with Null values) a change was made to how protocols are indexed by Azul. Previously protocol inner entities were indexed with only the fields related to the type of protocol (e.g. `paired_end` if a `SequencingProtocol`, `workflow` if a `Analysis Protocol`).

Ticket #1575 changed this so that all protocol inner entities are indexed with all the possible protocol fields (set to a value of `None` if not specified). This was done to allow Elasticsearch to search and sort these fields.

Looking at a prod bundle given as an example [c95d7e0c](https://service.explore.data.humancellatlas.org/repository/bundles/c95d7e0c-84df-44d3-9c4d-8a869733fd3e) the `protocols.pairedEnd` field is listed as `false, null`. From the [bundle manifest](https://dss.data.humancellatlas.org/v1/bundles/c95d7e0c-84df-44d3-9c4d-8a869733fd3e?replica=aws&per_page=500) and [links.json](http://dss.data.humancellatlas.org/v1/files/01d36488-9d11-44ba-868d-7da46ee7bef6?replica=aws) we can see the last link in the graph is going from a cell suspension (e7af9648) to multiple sequence files using two protocols, a [library preparation protocol](http://dss.data.humancellatlas.org/v1/files/88bb0331-4a61-4268-b17b-2310fb47bcb8?replica=aws) with no `paired_end` field, and a [sequencing protocol](http://dss.data.humancellatlas.org/v1/files/0209526c-1969-4480-ab9a-ab108952dbd4?replica=aws) with a `paired_end` of `false`. This is why the bundle's `protocols.pairedEnd` value is `false, null`.

**Comment by danielsotirhos** [comment]
Seems to work as intended. Assigning ticket to @hannes-ucsc for review.

**Comment by hannes-ucsc** [comment]
@danielsotirhos's analysis is correct but the conclusion is not. This behaviour is broken, the extra null should not be there. The problem is that we inject null values when there really are no null values. In this case, the `hits.protocol` inner entity represents a mix of concrete protocol entities of different types, namely `analysis_protocol`, `sequencing_protocol`, `library_preparation_protocol` and `imaging_protocol`. They all completely disjunct sets of fields. The `paired_end` field is a property of only the `sequencing_protocol`. When the protocol is of a different type, we still inject a `paired_end` field with a value of `null`. This synthetic `null` then ends up indistinguishable with a organic null from a `sequencing_protocol` where the value is actually `null`.

I see two solutions: 

a) We introduce two types of `null` placeholders internally one for synthetic nulls and one for organic ones. We can then filter out the synthetic ones from the `termFacets` and `hits` part of the response. While this sounds easy enough, it would be an invasive change that touches many areas of the code.

b) We eliminate the need for synthetic nulls by eliminating polymorphic inner entities. There are two inner entities that are polymorphic: protocol and sample. This issue is about `protocol` but it affects samples in a similar way, just not as prominently for various reasons. To eliminate the protocols polymorphism, we would split `contents.protocols` into `contents.sequencing_protocols`, `contents.analysis_protocol`, `contents.library_preparation_protocol` and `contents.imaging_protocol`. On the service response side we could merge them again or leave them separate.

For samples, we could slim it down so it only contains fields that are present in every concrete sample type. This would also eliminate the need to inject synthetic nulls. Another idea is to separate `contents.samples` into `content.sample_specimens`, `contents.sample_celllines` and `contents.sample_organoids` and merged them very late when producing the response.

Before we solve problem this for samples (probably as part of another issue), I would like to first understand if DataBrowser is actually using `hits.samples` and the associated facets. I would like to arrange for a quick meeting with the DataBrowser team to ascertain what the best approach for that would be.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :" @danielsotirhos to create ticket about solving this for samples."

**Comment by hannes-ucsc** [comment]
Corresponding ticket for samples is #2071.
