### ISSUE TITLE
Inconsistent line numbers in flake8 output

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2087]
for a given file
```
import json
import logging
from more_itertools import (
    one,
)
import re
from typing import (
    Dict,
    List,
    Mapping,
)
import uuid

from chalice import (
    BadRequestError,
)

from azul.openapi import (
    schema,
)
from azul.strings import (
    pluralize,
)
from azul.types import (
    JSON,
)
from azul.uuids import (
    InvalidUUIDError,
    validate_uuid,
    InvalidUUIDVersionError,
)

```

flake8 output is

```
make pep8
flake8 --config .flake8/conf /Users/amar/dev/hca/azul/src 
...
/Users/amar/dev/hca/azul/src/azul/openapi/validation.py:6:1: AZUL111 import statements are not correctly ordered
/Users/amar/dev/hca/azul/src/azul/openapi/validation.py:12:1: F401 'uuid' imported but unused
/Users/amar/dev/hca/azul/src/azul/openapi/validation.py:27:1: AZUL112 symbols in from import are not correctly ordered
```

the first error, 
`/Users/amar/dev/hca/azul/src/azul/openapi/validation.py:6:1: AZUL111 import statements are not correctly ordered`
indicates that there is an issue with the line `import re`; however the issue here is with the previous import of `one` from `more_itertools`, it should be placed after the closing parentheses for the import of `BadReqestError` because its an external module. 

`validate_uuid` is showing an error line.26 (acceptable in my opinion because it narrows down the block of code to look at)

This behavior can also be seen as acceptable because `import re` an internal module should not occur after an external module.

**Comment by amarjandu** [comment]
One solution might be to provide a more specific error code about importing external modules after an internal or visa-vesa. Ideally the error codes would be different so its easier to see why the issue is occurring.

**Comment by hannes-ucsc** [comment]
A solution for this would be hard to implement. The current implementation objects about the first violation in source order, and the `re` import is that. Reading the file in source order, the `itertools` import starts the external dependency section and the `re` import doesn't fit into that section. The plugin would have to do some elaborate optimization in order to figure out the *minimal* set of violations is and I don't think that complexity is worth the usability improvement. As @noah-aviel-dove pointed out during stand-up, the universal fix to any import ordering violation is use PyCharm to format the file and optimize the imports. We carefully selected the ordering criteria the plugin enforces so we would be able to do that.
