### ISSUE TITLE
Retries of `contribute` lambda invocations may drop tallies

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2163]
Port #2159 to hca/develop.

**Comment by amarjandu** [comment]
For the record, it was observed that the `hca/develop` branch does not have the same issues that the `develop` within the `contribute` method in the `indexer_service`. This is due to the `tallies` object being instantiated outside of the loop that performs the writing of the contributions to the ES instance.

Compared to `hca/develop` which used to instantiate the tallies after the writing had been performed. https://github.com/DataBiosphere/azul/commit/0fd3b3e35e0c28b719b781db3f5a44db37102b85
