### ISSUE TITLE
Design MVP mechanism for user-contributed matrices

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2175]

**Comment by theathorn** [comment]
See https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/108.

**Comment by mshadbolt** [comment]
I also posted it on slack but we have uploaded all the contributor matrices that we have received to the google storage bucket and have a list of files in this ~~csv~~ xls (because apparently github doesn't like csvs: 
[20200903-contributor_matrices_dcp2_mvp - final_file_list.xlsx](https://github.com/DataBiosphere/azul/files/5175876/20200903-contributor_matrices_dcp2_mvp.-.final_file_list.xlsx)

**Comment by hannes-ucsc** [comment]
@mshadbolt how does that Excel sheet relate to https://docs.google.com/spreadsheets/d/1Te1FTUbdn-tFS3eLVTB7uMEApoFU0Il6krSoiq_LAAw/edit?ts=5f3d641f#gid=0 Can I use either?

**Comment by hannes-ucsc** [comment]
Spec proposal here: https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.aohbnknu370j

Implementation notes for Azul:

We will stage CGM (contributor-generated matrix) files in a separate staging area, one subgraph per project. We will not stage project metadata (`project.json`), only `supplementary_file.json` and `links.json`. The indexer code may currently require that each bundle contains `project.json` but that requirement will have to be relaxed since the CGM bundles won't contain `project.json`. The indexer must detect CGM files by checking `provenance.submitter_id` of `supplementary_file` entities and handle them by creating a project contribution with a `contributor_matrices` inner entity for each CGM file. The structure of that inner entity should resemble the `/index/projects` response mentioned in the spec except that the leafs are DRS paths.

The same person should stage the CGM files AND implement the indexer changes.

**Comment by mshadbolt** [comment]
@hannes-ucsc that file is a snapshot of the 'final_file_list' tab of the google sheet you linked to. I thought it may be cleaner since there are multiple tabs and things I was doing to check files but you could use either the csv or that particular tab of the sheet.

**Comment by hannes-ucsc** [comment]
Thank you, @mshadbolt.

**Comment by hannes-ucsc** [comment]
We'll close this when the spec change is ratified.

**Comment by hannes-ucsc** [comment]
Ratified.

https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit?ts=5f6a418a#heading=h.aohbnknu370j
