### ISSUE TITLE
`make requirements_update` may use stale docker image layer

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2261]
The outdated docker image may not contain the latest requirements.

This caused a [Gitlab build to fail for #2077](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5675). A [Gitlab build ran and failed prior](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5624) because transitive dependencies were out of date. A transitive dependency, `cfn-lint`, was then updated. I updated the transitive dependencies, but the new build failed because the docker container on Gitlab used a docker cache from the previous build and therefore didn't catch the update to `cfn-lint`.

The reason the cache was used when it should not have been was because `requirements.*.trans.txt` files are cleared at the beginning of `make requirements_update` and therefore changes within them won't invalidate the docker cache.

**Comment by jessebrennan** [comment]
The spike label represents the work I've already done investigating the ticket. Possibly more will need to be done to determine a solution.

**Comment by jessebrennan** [comment]
A couple solution ideas:
- Empty the `requirements.*.trans.txt` files after the files are copied inside of docker container.
- Remove the "import" call to `requirements.*trans.txt` from inside of `requirements.txt` and `requirements.dev.txt` before building the requirements, then add it again after.

**Comment by natanlao** [comment]
I can reproduce this issue on 21aa288b0a4029a528cf078e80e9c7a408d7288b.

* Run `make requirements_update`. Each requirements.*.txt file is cached (including the transitive dependency files, as [modified in the Makefile](https://github.com/DataBiosphere/azul/blob/21aa288b0a4029a528cf078e80e9c7a408d7288b/Makefile#L63))
* Then, say that after `make requirements_update` is run, a new version of a transitive dependency is released. No direct dependencies are affected.

The expected behavior at this point is that running `make requirements_update` will notice the updated version of the transitive dependency and update each requirements.*.trans.txt file accordingly. Instead, because the transitive dependency files are cached, `make requirements_update` exits without updating any requirements files.

The fix in #2263 does not prevent a stale image layer from being used.

**Comment by hannes-ucsc** [comment]
The orginal repro was slightly different in that it showed that a change to a .trans.txt file didn't trigger image cache invalidation. In this case, the only thing being different is that a newer version of a dependency was released between invocations of `make requirements_update` on the developer's machine. That's the intended behaviour. We do not want updates to transitive deps to fail `make requirements_update check_clean` unless any of the dependency files or Makefile or Dockerfile (image inputs) were touched: on one machine, repeated builds with the same image inputs should lead to the same dependencies being used or the build should fail.

There are two problems: 1) `make requirements_update check_clean` can still fail on one machine even after it succeeded on another  machine (which is still better than silently using updated transient deps) and 2) `make requirements_update` may not produce the same changes to the transitive files between machines. The latter is what led to the reopening of this ticket. I want to address them as a separate ticket, though.

**Comment by hannes-ucsc** [comment]
See #2344 and #2345.
