### ISSUE TITLE
Remove "@eventually" from test

### ISSUE THREAD

**Issue by alex-hancock** [DataBiosphere/azul#233]
Addressing #207 introduced the refresh "wait for" parameter in the indexing functions. This addition deprecates the need for the `eventually` decorator.

I've created this issue so we can observe the changes that the refresh addition makes and reverse it if we don't like them.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-162)
┆Project Name: azul
┆Issue Number: AZUL-162

**Comment by hannes-ucsc** [comment]
I think the way forward is to make this configurable. Will create ticket.

**Comment by hannes-ucsc** [comment]
#284

**Comment by hannes-ucsc** [comment]
We use `refresh=False` in actual deployments now for performance reasons but the indexer tests do configure the indexer instance to use `refresh="wait_for"` for all updates. This should eliminate the need for `@eventually`. Remove the uses of `@eventually`. Since `@eventually` is a function decorator, the assertions had to be placed into a separate function. [Inline](https://refactoring.com/catalog/inlineMethod.html) those functions.
