### ISSUE TITLE
`make requirements_update` yields inconsistent diffs to `requirements*.trans` between machines

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2345]
`make requirements_update` may not produce the same changes to the transitive files between machines if the image layer caches reflect different states on pypy. This led to the [reopening](https://github.com/databiosphere/azul/issues/2261#issuecomment-707278386) of #2261.

To repro run `make requirements_update` on machine A. Run `git diff > a1`. Wait a week. Run it on machine B. Run `git diff > b` on B. Then run it again on machine A. `git diff > a2`. The second run on A will reuse the cached layers from the first run on that machine. So a2 == a1 but `b != a2`. Ideally, `b == a2`.

**Comment by hannes-ucsc** [comment]
The solution is to add the ability to run `make requirements_update` without image layer caching enabled.

**Comment by natanlao** [comment]
Selectively disabling cache for a single layer [isn't supported directly in Docker](https://github.com/moby/moby/issues/1996) but we can get close by:

1. Adding a build argument (say `ARG INVALIDATE_CACHE`) directly before the last command in the Dockerfile.
2. Modifying the Makefile to pass a default value to `docker build` for that build argument, unless an environment variable is set.

Requirements could then be regenerated without the problematic cache layer like so:

```console
$ INVALIDATE_CACHE=$(date +%s) make requirements_update
```

`$(date +%s)` being seconds since epoch so that a new, uncached value for INVALIDATE_CACHE is "always" provided to `docker run`.
