### ISSUE TITLE
Update stale Kibana image in `scripts/kibana_proxy.py`

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2366]
The image specified for kibana-oss: `docker.elastic.co/kibana/kibana-oss:6.8.0` appears to have been removed from the container registry. https://www.docker.elastic.co/r/kibana/kibana-oss
This causes issues when trying to locate the images to pull down to a local machine.

**Comment by amarjandu** [comment]
It appears that the kibana image is available from the [docker hub repository](https://hub.docker.com/layers/kibana/library/kibana/6.8.0/images/sha256-290cd245e9088917d578a85574e5bfbffa3d95623c911dbc4d28383b3836d8d8?context=explore)  

Note that the name for the image is `kibana` and not `kibana-oss` not sure if this is just a naming convention.

**Comment by natanlao** [comment]
The `kibana` image does not work as an in-place replacement for `kibana-oss` (which I didn't expect because it looks like [`kibana-oss` is a subset of `kibana`](https://www.elastic.co/guide/en/kibana/6.0/docker.html#image-type)?)

I can't find any schedule that outlines when kibana-oss images are removed, but it looks like the entire 6.8.x line will be [EOL'd starting November 20, 2020](https://www.elastic.co/support/eol)

**Comment by natanlao** [comment]
`docker.elastic.co/kibana/kibana-oss:6.8.0` is back up as of time of writing (14:29 PT, 26 Oct 2020). See live here https://www.docker.elastic.co/r/kibana/kibana-oss:6.8.0 ([archive](https://web.archive.org/web/20201026213013/https://www.docker.elastic.co/r/kibana/kibana-oss:6.8.0)). Everything seems to work fine now...

**Comment by hannes-ucsc** [comment]
OK, in that case we'll close this and zero out the estimate.

Long term, https://github.com/DataBiosphere/azul/issues/2372 should reduce our dependency on external images.
