### ISSUE TITLE
Disable re-indexing of DCP/1 catalog

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2427]
Reasons:
  - it takes 6 additional hours to index
  - the data in DSS is unlikely to change between now and the end of 2020, when it will be deleted by CZI

**Comment by hannes-ucsc** [comment]
Unfortunately, this can't be done. I didn't fully think this through. Since were constantly updating indexer and service code to match, if we want to offer a catalog in the service, we need to keep reindexing in whenever the code changes. If we don't new service code will hit an out of date index and the request will fail, rendering the catalog unusable, which means we might as well delete it. I'll need to back this change out.
