### ISSUE TITLE
Velocity report requires write access to GitLab

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2458]
We can't have secrets in the Github project settings that grant write access to Gitlab. I think the security controls we're going to implement will also prohibit us from using Github identities to authenticate against Gitlab, but that's a different ticket.

**Comment by melainalegaspi** [comment]
Spike to figure out where to put velocity report. Should not be public and cannot be on GitLab. Possibly look into putting in Confluence.

**Comment by natanlao** [comment]
Potential approaches, all of which expose an API that can be used to upload reports, and are already used by the team:
* Confluence.
* A wiki on a private GitHub repository in the DataBiosphere or ucsc-cgp organization. The first iteration of the velocity reporting script used this method.

**Comment by natanlao** [comment]
From standup: proceed with private GitHub wiki.

**Comment by natanlao** [comment]
I created https://github.com/ucsc-cgp/boardwalk-velocity-reports but I learned that the wiki feature can only be used if the repository is public, or if the organization's GitHub plan is upgraded. Should I:

* Seek an upgrade to ucsc-cgp's plan, or find a paid account ($4/user/month)
* Instead of storing reports in the repository's wiki, store reports in the repository itself. Reports can be stored as markdown files, can be rendered as rich text in the browser, and are lexicographically sortable.
* Upload reports to Confluence instead.

**Comment by natanlao** [comment]
Hannes says to proceed with option 2, store reports in repository itself

**Comment by theathorn** [comment]
Triage to see who will demo..

**Comment by theathorn** [comment]
@hannes-ucsc "Abraham will own this script and demo this ticket"
