### ISSUE TITLE
Copy DCP/1 project-level matrices to a GCP staging bucket and add metadata for import into TDR

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2483]
@NoopDog and @MillenniumFalconMechanic would prefer to access DCP/1 project matrices in DCP/2 Prod via the same API used for DCP/2 generated matrices and CGMs.

There are non-stratified DCP/1 matrices in 3 formats: loom, mtx and csv.
TBD: support all 3 matrix types or just loom?
@NoopDog : "I think we do not need a different level of stratification. We will just list all files tagged with the existing stratification values".

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Even though these matrices come in through the CGM adapter, the Azul service should expose them under hits.project.matrices. "

**Comment by danielsotirhos** [comment]
- Completed copy of all `s3://project-assets.data.humancellatlas.org/project-assets/project-matrices` files to the staging area `gs://broad-dsp-monster-hca-prod-ucsc-storage/cgm_dcp1`.
- [This spreadsheet](https://docs.google.com/spreadsheets/d/1KhxARyjssHrdg2l2F_UuSvhZuU4b2qsbC9VDF6vWHZc/edit?usp=sharing) was used with the CGM Adapter to stage the files and generate the required `links`, `supplementary_file`, and `file_descriptor` JSON files.
- Values taken from project listings on `data.humancellatlas.org` were used to populate the stratification values of `genusSpecies`, `organ` and `libraryConstructionApproach` for each file.
- The `submitter_id` value of all `supplementary_file` is set to `c9efbb15-c50c-5796-8d15-35e9e1219dc5` generated from the name `dcp1 matrix service`. This will be used by Azul to identify these matrices as DCP1-generated and use them to populate the `hits[].projects[].matrices` response (instead of `hits[].projects[].contributorMatrices`)
