### ISSUE TITLE
Allow CGM stratification dimension 'libraryConstructionMethod'

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2696]
Currently the allowed CGM stratification dimensions are: 'genusSpecies', 'developmentStage', 'organ', 'libraryConstructionApproach'. If a dimension outside this set is used a ValueError will be raised by `make_stratification_tree()`.

In the current schema `library_construction_approach` has been deprecated for `library_construction_method`.

Modify Azul's parsing of the stratification information so that `libraryConstructionMethod` or `libraryConstructionApproach` can be accepted.

**Comment by danielsotirhos** [comment]
Closing as won't fix.

**Comment by hannes-ucsc** [comment]
The reasoning for the closing of this issue being that we we want to be 100% consistent with one property naming convention, either Azul's response naming scheme (which is camel case and uses "approach") or the metadata schema (which is snake case and uses "method"). Consistency with Azul is easier to achieve (we just need to change the spec such that it is consistent with the example in that same spec. The current implementation is consistent with the example in the spec, not the spec itself. The downside of this is that the dimension names referred to in metadata files use a naming convention that is inconsistent with the convention used by the schema of the metadata files and instead uses the Azul convention. This is acceptable because this way of describing CGMs was for MVP only and will go away soon. Even CGMs should be described organically using a metadata graph, in which case the stratification of the matrix is evident from the graph itself.
