### ISSUE TITLE
Suggestion: Version the document structure to help reindexer avoid reindexing docs with the same structure

### ISSUE THREAD

**Issue by shiroyuki** [DataBiosphere/azul#271]
In order to ensure that every reindexing yields the same result, we could version the structure of the document for every changes to the structure. For example:

```javascript
{
  _version: SEMANTIC_VERSION // Example: 1.0.12; See https://semver.org/ for more info
  ... // omitted content
}
```

With this, the reindexer can avoid by checking the version of the document. One example would be that the reindexer may randomly pick one document and just check the version of the document before deciding whether the reindexer should proceed with reindexing or abort the operation.

**Pros:**
* Inexpensive way of comparing the structure of two random documents.
* The other services may leverage the version to better handle data.

**Cons:**
* The active version number must be known at least to both indexer and reindexer.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-179)
┆Project Name: azul
┆Issue Number: AZUL-179

**Comment by hannes-ucsc** [comment]
Semantic versioning is used when humans decide what severity/impact certain changes to an artifact have. This has no place here for a linear stream of updates made by a machine.

Comparing two in-memory data structures is orders of magnitude faster than a round-trip to Elasticsearch. WIth that in mind, it makes no sense to optimize that comparison. Will create ticket for implementing that instead of what's being proposed here.

**Comment by hannes-ucsc** [comment]
See #285
