### ISSUE TITLE
Collect BQ queries and stats to aid TDR team in diagnosing high cost

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2736]

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Need digest of log messages, classifying query shapes and their cost."

**Comment by noah-aviel-dove** [comment]
Reindexed `hca_dev_20201203___20201210`

- 1,818,824 total queries
- All non-cached queries billed at tier 1
- 720,509 cache misses (39.6%). All further stats are for non-cached queries only.
- 136,833,357,840,384 total bytes billed (136 TB [@ $5.00/TB = $680])
- 4 query shapes:

1. Listing bundles:
 - 256 queries (0.035%)
 - 17.2 GB billed (0.012%)
 - 67.2 MB/query
 - Example:
 ```
 SELECT links_id, version
 FROM broad-jade-dev-data.hca_dev_20201203___20201210.links
 WHERE STARTS_WITH(links_id, '10')
 ```
2. Retrieving links:
 - 165,103 queries (22.9%)
 - 29.9 TB billed (21.85%)
 - 181.1 MB/query
 - Example:
```
SELECT 
JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type, 
content, 
links_id, 
version, 
BYTE_LENGTH(content) AS content_size,
project_id
FROM broad-jade-dev-data.hca_dev_20201203___20201210.links
WHERE links_id = '0bf9a721-1ba1-4115-9ff7-d9c49e3251cc'
AND version = TIMESTAMP('2019-08-01T20:01:47.956664Z')
 ```
 
3. Retrieving other entities:
 - 555,150 queries (77.05%)
 - 106.9 TB billed (78.12%)
 - 192.0 MB/query
 - All cached queries should be of this shape
 - Example:  
```
SELECT 
version, 
process_id, 
JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type,
BYTE_LENGTH(content) AS content_size, 
content
FROM broad-jadeFROM broad-jade-dev-data.hca_dev_20201203___20201210.process
WHERE process_id = "71f00652-caf5-44e6-95cb-6e90f4d5dd62"
OR process_id = "146d53e9-b669-444b-ad39-a5e9fdfc7102"
OR process_id = "bbc52978-94cd-4a69-af6d-949c8ced8959"
```
The majority of these queries are for only a few entity types:

entity_type | query% | bytes billed%
sequence_file | 29.7 | 55.9
process | 29.7 | 22.3
cell_suspension | 28.6 | 18.2
specimen_from_organism | 6.4 | 1.8
others | 5.6 | 1.6

4. Finding dangling inputs for subgraph stitching:
- 9 queries (0.001%)
- 2.63 GB billed (0.002%)
- 292 MB/query
- Example: 
```
SELECT 
links_id, 
version, 
JSON_EXTRACT_SCALAR(link_output, "$.output_id") AS output_id
FROM broad-jade-dev-data.hca_dev_20201203___20201210.links AS links
JOIN UNNEST(JSON_EXTRACT_ARRAY(links.content, '$.links')) AS content_links 
ON JSON_EXTRACT_SCALAR(content_links, '$.link_type') = 'process_link'
JOIN UNNEST(JSON_EXTRACT_ARRAY(content_links, '$.outputs')) AS link_output
ON JSON_EXTRACT_SCALAR(link_output, "$.output_id") IN UNNEST(['1c277796-0d41-4129-a88f-10f2f39e8d81', '8e9c972d-6e4e-44eb-976c-9f59d3667dd6'])
```

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc Any changes to request regarding content or presentation of the above comment?

**Comment by hannes-ucsc** [comment]
No, this is great. Thank you!

**Comment by hannes-ucsc** [comment]
Since Noah compiled this, the nature of the queries hasn't changed. The fourth type of query is increasing in frequency, it occurs once per analysis subgraph and we are continually accruing more of those.

**Comment by hannes-ucsc** [comment]
We should focus on types 2 and 3 since they use the pseudo PK on the target table and don't use joins. I'm assuming that clustering/partitioning on the PK columns will make them considerably faster and cheaper. I'm also assuming that that wouldn't actually require and BQ schema changes. That's the assumption we should verify.

**Comment by hannes-ucsc** [comment]
The performance of the fourth query might benefit from extracting the output IDs in each subgraph into a separate join table that connects `links` table rows with entity table rows. If we do that we might also want to create a similar join table for inputs. Or one big join table where each row expresses the tuple `(links_id, process_id, input_type, input_id, output_type, output_id)`. Interestingly, adding a join table isn't modifying any existing tables. Having this table would make it a lot easier to write queries for user's of TDR in general, not just Azul. Interestingly, adding a join table doesn't require modifying any existing tables. IOW, neither this optimization nor the clustering/partitioning above would require a BQ schema migration.

**Comment by aherbst-broad** [comment]
Hi all, here are some findings as mentioned during yesterday's sync up:

1. Clustering is not an option with TDR at this time

2. Partitioning: There is a quota on the number of partitions per table in BQ (4000). Partitioning would not be a good fit for our data model regardless, as we have no natural partitioning key (outside of version, which we already partition on). In the two highest cost query examples ( (2) retrieving links + (3) retrieving other entities), we are pulling individual links and entities out of the table in a random-access use case. A better fit may be clustering as the cardinality is much higher, but this feature is not available in TDR as mentioned.
One potential option: the links table is 165k rows, and 296MB in size (as of 8/26/2021). Given the relatively small size, it might be doable to load the table into memory and perform random access queries that way. 
I ran a script that pulled down all links rows, parsed the contents field from JSON and instantiated a dataclass object representing the projection from query (2). The stats were: 1.76 GB memory consumed, 17s CPU on a 2019 MBP w/16GB RAM 2.4 GHz 8-Core Intel Core i9. Alternatively, exporting the TDR data to a vanilla SQL database like postgres might be an option as well.

3. Creating the join table from Hannes’ last comment should not be a heavy lift, but will likely not increase performance, as there will still be a random access use case for links + entities. 

@hannes-ucsc I suspect implementing the join table as mentioned above (in a new schema + dataset for testing) would take us ~1 sprint ; do you feel that's worth pursuing or should we shelve that for now and press on with the prod migration with the schema as-is?

**Comment by hannes-ucsc** [comment]
I agree that adding the join table is not going to reduce the cost or performance incurred by the Azul indexer. It would only make it easier to write queries for diagnostic purposes, collect evidence or to perform ad-hoc research against the metadata, both by us internally and by external power users. I don't think we should prioritize it now.

Reading the entire `links` table into memory would accelerate query type 2 but that makes up only 20% of the cost. To eliminate the remaining 80% would require reading all entity tables into memory as well. Azul's serverless design is pretty scalable but doesn't lend itself very well to big in-memory caches. It uses AWS Lambda which attempts to keep processes running so that tasks can reuse global state initialized by previous tasks, but that is a best effort only. If we cache the BQ database in memory, we risk having to prime the cache for every task where that best effort fails. I don't think that's feasible.

The only remaining option is pulling the BQ tables into an equivalent ES index as a first pass before indexing. It's that or clustering. Before we decide let me ask this: Is "Clustering is not an option with TDR at this time" a euphemism for it never going to be being implemented?

**Comment by hannes-ucsc** [comment]
Let me ask a different question: Are there plans to implement clustering in TDR in the next 6 months?

**Comment by aherbst-broad** [comment]
@hannes-ucsc no, there are not plans to implement clustering in the next 6 months.
