### ISSUE TITLE
Bug with `specimens/summary` and `files/summary` not matching aggregates.

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#276]
Query to `files_index`
```JSON
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 14056,
    "max_score": 1
},
  "aggregations": {
    "total_specimens": {
      "value": 183
    },
    "total_files": {
      "value": 14278
    }
  }
}
```

Query to `specimens_index`
```JSON
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 184,
    "max_score": 1
},
  "aggregations": {
    "total_specimens": {
      "value": 183
    },
    "total_files": {
      "value": 14278
    }
  }
}
```

Note that the `aggregations` do not match to the total number of `hits`. Ideally this numbers should be matching across the board.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-182)
┆Project Name: azul
┆Issue Number: AZUL-182

**Comment by hannes-ucsc** [comment]
@achave11  and I spent some time looking into the root cause for why the specimens and files summaries are `permanently` inconsistent. The fix is essentially to only use primary keys to aggregate over when producing entity counts. For example, the specimen count is currently driven by a field called `biomaterial_id` which is supposed to the a unique identifier for specimens, but in fact, we indexed bundles that contain distinct (based on `document_id`) specimens with the same `biomaterial_id`. The fix for the specimen count is to count distinct `document_id` values, not distinct `biomaterial_id` values. There is a similar problem for projects which currently aggregates over `project_short_name`.

Once we fix those issues, the files and specimens summaries will be eventually consistent. They can still be temporarily inconsistent due concurrent indexing processes. We would like to maintain two separate summary endpoints so we have a way of telling whether the entity-specific indices are inconsistent.

@NoopDog proposed a different solution, which was to have one summary endpoint that hits all indices in separate queries and cherry picks the authoritative index for a particular the summary element. I prefer this solution because it is more efficient and exposes permanently inconsistent indices.

@NoopDog, this means that you should use `/summary/specimens` together with `/specimens` on the Specimens tab and `/summary/files` together with `/files` on the Files tab.

**Comment by achave11** [comment]
After spending more time analyzing the implications of the fix described by @hannes-ucsc above, we realize the complexity of obtaining specific index related fields from the other indexes. That is to say that we support two different indexes with the same structure, but different data models. This brings about redundancies in the response of the server, do to the unfolding of the data in the different indexes. We obtain inaccurate information when querying specimens about file related fields, like file sizes, and similarly when querying the files index about total cell count in specimens. 

We will resume the first proposed approach of making a request to each index (specimens, files) in order to populate a single summary response with the most accurate fields from each response.
