### ISSUE TITLE
Endpoint `/repository/files/export` ignores file format facet

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#299]
When we get the manifest for a link like below (which should only return PDF files) we are seeing all files in the downloaded manifest instead.

https://service.dev.explore.data.humancellatlas.org/repository/files/export?filters=%7B%22file%22:%7B%22fileFormat%22:%7B%22is%22:%5B%22pdf%22%5D%7D%7D%7D&format=tarball

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-199)
┆Project Name: azul
┆Issue Number: AZUL-199

**Comment by NoopDog** [comment]
@theathorn I have marked this as critical to try to get it bumped in priority. Is this possible to add the current sprint. We will need the export to observe the file types for the matrix service implementation as well as general usage.

**Comment by theathorn** [comment]
Ben, this is a manifest-related issue that we think you can fix quickly.

**Comment by Ben-Wu** [comment]
@NoopDog Can you verify that this is still an issue?  The manifest I get in that link has only pdfs and seems to have the correct number.  I tested with other file types as well and it seems to be working as expected.  I'm trying to look for what has changed recently that may have fixed this.

**Comment by Ben-Wu** [comment]
The original link seems to be no longer working since the manifest too large.

This is a smaller manifest with only fastq.gz:
https://service.dev.explore.data.humancellatlas.org/repository/files/export?filters=%7B%22file%22:%7B%22organismAge%22:%7B%22is%22:%5B%2221%22%5D%7D,%22fileFormat%22:%7B%22is%22:%5B%22fastq.gz%22%5D%7D%7D%7D&format=tarball

And this is the manifest with only pdf filtering on the same facets:
https://service.dev.explore.data.humancellatlas.org/repository/files/export?filters=%7B%22file%22:%7B%22organismAge%22:%7B%22is%22:%5B%2221%22%5D%7D,%22fileFormat%22:%7B%22is%22:%5B%22pdf%22%5D%7D%7D%7D&format=tarball

**Comment by NoopDog** [comment]
This looks ok to me on dev. This can be closed.
