### ISSUE TITLE
Partially empty rows in Terra handover for CrohnsTherapyResistance project

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2996]
Use this [search](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22libraryConstructionApproach%22,%22terms%22:%5B%2210x%203%27%20v2%22,%2210X%203%27%20v2%20sequencing%22,%2210x%203%27%20v3%20sequencing%22,%2210X%203%27%20v3%20sequencing%22,%2210X%20v2%20sequencing%22,%2210x%20v3%20sequencing%22%5D%7D,%7B%22facetName%22:%22workflow%22,%22terms%22:%5B%22Unspecified%22%5D%7D,%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Homo%20sapiens%22%5D%7D,%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%22992aad5e-7fab-46d9-a47d-df715e8cfd24%22%5D%7D,%7B%22facetName%22:%22nucleicAcidSource%22,%22terms%22:%5B%22single%20cell%22%5D%7D,%7B%22facetName%22:%22specimenOrgan%22,%22terms%22:%5B%22blood%22%5D%7D,%7B%22facetName%22:%22fileFormat%22,%22terms%22:%5B%22fastq.gz%22%5D%7D%5D) and then export to Terra.

The exported data table has 8 rows, but row 5 has no data except "participant_id":
![Screenshot 2021-04-20 101339.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/b0cdbcd7-e75c-4020-84f5-e6dadb813822)

**Comment by hannes-ucsc** [comment]
The participant_id is actually a subgraph (fka bundle) ID. The column name is a legacy Terra requirement.

The subgraph in question is `2a3b2a27-1e7d-4884-8905-be5daa768f1f`.

This is the BDBag Azul generated for this handover:

[481b7ad6-9aa0-5c13-b4aa-1d466577d66e.zip](https://github.com/DataBiosphere/azul/files/6346191/481b7ad6-9aa0-5c13-b4aa-1d466577d66e.zip)

This is the `participants.tsv` from that BDBag:

[participants.tsv.gz](https://github.com/DataBiosphere/azul/files/6346206/participants.tsv.gz)

This is that same file in Google Sheets

https://docs.google.com/spreadsheets/d/1Z5EsyjvWHK3pJLjiX4b2PTe40XabHN2XlKLxIchH33U/edit?usp=sharing

I've highlighted the row in question. **It is not empty, only some columns are empty. For other files other columns are empty.**

This is a weird project. Most subgraphs in that project have at least one fastq labelled `read1`, at least one labelled `read2` and at least one labelled `index1`. Subgraph `2a3b2a27-1e7d-4884-8905-be5daa768f1f` doesn't have any files labelled `index1`. That's why all of the `index1` columns in the table are empty. It does have two files labelled `read1` and `read2` and those columns are not empty.

There is nothing to fix in Azul. The contents of the hand-over is as expected for the irregular grouping of files. We need to escalate this to Ingest or the wranglers.

**Comment by hannes-ucsc** [comment]
Issue moved to [DataBiosphere/dcp2 #1](https://github.com/DataBiosphere/dcp2/issues/1) via [**ZenHub**](https://www.zenhub.com/)

**Comment by hannes-ucsc** [comment]
Still can't transfer issues across orgs. Dangit, Github and Zenhub.

**Comment by mshadbolt** [comment]
The wrangler for this project, @ami-day is away this week so I did a quick check of SRA for those run ids that have only a R1 and R2 and no index1 and it seems like that is what is what is available in SRA for this project:

Run IDs in question
```
SRR12565248
SRR12565249
SRR12565250
```
example from SRA: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12565248
if you go to the `Data access` tab there is only R1 and R2 available, whereas others in this project also have an index read available, e.g. https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12565255

So I don't think this is a wrangling issue. I am not sure why this sub-graph/experiment in particular does not have index files. Though I thought that analysis could still be run without the index files. Does the lack of index1 files for this subgraph prevent it being analysed?

**Comment by melainalegaspi** [comment]
@hannes-ucsc to follow-up with Farzaneh.

**Comment by hannes-ucsc** [comment]
Did that.

**Comment by khajoue2** [comment]
> The wrangler for this project, @ami-day is away this week so I did a quick check of SRA for those run ids that have only a R1 and R2 and no index1 and it seems like that is what is what is available in SRA for this project:
> 
> Run IDs in question
> 
> ```
> SRR12565248
> SRR12565249
> SRR12565250
> ```
> 
> example from SRA: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12565248
> if you go to the `Data access` tab there is only R1 and R2 available, whereas others in this project also have an index read available, e.g. https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12565255
> 
> So I don't think this is a wrangling issue. I am not sure why this sub-graph/experiment in particular does not have index files. Though I thought that analysis could still be run without the index files. Does the lack of index1 files for this subgraph prevent it being analysed?
> 
> EDIT: Just saw subsequent conversation on slack and this project does have other issues with it which will prevent analysis until those are fixed (linking issues).
Indecx file is optional for the analysis but we use them by default if the data table provides them. We can change that for this project.

**Comment by hannes-ucsc** [comment]
I think I'm just gonna close this one since Azul is behaving as expected. There may or may not be an issue with how the project is structured but I don't want to track that as an Azul issue.
