### ISSUE TITLE
Delete old CloudTrail bucket in dev and setup new one

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3004]
See #2983

**Comment by theathorn** [comment]
Spike to determine if we need an S3 bucket for CloudTrail.

**Comment by achave11** [comment]
AWS CloudTrail **does require** an S3 bucket for its _trail log location_. A new one can be created or an existing one can be used.

**Comment by achave11** [comment]
S3 bucket `platform-ha-cloud-trail` currently in us-west-2 region.
Bucket Versioning: Disabled
Multi-factor authentication (MFA) delete: Disabled
Tags: Owner | weiler@soe.ucsc.edu
Default encryption: Disabled
Server access logging: Disabled
Transfer acceleration: Disabled
Object Lock: Disabled
Requester pays: Disabled
Static website hosting: Disabled

What should the name of the bucket be and which tag attributes should it contain?
Planning to use the same config described above, should anything change for the new bucket?

**Comment by hannes-ucsc** [comment]
Bucket name must be `edu-ucsc-gi-platform-hca-dev-cloudtrail`. The `owner` tag (not `Owner`) must be `hannes@ucsc.edu`. Access must be `Bucket and objects not public`. All other settings should be left at their default.

**Comment by achave11** [comment]
Bucket name `platform-ha-cloud-trail ` has been deleted.

**Comment by achave11** [comment]
CloudTrail `Default` trail logs location has been updated to use `edu-ucsc-gi-platform-hca-dev-cloudtrail ` S3 bucket.

<img width="1341" alt="Screen Shot 2021-05-12 at 2 25 56 PM" src="https://user-images.githubusercontent.com/19215510/118046657-794eb180-b32e-11eb-931a-587c55d9f1ec.png">



Since `platform-ha-cloud-trail` has been deleted, it's no longer searchable in S3 AWS Console.

<img width="1629" alt="Screen Shot 2021-05-12 at 2 25 10 PM" src="https://user-images.githubusercontent.com/19215510/118046959-ee21eb80-b32e-11eb-9777-4cd15350ac56.png">

**Comment by hannes-ucsc** [comment]
LGTM. Screenshots serve as demo.
