### ISSUE TITLE
"sequencing_process.provenance.document_id"  column is missing from the "full" manifest

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#3066]
#### Need

The sequencing_process.provenance.document_id field is used to link the cells in the DCP-generated matrices to the sequencing process that created them and the associated items higher in the graph, e.g., sample, donor.

This column is currently missing from the "full" manifest available from the project metadata download screen but is available in the "compact" manifest available from the "export selected data" flow. 

We are getting support requests from folks who have downloaded the full manifest from the project manifest screen and can not find the sequencing_process.provenance.document_id field to link to the DCP-generated matrices.

**Comment by hannes-ucsc** [comment]
> We are getting support requests from folks who have downloaded the full manifest from the project manifest screen and can not find the sequencing_process.provenance.document_id field to link to the DCP-generated matrices. 

I assume you mean this:

https://humancellatlas.slack.com/archives/C01360XN04S/p1620861131404600?thread_ts=1620840040.400800&cid=C01360XN04S

My response on that thread was

> It's important to know that while provenance.document_id is a field defined in the schema (every entity has it), the sequencing_process entity is synthetic. The schema only knows about process and analysis_process. Every primary subgraph has many process entities in it (each edge in the graph is a process). But there is one process that was of particular interest, the process that uses a sequencing_protocol and produces sequence_file entities. That's why the compact manifest dedicates a column to that specific type of process. The full manifest doesn't make this distinction and since it lacks any graph information, consumers of that manifest can't reliably  identify the sequencing processes in a subgraph.

> My vision is that we'll 1) continue to curate the compact TSV manifest with the columns we think (or are told) are important and 2) replace the pseudo-full manifest with a truly complete JSON manifest.

The `sequencing_process` entity is synthetic. A better word would be "virtual". The full manifest does not support virtual entities. The code that generates the full manifest would require substantial changes in order to support them. Because of the flaws inherent to the full manifest format, we don't plan on spending any considerable effort on the full manifest generation code. We are currently only maintaining it until we replace it with a full JSON manifest. That full JSON manifest will retain graph relationships, thereby eliminating the need for virtual entities altogether.
