### ISSUE TITLE
Provide a list of the possible fields included in the compact and full manifests

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#3074]
We will be documenting what is in the manifests on the data portal and will need information on what they will contain in the full case.

One approach is to just download a manifest of each type and look at the headers and this may be fine. 

However, I wanted to check if there was the possibility that some fields in the downloaded manifest might be missing for a given project as the project does not use that field.

Can you advise on the best way to obtain the set of fields in each manifest or provide the list?

Thank you,

**Comment by hannes-ucsc** [comment]
We should stop promoting the full manifest because of its many flaws. In the mid-term, it will be replaced by a JSON manifest (#2693). In the short-term the "download metadata" link will be changed to point to the compact manifest instead (https://github.com/HumanCellAtlas/data-browser/issues/1766).

Since the manifests are an artifact produced by Azul, the correct place to document them is not on the Data Portal page but as part of Azul's OpenAPI specification. Otherwise we'd create a brittle coupling between the Azul implementation and the Portal documentation. Instead, the portal could contain links that point to Azul's Swagger UI, or even have an (semi)-automated process that imports the manifest documentation from Azul's OpenAPI specification. I doubt it's a good idea to invest my team's time in a one-off effort that's leaves the AvroPFB and BDBag formats undocumented and that's bound to become stale in matters of months.

If you want to help extend the documentation of Azul's manifest APIs as part of its OpenAPI spec, we can discuss ways for you to contribute to the Azul source code.

A list of compact manifest fields will be created by #3072.

**Comment by theathorn** [comment]
Maybe a dup of #3055.
