### ISSUE TITLE
`Genus Species` values inconsistent between `Projects` and `Samples`/`Files` views

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3152]
Go to https://data.humancellatlas.org/explore/projects and from the "Projects" tab click on the "Donor" dropdown; not that "Unspecified" is not present. Click on the "Samples" or "Files" tab and then the "Donor" dropdown - "Unspecified" is now present.

I originally ran into this issue on https://data-browser.dev.lungmap.net/ :

- Select "File Format" = "LOOM"
- On Files tab, select "Donor" = "Unspecified"
- The Projects tab is now empty

**Comment by theathorn** [comment]
Spike to diagnose and estimate.

**Comment by danielsotirhos** [comment]
The issue stems from the case when an entity (e.g. supplementary file or sample) is part of a subgraph without a donor_organism entity.  In this case the "/index/samples" or "/index/files" endpoint would return an empty list in the hit's "donorOrganism" field (causing "Species" to be listed as "Unspecified"), however the response from the "/index/projects" would have a "donorOrganism" (and "Species") value since there is a donor in the project, just not connected to the file or sample entity.

Currently when Azul aggregates values for the "/index/projects" endpoint, it traverses the graph starting from all specimen and files to find all the donor entities, and then aggregates those together. Since it is aggregating what it found, the lack of finding a donor from the file or sample entity is not represented in the aggregated results.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to spike with a response.

**Comment by theathorn** [comment]
A suggestion discussed was for the Data Browser to auto-remove any filter selections on a tab for which that filter selection does not apply (e.g. in this case by removing "Genus Species = Unspecified" when viewing the Files tab).

**Comment by hannes-ucsc** [comment]
This is not a bug in Azul but the intended behavior. The project does have donors so it would be incorrect to pretend that it does not. It does have files that don't have donors but that's not the same. What if it has files that have donors, and samples that don't? Should we pretend that the project has no donors?

This may be counter-intuitive to users but we don't want to bend reality to address that, we need to help the user in understanding what's going on. As hinted by Trevor, I think the UI should highlight any currently active filters for which the termFacets part of the response indicates no hits. The highlighting indicates that a filter causes the response to be empty and that disabling it and all other highlighted filters would remedy that.

As an extension of this mechanism, the set of disabled (not removed) filters could be maintained per tab, so that switching tabs re-enables them. This requires implementing a distinction between removed and temporarily disabled filters.

**Comment by theathorn** [comment]
Closing in favor of HumanCellAtlas/data-browser#1895.

**Comment by hannes-ucsc** [comment]
The "wonfix" label indicates that the issue is valid and can be reproduced but that we decide not to fix it. The "invalid" label indicates that the issue can't be reproduced or that the observed behavior is expected.
