### ISSUE TITLE
Certain logged in users cannot access open access data

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3253]
Anonymous users can see all public data.
Login in to the data browser as a registered Terra user who does not have access to any managed access projects.
Now the Samples and Files tab show "No results".
The logged-in user should still have access to all open-access data.
TDR should grant access for all registered users to open access snapshots.

Note: Logged in users who are not registered with Terra will experience HumanCellAtlas/data-browser#1844.

**Comment by hannes-ucsc** [comment]
I don't think this is Azul's fault. Azul merely enforces the TDR access of the logged in user. In this case the logged in user does not seem to have access to any snapshots (not even the ones that should be publicly accessible) and so Azul hides all samples and files from them. I would expect any logged in user with a valid Google identity to have access to all non-managed-access snapshots in the TDR instance. Note that I say "any logged in user" and not "any logged in user that has previously registered with Terra". If we can't do the former, I'm willing to support the latter but it would require extending the Data Browser login flow to redirect unregistered users to the Terra registration page, and ideally back to the browser.

Until we fix this, the Data Browser will show publicly accessible files and samples to anonymous visitors, but hide them once the visitor logs in with their Google identity. That does not make sense.

**Comment by hannes-ucsc** [comment]
I should note that the user @theathorn was using to reproduce this, was actually registered with Terra.

**Comment by nmalfroy** [comment]
For the point about Terra registers users, that's actually what is needed for authz in Terra, not just a Google identity.  That being said, we could do this a couple of ways:
- mark not controlled snapshots as public.  That means any user in TDR can see those snapshots but it would also solve your issue
- automatically (read programmatically) add users to a 'public-hca' Terra group that all public hca snapshots can grant reader role to.  That would accomplish the same thing and be more specific to the hca snapshots

Does that make sense?

**Comment by theathorn** [comment]
@nmalfroy also wrote "Worth noting: both require being registered in Terra (since what we really need is a Terra user, not just a Google user)".

**Comment by hannes-ucsc** [comment]
> Does that make sense?

Not completely, I think.

>  That would accomplish the same thing 

Agreed.

> and be more specific to the hca snapshots

If you made only the HCA snapshots public that would also be specific to HCA snapshots. In other words, I don't understand how marking snapshots public is less specific as automatically adding users to a group that has read access to the HCA snapshots. Both solutions would only apply to HCA snapshots. Maybe I'm misunderstanding something.

As long as the TDR team implements it, I am OK with either option. If the thought was that Azul or Data Browser automatically modifies a Terra group, I would have a hard time agreeing to that. I do not want Azul to have ANY permission to modify anything in Terra. If the TDR team implements option B (auto add to group), I would caution that it seems a bit unconventional to modify on first access. It might introduce race conditions because Azul would, immediately after auto adding the user to that group, try to determine the snapshots the user has access to.

**Comment by theathorn** [comment]
This problem was "fixed" by logging out of Data Browser and then requesting an "Export to Terra" as an anonymous user. This took me to https://bvdp-saturn-dev.appspot.com/ which recognized my theathor@ucsc.edu as an already logged in Terra user. I closed the Terra window and re=logged in as theathor@ucsc.edu on the Data Brower and now the Samples and Files tabs are populated. I can no longer reproduce the problem with any of my Google accounts (there are 3, all registered with Terra) even if I log out of Terra and logout of Chrome.
