### ISSUE TITLE
`python -m venv` produces bad deployment

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#340]
Running `make deploy` from a virtualenv that was created with `python -m venv` results in a non-functioning Lambda. The indexer lambda, for example, raises

```
Unable to import module 'app': No module named 'crcmod'
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-221)
┆Project Name: azul
┆Issue Number: AZUL-221

**Comment by GPelayo** [comment]
When a user is trying to deploy Azul, the following messages is displayed.
```
Creating deployment package.

Could not install dependencies:
jsonobject==0.7.1
hca-metadata-api==1.0b9
jmespath==0.9.4a1
retrying==1.3.3
pycparser==2.19
crcmod==1.7
future==0.16.0
aws-requests-auth==0.4.2
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://chalice.readthedocs.io/en/latest/topics/packaging.html
```

From this message, we can deduct that `crcmod` and other libraries weren't properly installed remotely. This explains why the `crcmod` module can't be imported. 

Chalice can only download `crcmod` and the other missing libraries as source distributions or incompatible wheels that require rebuilding. When Chalice attempts to use pip to build these libraries into an installable wheel, `pip wheel` throws an error message when trying to run its build wheel command.
```
b"ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel\nYou are using pip version 9.0.3, however version 19.0.2 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"
```
So the reason `python -m venv` produces a bad deployment because it requires the `wheel` package to be installed.
