### ISSUE TITLE
Set up prod deployment for new TDR production instance 

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3517]
Two snapshots are now available:

Dataset: hca_prod_6072616c87944b208f52fb15992ea5a4__20211004
Snapshot: hca_prod_6072616c87944b208f52fb15992ea5a4__20211004_20211004
Google Project ID: datarepo-486c6d02

hca_prod_df88f39f01a84b5b92f43177d6c0f242__20211004
Snapshot: hca_prod_df88f39f01a84b5b92f43177d6c0f242__20211004_20211004
Google Project ID: datarepo-49f1b676

These are located in the US multi-region.

**Comment by hannes-ucsc** [comment]
Assignee (must be operator) to duplicate the `prod` deployment. Call it `prod2`. Have it share the ES instance in `prod`. All operations related to that deployment will be manual. Since this isn't urgent, the PR can target `develop` branch. After first review by me, assignee to create the deployment from their local machine and test the deployment. Then another review by me, rinse and repeat, merge to develop. I don't think we need to create another branch for this deployment. It should always be at the `prod` branch or a little behind. I'll file a PR that tweaks the check branch logic to allow for more deployments per branch.

**Comment by hannes-ucsc** [comment]
For demo, make a few requests against various endpoints in the new deployment.

**Comment by hannes-ucsc** [comment]
Should demo this twice, next week internally and the following Tuesday DCP-wide.
