### ISSUE TITLE
Create S3 bucket to persist BDBag for FireCloud export

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#36]
The creation of the S3 storage bucket should occur during the webservice deployment process.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-28)
┆Project Name: azul
┆Issue Number: AZUL-28
┆Epic: Epic 8: “Handoff” From Portal to Workspace

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

I created two bucket in the S3 of the platform-dev account which have the settings following the description in the update of the README in feature/commons of cgp-deployment.

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

The buckets are named "azul-s3-bucket" and "bdbag".

**Comment by coverbeck** [comment]
Why are there 2 buckets? Shouldn't there just be one?

**Comment by mjkrause** [comment]
They are in S3 in our `platform-dev` account. I created those following my own instructions in the readme. That's how we wanted to go about it. The user creates them manually in their account. Then in the install script the user provides the address of the bucket so it is stored in an environment variable.

**Comment by coverbeck** [comment]
I'm asking why are there 2 buckets instead of just 1 bucket. What is going into each bucket? In your design document, the BDBags go into the bucket specified by AZUL_S3_BUCKET... What will go into the other bucket?

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

Not sure I understand. Do you refer to the word “webservice” in the description of this story, and it is actually part of cgp-deployment?

**Comment by coverbeck** [comment]
The description currently says `The creation of the S3 storage bucket should occur during the webservice deployment process.`. I initially read this, perhaps influenced by our discussion yesterday, as saying that the webservice creates the bucket, but I was wrong. Although to me it still implies something is happening as part of the deploy script, when you ended up creating it via AWS Console..

You had closed the bug saying that you had created two buckets, so I thought you were done with it. Which is why I asked about the second bucket, because I didn't realize you were going to revisit.

If you are still exploring features for the bucket, then you probably shouldn't have closed the ticket, unless you have another ticket to fine-tune the features.
