### ISSUE TITLE
Enable GitLab ALB request logging

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3604]
In the aftermath of the security incident, I noticed that the GitLab request logs only contain the IP addresses of the load balancers. Apparently, X-Forwarded-For is not logged by GitLab. We should enable [request logging](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html) on the ALB and, if possible, connection logging on the NLB.

**Comment by achave11** [comment]
[pl] @hannes-ucsc: "Put back into progress, separate PR to remove NLB logging because it doesn't work due to the fact that we don't use TLS."
[sn hint] Use AWS S3 recursive sync recur sub -> gunzip all, grep them for something not having the -v `gitlab-runner`.
- [ ] Click around in the GitLab instance, and make sure IP from home PC shows up in the logs.

**Comment by achave11** [comment]
The following demonstrates the proper logging of my browsing activity (via IP) in the GL instance.
![Screen Shot 2021-11-30 at 1 23 01 PM](https://user-images.githubusercontent.com/19215510/144130526-0832998f-b825-4924-b996-278b264ae25d.png)

**Comment by hannes-ucsc** [comment]
For demo, click around in GitLab, then snow the resulting log entries.
