### ISSUE TITLE
Experiment with serialization of retries

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3629]
To validate the approach we're taking for #3315 and #3359, perform a reindex of `prod` (with three catalogs `dcp1`, `dcp10` and `dcp11`) in which we process retries only after all messages have been attempted once. Disable the SQS trigger and zero out the reserved concurrency of the `…_retry` Lambdas. Then kick off the reindex. Once the non-retry queues (both notifications and tallies) are empty, re-enable the `contribute_retry` lambda. Once the `notifications_retry` and the non-retry `tallies` queues are empty, re-enable the `aggregate_retry` lambda. Collect dashboard screenshots. There should be fewer messages in the fail queues that have to be re-fed and the overall indexing time (minus the pauses for reenabling the lambdas) should be shorter. Re-feed all failures to bring `prod` into a good state.

**Comment by amarjandu** [comment]
DIsabled SQS-Lambda trigger for `contribute_retry` and `aggregate_retry` lambdas in `prod`, set reserved concurrency for both lambdas to `0`.

**Comment by amarjandu** [comment]
Started `reindex` of `prod` https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/11445

**Comment by amarjandu** [comment]
Notifications and Tallies are at 0 in the azul-prod cloudwatch dashboard, enabling the `contribute-retry lambda`

**Comment by amarjandu** [comment]
enabled the `aggregate_retry` lambda in `prod`

**Comment by amarjandu** [comment]
The previous prod reindex took ~20 hours and 5 min to complete. (23:20 total - 3:15 where tallies were stuck due to shard issues)

The experimental reindex took ~16 hours and 11 min to complete. (15:04 to process notifications + 1:07 to process tallies)

The hypothesis of lower transient failures and shorter overall duration was correct. There were no additional transient failures apart from the 5 expected bundles that failed

Overall time for experiment:
<img width="3120" alt="Screen Shot 2021-11-17 at 2 48 41 PM" src="https://user-images.githubusercontent.com/1947534/142332552-61dc476f-2dee-4ec3-a095-5699fa51ca09.png">

Aggregate retry for tallies during experiment:
<img width="3120" alt="Screen Shot 2021-11-17 at 2 51 47 PM" src="https://user-images.githubusercontent.com/1947534/142332643-b7a80226-75d3-4164-9c6c-973b623cb093.png">

.

**Comment by theathorn** [comment]
@hannes-ucsc "We had no transient failures and did not need to re-feed any messages, confirming that the approach outlined in #3315 and #3359 works."
