### ISSUE TITLE
Automate creation of FedRAMP inventory

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3634]
From [Automating creation of a FedRAMP Integrated Inventory Workbook](https://aws.amazon.com/blogs/publicsector/automating-creation-fedramp-integrated-inventory-workbook/):

> Did you know AWS can help deliver an automated solution for creating the FedRAMP Integrated Inventory Workbook? This workbook needs to be updated and submitted to the FedRAMP Project Management Office (PMO) monthly for continuous monitoring. Automating this workbook saves manual work hours. Any customer going through the FedRAMP authorization process can leverage this workbook. Understand how to gather an inventory of AWS resources from AWS Config data to create the FedRAMP Integrated Inventory Workbook.

Edit 1: Include the list of packages installed in the GitLab instance.

Edit 2: Include accounts in the inventory so we can cover AC-j (account review).

**Comment by theathorn** [comment]
Can this be used to fill in 10.2 "Ports, Protocols and Services" in the [Azul Data Browser FedRAMP SSP](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r) or we need a separate ticket?

**Comment by theathorn** [comment]
Raised #3998 and #3999 for the above issues.

**Comment by theathorn** [comment]
@nolunwa : What is Dockstore using to implement this control?

**Comment by nolunwa** [comment]
@theathorn AWS provides an automated solution for creating the [FedRAMP Integrated Inventory Workbook]. AWS gathers an inventory of AWS resources from AWS Config, Lambda and Cloudwatch Event data to create the FedRAMP Integrated Inventory Workbook. see the[ full blog post](https://aws.amazon.com/blogs/publicsector/automating-creation-fedramp-integrated-inventory-workbook/) for teams review and adoption

**Comment by hannes-ucsc** [comment]
OK, read the blog post. Seems reasonable. However, the solution presented only reports a handful of resource types:

Which resource types do *we* need to include in our report?

**Comment by nolunwa** [comment]
@hannes-ucsc I shared with you the Dockstore inventory we modified our final report. Also should include system-specific information required for component accountability which includes internally developed software, asset type for computing, networking, database and Hardware should be included For any resource outside of AWS should be included manually added

**Comment by hannes-ucsc** [comment]
https://github.com/dockstore/lambda

**Comment by hannes-ucsc** [comment]
That makes it clear. Thank you.

**Comment by hannes-ucsc** [comment]
Resources to include:

- EC2 instance
- Application load balancer
- Network load balancer
- Client VPN endpoint
- OpenSearch domain
- VPC endpoint
- CloudFront distribution
- API Gateway
- Lambda function
- S3 bucket
- SQS queue

Follow the pattern lined out in the blog post, and continued by the Dockstore team (see above). Copy their Python code but minimize changes to it, so that we can reintegrate later. Add mappers for the resource types listed above that are not currently supported. With respect to infrastructure and glue code (Terraform config, app.py) we'll have to deviate from the blog post and follow our own conventions.

No follow-up tickets needed. Will track implementation in this ticket.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to dust off the ticket. @nolunwa expressed that this is relatively urgent.

**Comment by hannes-ucsc** [comment]
Study the blog post linked to in the description above. 

Contrary to what's outlined in that blog post, we will not use a Lambda but a scheduled GitLab pipeline instead. The main job of that pipeline does two things: it …

1) runs a script that generates the Excel spreadsheet (that format is a FedRAMP requirement, CSV is not sufficient) and

2) marks that spreadsheet as a build artifact (as opposed to the uploading the spreadsheet to an S3 bucket as the blog post suggests).

The script issues a query against AWS Config in order to list resources of specific types (those that we have mappers for, see below) and then iterates over the results, writing a row per resource to the output spreadsheet. The column schema of the spreadsheet is prescribed by FedRAMP. I don't mind the use of the data mapper design pattern suggested in the blog post, but I think the three classes `AwsConfigInventoryReader`, `CreateReportCommandHandler` and `DeliverReportCommandHandler` could all be combined into a single service class. Include any applicable mappers that the Dockstore team added to their [implementation](https://github.com/dockstore/lambda/tree/develop/fedramp-integrated-inventory-workbook) of this control. Most of the code should live in the `src` directory of the Azul source tree. The script itself should be kept slim. It should be possible to run the script locally.

For extra credit: I would also like to remove the resource type restriction from the WHERE clause in the AWS Config query so that resources of all types are returned. Implement a generic, default mapper that can map any resource type to the spreadsheet column schema. It's OK for the default mapper to be lossy. Resources with specialized mappers should got to the top of the spreadsheet. Additionally, the ordering of rows must be deterministic.

For extra extra credit, have the script update a [wiki](https://docs.gitlab.com/ee/user/project/wiki/) page in the `azul` project on the GitLab instance it is running on. The wiki page should be in a format that most closely corresponds to the AWS Config query result. The ordering of resources on the wiki page should be consistent with that of the rows in the spreadsheet. GitLab wiki pages are files in a special Git repository hosted on GitLab, so we'd also be tracking the **history** of the inventory that way.

**Comment by hannes-ucsc** [comment]
For demo, show report in `dev`, `anvildev` and `prod. Discuss improvements to the report. Discuss wiki mode. File tickets as needed.
