### ISSUE TITLE
GitLab job `sell_unused_slots` should cover all used locations

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3673]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/34351 indicates that there are no unused slots to sell, however there was an idle slot commitment incurring unnecessary cost.
![Screen Shot 2021-11-29 at 5 17 39 PM](https://user-images.githubusercontent.com/19215510/143969242-e5d57087-965a-458f-a3ca-080824483fd7.png) Image dated: 2021-11-29 @ 17:17:39

**Comment by noah-aviel-dove** [comment]
The screenshot shows that the slots were purchased in the `US` location. However the `dev` deployment is configured to purchase slots in the `us-central1` location. The script only checks for slots in its configured region.

**Comment by noah-aviel-dove** [comment]
I think we ought to include the configured location in the log output of `sell_unused slots`.

**Comment by hannes-ucsc** [comment]
I think this was me running `make reindex` with production snapshots in my personal deployment. Thank you for catching that, @achave11.

Since what I did is a reasonable use case, we should extend `sell_unused slots` to loop over all regions in yet another config variable, `AZUL_TDR_ALLOWED_SOURCE_LOCATIONS`. That variable would only be set in the root `environment.py` and it would need to contain the locations referenced by all deployments. `config.tdr_source_location` would need to ensure that the configured location is listed in `AZUL_TDR_ALLOWED_SOURCE_LOCATIONS`.

**Comment by hannes-ucsc** [comment]
For demo, buy slots manually in both configured locations and run the script. It should sell them all.
