### ISSUE TITLE
Allow for sorting by `lastModifiedDate`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3679]
… with `lastModifiedDate` being defined as `updateDate` or `submissionDate`, whichever is more recent.

[Slack discussion](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1638407004065000).

**Comment by theathorn** [comment]
@hannes-ucsc to fill in details.

**Comment by hannes-ucsc** [comment]
I think we should allow all three use cases:

1) sort by `submission_date` (can't have `null` values)

2) sort by `update_date` (`null` values should go at the end of a descending order so that they appear after the projects that were updated a long time ago, as in "never updated" is more stale than "updated a long time ago")

3) sort by `max(submission_date, update_date)` (can't result in `null` values since `null` is less than anything else and `submission_date` is never `null`, see use case 2)

Use case three should be accomplished by a synthetic index field called `last_modified_date` with a matching response  property called `lastModifiedDate`.

The Data Browser is free to show columns for all three fields or just one. If it were up to me, I would display a single column for `lastModifiedDate` and, when the user hovers over a cell, display a tool tip displaying the other two fields.

**Comment by hannes-ucsc** [comment]
For demo, all `/index/...` endpoints by all six fields in both directions, ascending and descending, and prove the ordering of the results. For endpoints with a large number of results like `/index/files` and `/index/bundles`, apply a suitable filter that constrains the number of results while still yielding results with sufficient diversity in the sort field to prove the ordering.

**Comment by danielsotirhos** [comment]
Missing entries in translation for `submission_date`, `update_date`, and  `last_modified_date` fields. This prevents us from sorting by these fields.

@hannes-ucsc: "Consider moving the aggregate fields from `contents.aggregate_dates` to `contents.projects` (for the projects index) and `contents.bundles` (for the bundles index). If that is not possible, comment here as to why."

**Comment by melainalegaspi** [comment]
@danielsotirhos to provide follow-up PR to address the issues mentioned in the above comment.
