### ISSUE TITLE
PFB exports missing DRS links

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3689]
From DCP demo on 12/7/21: A PFB export of loom files results in a "Files" tab in Terra with a non-clickable "drs_path" column but no clickable DRS link (which is present when using the BdBag format).

**Comment by danielsotirhos** [comment]
I was unable to create a Terra workspace with my account, however I believe the issue is due to the `BdBag` manifest returning a full DRS URI, while the `PFB` manifest returns only the suffix of the DRS URI.

![Screen Shot 2021-12-17 at 9 07 31 AM](https://user-images.githubusercontent.com/46407464/146584393-fb19536d-036c-44d1-9ec8-53c8ca6a4fad.png)

The conversion of a `drs_path` to a DRS URI is done by [ManifestGenerator._extract_fields](https://github.com/DataBiosphere/azul/blob/abcaa7c6a04f1f5b8fd74e449e254eff6c433913/src/azul/service/manifest_service.py#L746) which the `CompactManifestGenerator` and `BDBagManifestGenerator` use, but the `PFBManifestGenerator` does not.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Agreed. We need to compose the complete DRS URI from drs_path and the plugin's base_url for DRS."

**Comment by hannes-ucsc** [comment]
For demo, perform a AvroPFB hand-over to Terra and show the new column with proper DRS URIs.
