### ISSUE TITLE
Export BDBag to S3 bucket

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#38]
Part of persisting the BDBag so FireCloud can import it from a pre-signed URL.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-30)
┆Project Name: azul
┆Issue Number: AZUL-30
┆Epic: Epic 8: “Handoff” From Portal to Workspace

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

In order to test modifications in azul/webservice.py created a new feature branch feature/mkrause/s3-bdbag-dev in the GitHub cgp-deployment repo. 

Then I changed the GitHub branch azul is installed from in cgp-deployment/install_bootstrap from feature/commons to feature/persistent-bdbag.

That way, if the install is run, it will download from the relevant branch where I made changes.

**Comment by coverbeck** [comment]
You can also just manually change checkout a different branch on your ec2 instance as well, without running `install_bootstrap`.

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

I encountered a blocker when I was unable to log in on mkrause.ucsc-cgp-dev.org. With Charles' help we found the root of the problem: in the log files of docker-compose  the following is stated: too many certificates already issued for exact set of domains: [_mkrause.ucsc-cgp-dev.org_](http://mkrause.ucsc-cgp-dev.org): see [_https://letsencrypt.org/docs/rate-limits/_](https://letsencrypt.org/docs/rate-limits/).

I will try to create a subdomain [_mkrause2.ucsc-cgp-dev.org_](http://mkrause2.ucsc-cgp-dev.org) to get around that problem.

See here [https://crt.sh/?q=%.ucsc-cgp-dev.org](https://crt.sh/?q=%25.ucsc-cgp-dev.org) for an overview of domains and certificate expiration dates.

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

Opened a PR at [https://github.com/DataBiosphere/azul/pull/269](https://github.com/DataBiosphere/azul/pull/269).
