### ISSUE TITLE
Enforce a concurrent session limit per user

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#3833]
Limit the number of concurrent HTTP connections by source IP for unauthenticated anonymous access, and by OAuth access token for authenticated access.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Will limit both to 10."

**Comment by theathorn** [comment]
@hannes-ucsc : "I need to think about this some more. WAF does not limit concurrent connections, only number of requests per 5 minutes. In light of the fact that requests must finish within 29s (API Gateway requirement), the two metrics may be related."

**Comment by hannes-ucsc** [comment]
It turns out that it is difficult in applications fronted by API Gateway to limit the number of concurrent *connections*. We can only limit requests rates via WAF or API Gateway throttles.

However, this control requires a limit on the number of *sessions*, not connections, so we will need to revert the decision to approximate one with the other.

We will not limit the number of sessions for anonymous users. Technically there is no session since there is no authentication. We will instead limit the request rate via WAF to 100 requests per 5 minutes, the minimum. 100 requests in 300 seconds means one request every 3s. If every requests takes 30 s (the maximum allowed by API Gateway) you end up with at most 10 pending requests on average.

For Google Cloud and AWS (interactive and programmatic sessions by internal users), we will refer to the Control Implementation Summary and Customer Responsibility Matrix (CIS/CRM) by AWS and inherit whatever limits AWS applies.

External users log into Azul via Google OAuth 2. In OAauth 2.0, a session is represented by an access token. There is a token grant limit of 10,000,000 grants per day (116 per second) in place. That's unrealistically high for our purposes, and wouldn't protect the Azul app from abuse. It's also a global limit, as opposed to per-user, so it wouldn't isolate malicious requests from benign ones.

To limit the number of sessions i.e., access tokens we would need to know the user's identity and that can only be obtained from an ID token—the `sub` claim in the ID token, to be specific. There are two mechanisms by which an ID token can be obtained: 1) it is sent to the application (along with the access token) or 2) it can be obtained from the provider's userinfo endpoint. In either case, the `openid` scope must have been included in the initial request to the provider's authentication endpoint. The first option is preferred since it eliminates the need for an additional, server-side request by Azul to the authentication provider (Google). Once Azul has the ID token, it can extract a user's identifier (ID) from the `sub` claim in that token. 

Currently we cache user info (like the snapshots they have access to) in a DynamoDB table keyed on the access token. We need to change that to be keyed on the user ID. Once cache lines are per user, instead of per access token, we can limit the number of access tokens per user by storing a set of access tokens in the cache line. We can then limit the size of that set to, say, 10 and reject requests that would cause that set to exceed the limit.

For this to work, the client (Data Browser, Swagger UI) *must* specify the `openid` scope when authenticating the user. The client *should* pass both an access token and the ID token to Azul. If it doesn't, Azul needs to first make a request to the provider's userinfo endpoint to obtain the ID token. Azul will support a proprietary bearer token format that combines the access and ID tokens. We'll probably use the same mechanism as JWT (base64-encoded JSON) as the format. In the interim, Azul will support both stand-alone access tokens and combined bearer tokens. To detect which type of token it was passed, Azul will attempt to unpack the combined token and if that fails, assume that an access token was passed, and hit the userinfo endpoint to get the ID. At a later stage, we'll make the combined format mandatory so as to completely avoid the userinfo roundtrip.

**Comment by hannes-ucsc** [comment]
- [ ] Make Swagger UI request `openid` scope (may also need `profile` scope, I'm not sure)
- [ ] Hit Google's `/userinfo` endpoint to obtain ID token
- [ ] Validate ID token and extract `sub` claim
- [ ] Change cache line to be keyed on ID from `sub` claim of ID token
- [ ] Track set of access token in cache line 
- [ ] Limit set size to 10, return a 403 with a descriptive body if limit would be exceeded

**Comment by hannes-ucsc** [comment]
Solution to this should be deployed at the same time as #

**Comment by nolunwa-ucsc** [comment]
Implementation of AC-10: concurrent session only applies to High impact level syste based on the Rev 5 adoption. The team can decide not to implement and close this ticket @hannes-ucsc

**Comment by nolunwa-ucsc** [comment]
closing this ticket, see comment from August 8th
