### ISSUE TITLE
Unit test imaging subgraphs from schema-test-data

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3873]
https://github.com/HumanCellAtlas/schema-test-data/pull/16

The primary goal is to make these subgraphs pass indexing and to survey which, if any, of the imaging-specific properties we already index and expose. The latter will guide us in scheduling follow-up work.

Once assignee is confident that we can index these subgraphs, they should approve the PR.

**Comment by danielsotirhos** [comment]
Out of the 5 bundles in https://github.com/HumanCellAtlas/schema-test-data/tree/35be6652afbd9a84837abcc79594367f92f265fd/tests , all were canned and 1 (3ac62c33) failed to be indexed.

The index failure was due to a schema change in `imaging_protocol`.
Previous versions of [imaging_protocol](https://schema.staging.data.humancellatlas.org/type/protocol/imaging/11.1.0/imaging_protocol) had a required [target](https://schema.humancellatlas.org/module/protocol/1.1.0/target) object which contains an `assay_type`.
The new version of [imaging_protocol](https://schema.staging.data.humancellatlas.org/type/protocol/imaging/11.3.0/imaging_protocol) removed `target` and added a [probe](https://schema.staging.data.humancellatlas.org/module/protocol/1.1.1/probe) object which has the `assay_type`.

A change to [hca-metadata-api](https://github.com/DataBiosphere/hca-metadata-api/blob/ce347f9362a92089a3f063b5aec2480e3d762f7e/src/humancellatlas/data/metadata/api.py#L764) will be required in order to support the change to the `imaging_protocol` schema, 

Imaging-specific properties hca-metadata-api currently supports are:
- imaged_specimen: slice_thickness
- imaging_protocol: target.assay_type
- *imaging_preparation_protocol: (no imaging specific fields, treated like other `protocol` documents)
- *image_file: (no imaging specific fields, treated like other `file` documents)

Imaging-specific properties Azul indexes and expose are:
- hits[].protocols[].assayType
