### ISSUE TITLE
Send GitLab host logs to CloudWatch

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3894]
`/mnt/gitlab/logs/`
`/var/log/`

![Data Browser System Overview - Logging   Monitoring(1)](https://user-images.githubusercontent.com/5143256/222058627-ba776188-dea1-4277-a7dd-a5b42d096065.png)

**Comment by achave11** [comment]
General outline of steps:

1. Build docker image for agent https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-build-docker-image.html
2. Start EC2 instance from rancher AMI that's used by our GitLab instance (@amarjandu can help).
3. Upload image tarball to EC2 instance
4. Import tarball
5. Configure agent
6. Start container from image
7. Verify that logs are send to cloudwatch

It's importat to be aware of the distinction between the deprecated and the new agent. See note at top of page https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html.

**Comment by hannes-ucsc** [comment]
Change of plans: we'll be migrating the GitLab instance to start from the Amazon Linux AMI on which the CloudWatch agent can be installed via `yum`.

**Comment by hannes-ucsc** [comment]
Docker uses the `syslog` driver by default. On the Amazon Linux AMI, this causes all container output (stderr and stdout) to be written to `/var/log/messages`. The container running the `gitlab` image on that instance runs a [wrapper](https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/085b9303e8d4080686349d087789ca7165a09397/docker/assets/wrapper#L190) which runs `gitlab-ctl tail` in the background, which runs Unix [tail](https://github.com/chef/omnibus-ctl/blob/main/lib/omnibus-ctl.rb#L577) on all log files written to `/var/log/gitlab` in the container (`/mnt/gitlab/logs` on the host). The `tail` command is invoked with `--name` which causes every line in tail's output to be prefaced with a line reading `===> /var/log/gitlab/foo.log`. This is relatively useless because the adjacency correlation gets lost in `/var/log/messages` on the host with interspersed lines from other processes.

We should disable the tail by setting `GITLAB_SKIP_TAIL_LOGS` for the `gitlab` container so that the verbose GitLab container logs don't pollute `/var/log/messages`. They are already available on the host under `/mnt/gitlab/logs` from where the CloudWatch Logs agent can be [configured](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection) pick them up.

Scan all file system for other log directories we might want to forward to CloudWatch. The SSM agent log directory comes to mind, for example.

**Comment by achave11-ucsc** [comment]
All the log entries agreed on were added, and are active. Additionally, the experiment on `…/reconfigure/{dated}.log` was successful, not only is the log forwarded after starting and stopping the `gitlab` deamon (and dependents), but the log forwards the re-creation of the instance (when new log entries and related changes were pushed) as well.

**Comment by hannes-ucsc** [comment]
For demo, show that the forwarding of the logs survives restarting the agent (via systemctl restart) as well as rebooting  and recreating the instance. Show evidence the GITLAB_SKIP_TAIL_LOGS does indeed prevent GitLab log files from being tailed or sent to the host. Show that the agent picks up new log files matching `/mnt/gitlab/logs/reconfigure/*.log` without having to be restarted. I *think* restarting the `gitlab` container or running `gitlab-ctl reconfigure` inside it causes a new log file to be created.

https://docs.gitlab.com/ee/administration/restart_gitlab.html#omnibus-gitlab-reconfigure

**Comment by nolunwa-ucsc** [comment]
@dsotirho-ucsc Please update this spreadsheet to include the Gitlogs audit event captured in cloudwatch. https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit#gid=311132757
