### ISSUE TITLE
Investigate GitLab merge trains

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3906]
From retro 2/25/2022 @amarjandu : "Consider looking into GitLab merge trains in order to reduce time between `approve` and `merged`"

**Comment by hannes-ucsc** [comment]
Merge trains speculatively build multiple mergeable PR in parallel. If two PR branches A and B are mergeable, two builds are started: one build for `merge(develop, A)` and another one for `merge(merge(develop, A), B)`. This could help if it weren't for the sandbox. We can't build multiple PRs concurrently in a single deployment. 

When we accrue merge debt (a large number of tickets in the `Approved` column), it's not because GitLab is the bottleneck, GitLab is mostly idle, actually. It's because the operator is busy (sometimes correctly so) with other things or simply not good at multitasking and keeping GitLab busy.
