### ISSUE TITLE
Confusing/duplicate tables in PFB manifest

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3908]
While giving a LungMAP demo, a question came up concerning the meaning and utility of the sample_specimens vs samples vs specimens tables. It appears that sample_specimens is a duplicate of specimens.

![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/c9376bd7-ea40-4490-810d-ab4b93235cc5)

![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/fe57c354-85cb-4d92-a1d4-757c3f0357eb)

**Comment by hannes-ucsc** [comment]
> It appears that sample_specimens is a duplicate of specimens.

It's a non-strict subset. A sample is a biomaterial from which a cell suspension is derived. Not all specimens are samples.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to provide language that documents the samples and sample_foo tables for the data portal. Once that documentation is on the portal, the browser should link to that portal page from the handover page.

**Comment by hannes-ucsc** [comment]
After a successful handover from the Data Browser, the Terra workspace will be populated with a number of data tables. Most of these tables are self-explanatory. The HCA metadata schema distinguishes between five main types of entities: projects, biomaterials, files, processes, and protocols. Processes represent concrete derivations of biomaterials from concrete biomaterials, or files from biomaterials, or files from other files. Protocols represent the modalities of such processes. A protocol can be seen as a recipe, and a process as the execution of that recipe. Since there are many processes in a typical HCA project, the handover only includes the protocols used by them.

**Comment by hannes-ucsc** [comment]
Didn't mean to close this.

**Comment by theathorn** [comment]
@theathorn to create corresponding data portal ticket.

**Comment by theathorn** [comment]
@hannes-ucsc to document sequence inputs table.

**Comment by hannes-ucsc** [comment]
Done.
