### ISSUE TITLE
Error creating file manifest for LungMAP project

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3982]
Reproduction steps:
  - At https://data-browser.lungmap.net/ click checkbox to select "Genomic, epigenomic, and biophysical cues controlling the emergence of the lung alveolus"
  - Click "Export Selected Data" / "Request File Manifest"
  - Click "Confirm Species" (Mus musculus)
  - "Select All" file types / "Prepare Manifest"
  - Error page:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/45b60fed-92ec-4c15-9207-001ef8f46170)

Manifest generated OK on a 2nd attempt.

**Comment by theathorn** [comment]
Spike to correlate with Cloudwatch logs for manifest lambda.

**Comment by achave11** [comment]
It failed due to the following:
```
[ERROR] ClientError: An error occurred (InvalidTag) when calling the PutObjectTagging operation: The TagValue you have provided is invalid
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1564, in __call__
    return self.handler(event_obj)
  File "/var/task/chalice/app.py", line 1517, in __call__
    return self._original_func(event.to_dict(), event.context)
  File "/var/task/app.py", line 1613, in generate_manifest
    return app.manifest_controller.get_manifest(event)
  File "/var/task/azul/service/manifest_controller.py", line 77, in get_manifest
    result = self.service.get_manifest(format_=ManifestFormat(state['format_']),
  File "/var/task/azul/service/manifest_service.py", line 388, in get_manifest
    partition = generator.write(object_key, partition)
  File "/var/task/azul/service/manifest_service.py", line 1041, in write
    self.storage.put_object_tagging(object_key, tagging)
  File "/var/task/azul/service/storage_service.py", line 211, in put_object_tagging
    self.client.put_object_tagging(Bucket=self.bucket_name,
  File "/opt/python/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

Here are the pertinent logs of the execution:
<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">@timestamp</th>
<th title="Field #2">@message</th>
</tr></thead>
<tbody><tr>
<td>2022-03-23 23:25:10.418</td>
<td>END RequestId: c6b8c38b-a402-47b6-a9db-cfbf5e236d5f<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:10.418</td>
<td>REPORT RequestId: c6b8c38b-a402-47b6-a9db-cfbf5e236d5f	Duration: 1236.00 ms	Billed Duration: 1237 ms	Memory Size: 2048 MB	Max Memory Used: 155 MB	Init Duration: 2529.08 ms	<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:10.413</td>
<td>[ERROR] ClientError: An error occurred (InvalidTag) when calling the PutObjectTagging operation: The TagValue you have provided is invalid<br/>Traceback (most recent call last):<br/>  File &quot;/var/task/chalice/app.py&quot;, line 1564, in __call__<br/>    return self.handler(event_obj)<br/>  File &quot;/var/task/chalice/app.py&quot;, line 1517, in __call__<br/>    return self._original_func(event.to_dict(), event.context)<br/>  File &quot;/var/task/app.py&quot;, line 1613, in generate_manifest<br/>    return app.manifest_controller.get_manifest(event)<br/>  File &quot;/var/task/azul/service/manifest_controller.py&quot;, line 77, in get_manifest<br/>    result = self.service.get_manifest(format_=ManifestFormat(state[&#39;format_&#39;]),<br/>  File &quot;/var/task/azul/service/manifest_service.py&quot;, line 388, in get_manifest<br/>    partition = generator.write(object_key, partition)<br/>  File &quot;/var/task/azul/service/manifest_service.py&quot;, line 1041, in write<br/>    self.storage.put_object_tagging(object_key, tagging)<br/>  File &quot;/var/task/azul/service/storage_service.py&quot;, line 211, in put_object_tagging<br/>    self.client.put_object_tagging(Bucket=self.bucket_name,<br/>  File &quot;/opt/python/botocore/client.py&quot;, line 357, in _api_call<br/>    return self._make_api_call(operation_name, kwargs)<br/>  File &quot;/opt/python/botocore/client.py&quot;, line 676, in _make_api_call<br/>    raise error_class(parsed_response, operation_name)</td>
</tr>
<tr>
<td>2022-03-23 23:25:10.200</td>
<td>[INFO]	2022-03-23T23:25:10.200Z	c6b8c38b-a402-47b6-a9db-cfbf5e236d5f	POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_lm2_files_aggregate/_search [status:200 request:0.022s]<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:09.510</td>
<td>[INFO]	2022-03-23T23:25:09.510Z	c6b8c38b-a402-47b6-a9db-cfbf5e236d5f	POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_lm2_files_aggregate/_search [status:200 request:0.078s]<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:09.427</td>
<td>[INFO]	2022-03-23T23:25:09.427Z	c6b8c38b-a402-47b6-a9db-cfbf5e236d5f	Found credentials in environment variables.<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:09.411</td>
<td>[DEBUG]	2022-03-23T23:25:09.410Z	c6b8c38b-a402-47b6-a9db-cfbf5e236d5f	Creating ES client [search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443]<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:09.355</td>
<td>[INFO]	2022-03-23T23:25:09.355Z	c6b8c38b-a402-47b6-a9db-cfbf5e236d5f	Cached manifest not found: manifests/a5b96300-fc4b-56c5-a334-977b22e4b243.ef1411d7-c135-57e3-8d6d-5b924bc6cdbf.tsv<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:09.195</td>
<td>[INFO]	2022-03-23T23:25:09.194Z	c6b8c38b-a402-47b6-a9db-cfbf5e236d5f	Found credentials in environment variables.<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:09.178</td>
<td>START RequestId: c6b8c38b-a402-47b6-a9db-cfbf5e236d5f Version: $LATEST<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:08.928</td>
<td>/opt/python/bagit.py:629: SyntaxWarning: &quot;is not&quot; with a literal. Did you mean &quot;!=&quot;?<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:08.928</td>
<td>if not manifest_filename.find(&quot;tagmanifest-&quot;) is -1:<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:08.914</td>
<td>/opt/python/bdbag/bdbag_api.py:107: SyntaxWarning: &quot;is not&quot; with a literal. Did you mean &quot;!=&quot;?<br/></td>
</tr>
<tr>
<td>2022-03-23 23:25:08.914</td>
<td>if not manifest.find(&quot;tagmanifest-&quot;) is -1:<br/></td>
</tr>
</tbody></table>

**Comment by hannes-ucsc** [comment]
@theathorn stated during stand-up that he can't reproduce this. I'm pretty sure that's because the manifest object was successfully created, it just couldn't be tagged with the content-disposition file name. That's what the logs indicate. I've deleted the manifest just now, so it should be reproducible again. @theathorn could you check?

We need to determine what the invalid tag value actually is by logging it before we attempt to tag the object. That's the first PR. Once the PR lands in prod, we'll attempt to reproduce, extract the logs, and reconvene for next steps.

**Comment by theathorn** [comment]
Cannot reproduce.

**Comment by hannes-ucsc** [comment]
@achave11 may have correlated the wrong execution. It's possible that someone else got exactly the same error with a slightly different filter or set of files and that the logs posted above correlate to that other incident of this issue. I found another untagged manifest object and deleted it and was able to reproduce:

![image](https://user-images.githubusercontent.com/5143256/160025764-3162fe3d-d5a1-4251-8bff-d2f5625b1b38.png)

The fetch link to the manifest is https://service.azul.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMTBlNDQ3YTctNDJmNi00M2FiLWFjMzUtOGRjNzczNzU4NTBkIiwgInJlcXVlc3RfaW5kZXgiOiAzLCAid2FpdF90aW1lIjogNH0%3D

**Comment by melainalegaspi** [comment]
@danielsotirhos to file first the PR as described in @hannes-ucsc's original comment. PR needs to be labeled `partial`.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce. Might have to delete the cached manifest, first.

**Comment by danielsotirhos** [comment]
**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-indexer-prod, /aws/lambda/azul-indexer-prod-aggregate, /aws/lambda/azul-indexer-prod-aggregate_retry, /aws/lambda/azul-indexer-prod-contribute, /aws/lambda/azul-indexer-prod-contribute_retry, /aws/lambda/azul-service-prod, /aws/lambda/azul-service-prod-manifest  
start-time: -10800s  
end-time: 0s  
query-string:
```
fields @timestamp, @message
# | filter @message like 'BigQuery job error during'
# |filter @message not like 'Forbidden'
| filter @message like 'Tagging object'
| sort @timestamp desc
| limit 20
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|       @timestamp        |                                                                                                                                                                                              @message                                                                                                                                                                                               |
|-------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2022-04-12 21:33:53.290 | [INFO] 2022-04-12T21:33:53.290Z azul.service.storage_service 00010ca1-b0ba-466f-8c58-dabbad000000 Tagging object 'manifests/9c78a9a1-8ce8-5294-bdd6-dd2d6678b80e.ef1411d7-c135-57e3-8d6d-5b924bc6cdbf.tsv' with {'TagSet': [{'Key': 'azul_file_name', 'Value': 'Genomic, epigenomic, and biophysical cues controlling the emergence of the lung alveolus 2022-04-12 21.33.tsv'}]}                   |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by melainalegaspi** [comment]
@danielsotirhos to find out with confidence if commas are allowed in tag values on S3 objects. 
@danielsotirhos to inspect the TDR snapshot to see if there are other weird unicode characters in the project.JSON for this project.

**Comment by danielsotirhos** [comment]
Issue reproduced on `dev` with https://dev.singlecell.gi.ucsc.edu/explore/projects/a9c022b4-c771-4468-b769-cabcf9738de3

Field | Value
-- | --
@ingestionTime | 1649875980041
@log | 122796619775:/aws/lambda/azul-service-dev-manifest
@logStream | 2022/04/13/[$LATEST]f13e72b2b3be4be78a84f574989bfaaf
@message | [INFO] 2022-04-13T18:52:51.421Z 00010ca1-b0ba-466f-8c58-dabbad000000 azul.service.storage_service Tagging object 'manifests/09b8ca54-a897-512d-9693-6896b268f0e8.5c957295-df8a-548b-9dd0-f75082d9816d.tsv' with {'TagSet': [{'Key': 'azul_file_name', 'Value': 'Drop-seq, DroNc-seq, Fluidigm C1 Comparison 2022-04-13 18.52.tsv'}]}
@requestId | 00010ca1-b0ba-466f-8c58-dabbad000000
@timestamp | 1649875971421
TagSet.0.Key | azul_file_name
TagSet.0.Value | Drop-seq, DroNc-seq, Fluidigm C1 Comparison 2022-04-13 18.52.tsv

**Comment by danielsotirhos** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/API/API_control_S3Tag.html

```
Pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
```
Regex deconstructed:
- any kind of letter from any language
- any kind of whitespace or invisible separator
- any kind of numeric character in any script
- underscore
- dot (period)
- colon
- forward-slash
- equals
- plus
- minus (dash)
- at symbol

**Comment by hannes-ucsc** [comment]
That is nuts, but OK. Let's just base64 encode the value using the URL-safe version of Base64 (with dash and underscore).

**Comment by hannes-ucsc** [comment]
I triaged this on the fly and assigned you @danielsotirhos.
