### ISSUE TITLE
IT assertion for snapshot listing with `unreg` SA conflates 401 and 500

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4086]
```diff
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision fe1d2842e42040c36c69a0e88e5a1ab1702cf8dd)
+++ b/test/integration_test.py	(date 1649876494501)
@@ -212,6 +212,7 @@
                          f'The "unregistered" service account ({email!r}) has '
                          f'been registered')
         # The unregistered service account should not have access to any sources
+        # FIXME should be more specific, looking for the 401 case
         self.assertRaises(RequirementError, tdr.snapshot_names_by_id)
         return tdr
 ```

_Originally posted by @noah-aviel-dove in https://github.com/DataBiosphere/azul/issues/4083#issuecomment-1098392624_

**Comment by noah-aviel-dove** [comment]
Adding blocker because the assertion is currently disabled.

**Comment by noah-aviel-dove** [comment]
User credentials with insufficient generate the 401 case by raising a `UnauthorizedError`. Service accounts, registered or otherwise, never do this: they always raise a `RequirementError` which generates the 500 case.

We do need to distinguish the insufficient access case (which is expected/required) from other causes of 500 errors, but I think the ticket needs to be retitled.

**Comment by noah-aviel-dove** [comment]
I misinterpreted the status codes referenced in the title as referring to those returned by Azul rather than TDR. The current title is valid.
