### ISSUE TITLE
Estimate work for Year 5 of AnVIL grant

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4109]
From Tim's email:
I mentioned to Hannes - it would be nice to have a ballpark FTE "budget" for year 5 of anvil (from July 1st '22 to June 30th, '23) for the backend work around Azul (assume the front end is Clever canary and a different number we can add on).   I suppose this is really for only half a year (until Dec 1st), but from a budget perspective it doesn't totally matter - we are asking for the $s to get the resources allocated.  I also see that eventually we will have capacity issues on the team if we don't hire more.  

Anyway - ballpark do we think we can do those 6 months with 2, 3 or 4 FTEs on the project to produce something by December?

**Comment by hannes-ucsc** [comment]
1 FTE is defined as one employee working full-time for one year. The estimates on the ZenHub issues are in story points (SP) i.e. which we define as BP4 hours (one person classified as BP-4 working for one hour). Depending on the person assigned a task, the actual amount of time will be higher than the estimate if the assignee is a BP-2 or 3, and due to extra time spent by lead for giving direction and assistance. We stopped measuring actual sprint velocity but based on prior experience, a reasonable factor to extrapolate from story points (SP) to FTE is: FTE = SP / (8 * 5 * 4 * 12) * 2. 8 hours per day, 5 days per work week, for weeks in a month, 12 months in a year, factor 2 to account for team velocity.

For the estimation, I'll be assuming the following deliverables and a December 1st deadline:

- development and production instances of Azul and Data Browser, dedicated to AnVIL

- complete technical implementation of FedRAMP (I don't have enough visibility
  to estimate the documentation effort since that's been outsourced to a large
  degree, but based on prior workload we need to account for 25% of Daniel and
  me until the documentation is done) So that's 2 * 0.25 FTE for six months i.e., 0.25 FTE for documentation)

- complete implementation of access controls based on the TDR snapshots
  accessible to the current user

- a verbatim and/or by-reference hand-over of virtual cohorts to Terra

Not included in this estimate are

- more refined UI flows for users to apply for access

- any remedies to the fact that Azul heavily relies on AWS

There is also tension between what BI calls the *searchability subset* and
the set of entities and entity properties that Azul indexes and exposes to the
Data Browser. Depending on that, there may be significant work needed on the
Data Browser (adding or removing tabs/facets/filters) and that work might need
to be done on a fork, with the usual caveats (easy to do, hard to maintain). I
will not be estimating that work here. Once we settle on a compromise regarding
the *searchability subset* vs Azul index tension, CC can proceed to
estimate their work.

I've created the AnVIL 12/2022 release and ticketed out the big work items. Not all compliance tickets are accurately estimated.

So far that release has 1500 story points (BP-4 hours) which is equivalent to 1.5625 FTEs. Plus .25 FTE for compliance documentation (see above) gives 1.8125 FTE. To squeeze the work into six months we would need 3.625 people. Only to work on compliance and AnVIL, no HCA. The biggest uncertainties are the team velocity and the yet to be estimated compliance tickets.
