### ISSUE TITLE
IT fails due to AssertionError when running `catalog_complete` subtest

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4134]
IT in GitLab `prod` failed https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/19775 due to an AssertionError, this failure might be transient.
```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [catalog_complete] (catalog='dcp15-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 359, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 872, in _assert_catalog_complete
    hits = self._get_entities(catalog, entity_type)
  File "/builds/ucsc/azul/test/integration_test.py", line 919, in _get_entities
    body = self._get_url_json(url)
  File "/builds/ucsc/azul/test/integration_test.py", line 574, in _get_url_json
    return json.loads(self._get_url_content(url))
  File "/builds/ucsc/azul/test/integration_test.py", line 577, in _get_url_content
    return self._get_url(url).data
  File "/builds/ucsc/azul/test/integration_test.py", line 591, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 615, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (500, 'Internal Server Error', b'Traceback (most recent call last):\n  File "/opt/python/urllib3/connectionpool.py", line 445, in _make_request\n    six.raise_from(e, None)\n  File "<string>", line 3, in raise_from\n  File "/opt/python/urllib3/connectionpool.py", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File "/var/lang/lib/python3.8/http/client.py", line 1348, in getresponse\n    response.begin()\n  File "/var/lang/lib/python3.8/http/client.py", line 316, in begin\n    version, status, reason = self._read_status()\n  File "/var/lang/lib/python3.8/http/client.py", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/var/lang/lib/python3.8/socket.py", line 669, in readinto\n    return self._sock.recv_into(b)\n  File "/var/lang/lib/python3.8/ssl.py", line 1241, in recv_into\n    return self.read(nbytes, buffer)\n  File "/var/lang/lib/python3.8/ssl.py", line 1099, in read\n    return self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response\n    response = view_functi')
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [catalog_complete] (catalog='dcp1-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 359, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 872, in _assert_catalog_complete
    hits = self._get_entities(catalog, entity_type)
  File "/builds/ucsc/azul/test/integration_test.py", line 919, in _get_entities
    body = self._get_url_json(url)
  File "/builds/ucsc/azul/test/integration_test.py", line 574, in _get_url_json
    return json.loads(self._get_url_content(url))
  File "/builds/ucsc/azul/test/integration_test.py", line 577, in _get_url_content
    return self._get_url(url).data
  File "/builds/ucsc/azul/test/integration_test.py", line 591, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 615, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (500, 'Internal Server Error', b'Traceback (most recent call last):\n  File "/opt/python/urllib3/connectionpool.py", line 445, in _make_request\n    six.raise_from(e, None)\n  File "<string>", line 3, in raise_from\n  File "/opt/python/urllib3/connectionpool.py", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File "/var/lang/lib/python3.8/http/client.py", line 1348, in getresponse\n    response.begin()\n  File "/var/lang/lib/python3.8/http/client.py", line 316, in begin\n    version, status, reason = self._read_status()\n  File "/var/lang/lib/python3.8/http/client.py", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/var/lang/lib/python3.8/socket.py", line 669, in readinto\n    return self._sock.recv_into(b)\n  File "/var/lang/lib/python3.8/ssl.py", line 1241, in recv_into\n    return self.read(nbytes, buffer)\n  File "/var/lang/lib/python3.8/ssl.py", line 1099, in read\n    return self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response\n    response = view_functi')
----------------------------------------------------------------------
```

**Comment by noah-aviel-dove** [comment]
Looks like the same underlying cause as the previous failure (https://github.com/DataBiosphere/azul/issues/4133), except this time the exception is being raised within the lambda instead of the test code. Here is the truncated stack trace from the 500 response with some more readable formatting:

```
Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/python/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/var/lang/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/var/lang/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/var/lang/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/var/lang/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/var/lang/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/var/lang/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_functi
```

**Comment by achave11** [comment]
As @noah-aviel-dove had advice, this seems to be caused by a transient `ReadTimeoutError`, which has been identified already in #4133.
<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">@timestamp</th>
<th title="Field #2">@message</th>
</tr></thead>
<tbody><tr>
<td>2022-04-22 00:48:48.208</td>
<td>END RequestId: 970cccb6-c921-4bc4-84fd-802ff874c2a7<br/></td>
</tr>
<tr>
<td>2022-04-22 00:48:48.208</td>
<td>REPORT RequestId: 970cccb6-c921-4bc4-84fd-802ff874c2a7	Duration: 5045.06 ms	Billed Duration: 5046 ms	Memory Size: 2048 MB	Max Memory Used: 204 MB	<br/></td>
</tr>
<tr>
<td>2022-04-22 00:48:48.207</td>
<td>[DEBUG]	2022-04-22T00:48:48.207Z	970cccb6-c921-4bc4-84fd-802ff874c2a7	azul.chalice	Returning 500 response with headers {&quot;Content-Type&quot;: &quot;text/plain&quot;, &quot;Access-Control-Allow-Origin&quot;: &quot;*&quot;, &quot;Access-Control-Allow-Headers&quot;: &quot;Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key&quot;}. See next line for the first 1024 characters of the body.<br/>Traceback (most recent call last):<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 445, in _make_request<br/>    six.raise_from(e, None)<br/>  File &quot;&lt;string&gt;&quot;, line 3, in raise_from<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 440, in _make_request<br/>    httplib_response = conn.getresponse()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 1348, in getresponse<br/>    response.begin()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 316, in begin<br/>    version, status, reason = self._read_status()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 277, in _read_status<br/>    line = str(self.fp.readline(_MAXLINE + 1), &quot;iso-8859-1&quot;)<br/>  File &quot;/var/lang/lib/python3.8/socket.py&quot;, line 669, in readinto<br/>    return self._sock.recv_into(b)<br/>  File &quot;/var/lang/lib/python3.8/ssl.py&quot;, line 1241, in recv_into<br/>    return self.read(nbytes, buffer)<br/>  File &quot;/var/lang/lib/python3.8/ssl.py&quot;, line 1099, in read<br/>    return self._sslobj.read(len, buffer)<br/>socket.timeout: The read operation timed out<br/><br/>During handling of the abov</td>
</tr>
<tr>
<td>2022-04-22 00:48:48.206</td>
<td>[ERROR]	2022-04-22T00:48:48.205Z	970cccb6-c921-4bc4-84fd-802ff874c2a7	azul-service-prod	Caught exception for path /index/files<br/>Traceback (most recent call last):<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 445, in _make_request<br/>    six.raise_from(e, None)<br/>  File &quot;&lt;string&gt;&quot;, line 3, in raise_from<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 440, in _make_request<br/>    httplib_response = conn.getresponse()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 1348, in getresponse<br/>    response.begin()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 316, in begin<br/>    version, status, reason = self._read_status()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 277, in _read_status<br/>    line = str(self.fp.readline(_MAXLINE + 1), &quot;iso-8859-1&quot;)<br/>  File &quot;/var/lang/lib/python3.8/socket.py&quot;, line 669, in readinto<br/>    return self._sock.recv_into(b)<br/>  File &quot;/var/lang/lib/python3.8/ssl.py&quot;, line 1241, in recv_into<br/>    return self.read(nbytes, buffer)<br/>  File &quot;/var/lang/lib/python3.8/ssl.py&quot;, line 1099, in read<br/>    return self._sslobj.read(len, buffer)<br/>socket.timeout: The read operation timed out<br/><br/>During handling of the above exception, another exception occurred:<br/><br/>Traceback (most recent call last):<br/>  File &quot;/var/task/chalice/app.py&quot;, line 1705, in _get_view_function_response<br/>    response = view_function(**function_args)<br/>  File &quot;/var/task/app.py&quot;, line 1319, in get_data<br/>    return repository_search(&#39;files&#39;, file_id)<br/>  File &quot;/var/task/app.py&quot;, line 1074, in repository_search<br/>    return app.repository_controller.search(catalog=app.catalog,<br/>  File &quot;/var/task/azul/service/repository_controller.py&quot;, line 79, in search<br/>    filters = self.get_filters(catalog, authentication, filters)<br/>  File &quot;/var/task/azul/service/source_controller.py&quot;, line 61, in get_filters<br/>    source_ids=self._list_source_ids(catalog, authentication))<br/>  File &quot;/var/task/azul/service/source_controller.py&quot;, line 52, in _list_source_ids<br/>    sources = self.list_sources(catalog, authentication)<br/>  File &quot;/var/task/azul/service/source_controller.py&quot;, line 40, in list_sources<br/>    sources = self._source_service.list_sources(catalog, authentication)<br/>  File &quot;/var/task/azul/service/source_service.py&quot;, line 74, in list_sources<br/>    sources = list(plugin.list_sources(authentication))<br/>  File &quot;/var/task/azul/plugins/repository/tdr/__init__.py&quot;, line 203, in list_sources<br/>    snapshots = tdr.snapshot_names_by_id()<br/>  File &quot;/var/task/azul/terra.py&quot;, line 517, in snapshot_names_by_id<br/>    response = self._request(&#39;GET&#39;, endpoint, fields={<br/>  File &quot;/var/task/azul/terra.py&quot;, line 299, in _request<br/>    response = self._http_client.request(method,<br/>  File &quot;/opt/python/urllib3/request.py&quot;, line 74, in request<br/>    return self.request_encode_url(<br/>  File &quot;/opt/python/urllib3/request.py&quot;, line 96, in request_encode_url<br/>    return self.urlopen(method, url, **extra_kw)<br/>  File &quot;/opt/python/google/auth/transport/urllib3.py&quot;, line 388, in urlopen<br/>    response = self.http.urlopen(<br/>  File &quot;/opt/python/urllib3/poolmanager.py&quot;, line 375, in urlopen<br/>    response = conn.urlopen(method, u.request_uri, **kw)<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 755, in urlopen<br/>    retries = retries.increment(<br/>  File &quot;/opt/python/urllib3/util/retry.py&quot;, line 507, in increment<br/>    raise six.reraise(type(error), error, _stacktrace)<br/>  File &quot;/opt/python/urllib3/packages/six.py&quot;, line 770, in reraise<br/>    raise value<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 699, in urlopen<br/>    httplib_response = self._make_request(<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 447, in _make_request<br/>    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 336, in _raise_timeout<br/>    raise ReadTimeoutError(<br/>urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host=&#39;data.terra.bio&#39;, port=443): Read timed out. (read timeout=5.0)</td>
</tr>
<tr>
<td>2022-04-22 00:48:43.184</td>
<td>[DEBUG]	2022-04-22T00:48:43.184Z	970cccb6-c921-4bc4-84fd-802ff874c2a7	azul.terra	_request(&#39;GET&#39;, &#39;https://data.terra.bio/api/repository/v1/snapshots&#39;, fields={&#39;offset&#39;: 0, &#39;limit&#39;: 200, &#39;sort&#39;: &#39;created_date&#39;, &#39;direction&#39;: &#39;asc&#39;}, headers=None, timeout=None, body=5.0)</td>
</tr>
<tr>
<td>2022-04-22 00:48:43.174</td>
<td>[INFO]	2022-04-22T00:48:43.164Z	970cccb6-c921-4bc4-84fd-802ff874c2a7	azul.chalice	Received GET request for &#39;/index/files&#39;, with query {&quot;catalog&quot;: &quot;dcp1-it&quot;, &quot;filters&quot;: &quot;{}&quot;, &quot;size&quot;: &quot;100&quot;} and headers {&quot;accept-encoding&quot;: &quot;identity&quot;, &quot;authorization&quot;: &quot;Bearer REDACTED&quot;, &quot;cloudfront-forwarded-proto&quot;: &quot;https&quot;, &quot;cloudfront-is-desktop-viewer&quot;: &quot;true&quot;, &quot;cloudfront-is-mobile-viewer&quot;: &quot;false&quot;, &quot;cloudfront-is-smarttv-viewer&quot;: &quot;false&quot;, &quot;cloudfront-is-tablet-viewer&quot;: &quot;false&quot;, &quot;cloudfront-viewer-country&quot;: &quot;US&quot;, &quot;host&quot;: &quot;service.azul.data.humancellatlas.org&quot;, &quot;user-agent&quot;: &quot;python-urllib3/1.26.5&quot;, &quot;via&quot;: &quot;1.1 7a887c7cb9fe4a7abca02d85e8b196e8.cloudfront.net (CloudFront)&quot;, &quot;x-amz-cf-id&quot;: &quot;8gwCqwUQgNaVznMdKn74Ofm9kMvs7v3gOOPaVm58HOGBVF4TZBAJ4Q==&quot;, &quot;x-amzn-trace-id&quot;: &quot;Root=1-6261fb6b-68040fac51ff2fbb0cb9a839&quot;, &quot;x-forwarded-for&quot;: &quot;52.3.190.111, 130.176.179.81&quot;, &quot;x-forwarded-port&quot;: &quot;443&quot;, &quot;x-forwarded-proto&quot;: &quot;https&quot;}.</td>
</tr>
<tr>
<td>2022-04-22 00:48:43.174</td>
<td>[INFO]	2022-04-22T00:48:43.164Z	970cccb6-c921-4bc4-84fd-802ff874c2a7	azul.chalice	Authenticated request as OAuth2(REDACTED)</td>
</tr>
<tr>
<td>2022-04-22 00:48:43.160</td>
<td>START RequestId: 970cccb6-c921-4bc4-84fd-802ff874c2a7 Version: $LATEST<br/></td>
</tr>
</tbody></table>

**Comment by achave11** [comment]
This happened while running `sandbox` IT https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/44298

**Comment by achave11** [comment]
Happened again during prod promotion's IT https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/20068

**Comment by hannes-ucsc** [comment]
Noting times for Terra team: 

2022-04-27 23:57:20,209 INFO    MainThread: ... -> 500
2022-04-27 23:57:25,291 INFO    MainThread: ... -> 500
2022-04-27 23:57:30,360 INFO    MainThread: ... -> 500

**Comment by hannes-ucsc** [comment]
Created https://github.com/DataBiosphere/azul/issues/4152 to improve UX.

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/44636

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/44637

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45494

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/46817

**Comment by hannes-ucsc** [comment]
No recurrences since then.
