### ISSUE TITLE
Maintain a version number for the API

### ISSUE THREAD

**Issue by mtmorgan** [DataBiosphere/azul#4332]
I believe that the API / documentation available at https://service.azul.data.humancellatlas.org/# was updated yesterday, breaking the Bioconductor [hca](https://bioconductor.org/packages/hca) package.

Two requests in light of this

- [x] increment the /info/version of the API on change. The /version endpoint is too fine-grained for clients using the API.
- [x] Add an endpoint that lists the fields available as filters. Currently the hca package scrapes them from https://service.azul.data.humancellatlas.org/#/Index/get_index__entity_type_.

Edit by @hannes-ucsc:

https://github.com/DataBiosphere/azul/issues/4332#issuecomment-1192983652

**Comment by hannes-ucsc** [comment]
The `/openapi` endpoint exposes the filter fields and their schema directly without the need for scraping

```
$ curl -s https://service.azul.data.humancellatlas.org/openapi | jq '
> .paths["/index/{entity_type}"]
> .get.parameters[]
> |select(.name=="filters")
> .content["application/json"]
> .schema
> .properties
> |keys
> '
[
  "accessions",
  "aggregateLastModifiedDate",
  "aggregateSubmissionDate",
  "aggregateUpdateDate",
  "assayType",
  "biologicalSex",
  "bundleUuid",
  "bundleVersion",
  "cellCount",
  "cellLineType",
  "contactName",
  "contentDescription",
  "developmentStage",
  "donorCount",
  "donorDisease",
  "effectiveCellCount",
  "effectiveOrgan",
  "entryId",
  "fileFormat",
  "fileId",
  "fileName",
  "fileSize",
  "fileSource",
  "fileVersion",
  "genusSpecies",
  "institution",
  "instrumentManufacturerModel",
  "isIntermediate",
  "laboratory",
  "lastModifiedDate",
  "libraryConstructionApproach",
  "matrixCellCount",
  "modelOrgan",
  "modelOrganPart",
  "nucleicAcidSource",
  "organ",
  "organPart",
  "organismAge",
  "organismAgeRange",
  "organismAgeUnit",
  "pairedEnd",
  "preservationMethod",
  "project",
  "projectDescription",
  "projectEstimatedCellCount",
  "projectId",
  "projectTitle",
  "publicationTitle",
  "sampleDisease",
  "sampleEntityType",
  "sampleId",
  "selectedCellType",
  "sourceId",
  "sourceSpec",
  "specimenDisease",
  "specimenOrgan",
  "specimenOrganPart",
  "submissionDate",
  "updateDate",
  "workflow"
]
```

Currently the individual filter schemata for each field are overly general (not every field supports every relation as the current schemata claim) and we'll deploy a fix for that next week.

That same endpoint also exposes the version which we will maintain properly going forward:

```
$ curl -s https://service.azul.data.humancellatlas.org/openapi | jq '.info.version'
"1.0"
```

**Comment by mtmorgan** [comment]
Yes, that is where the hca package retrieves information from. I believe previously the location was under the path `/index/projects`. Maybe 'scraping' was the wrong word choice; the location under `/index/projects` seemed arbitrary (because the filters can be applied over other entity types).

Is there a 'release candidate' or something that one can track to anticipate forthcoming changes?

**Comment by hannes-ucsc** [comment]
You wrote 

> Currently the hca package scrapes them from https://service.azul.data.humancellatlas.org/#/Index/get_index__entity_type_.

which I interpreted to mean that the `hca` package currently obtains the list of fields from the Swagger UI, since that's the page you are referencing there. That's why I recommended above that the `hca` package obtains the fields directly from the `/openapi` endpoint instead. 

With the change that was deployed to production this week, which combines the entity type-specific routes (`/index/projects`, `/index/samples` and so on) into one generic `/index/{entity_type}` route, you won't have to arbitrarily pick an entity type anymore when you're obtaining the filterable fields. So I believe this addresses

> Add an endpoint that lists the fields available as filters

With respect to

> Is there a 'release candidate' or something that one can track to anticipate forthcoming changes?

Yes, https://service.dev.singlecell.gi.ucsc.edu/

It's typically one week ahead of production.

You can also monitor issues with the `API` label:

https://github.com/DataBiosphere/azul/issues?q=is%3Aopen+is%3Aissue+label%3AAPI

**Comment by melainalegaspi** [comment]
@hannes-ucsc to create follow on ticket.

**Comment by hannes-ucsc** [comment]
The 2nd of the issue author's suggestions is already [implemented](https://github.com/DataBiosphere/azul/issues/4332#issuecomment-1192755725) so I'll hijack this ticket for the remaining work: we need to have PR checklist item that reminds us to consider whether a change modifies the API in a manner that might break or adversely affect client code. If it does, we need to 

- bump the API version number https://github.com/DataBiosphere/azul/blob/4c22bf35477033125c89d813086fd952b262ce23/lambdas/service/app.py#L223 (the version should also precede the description so that it is more prominent)

- label the connected issue(s) with `API`

- tag the commit title with `a` (the tag should be documented in CONTRIBUTING.rst)

**Comment by hannes-ucsc** [comment]
We have the PR checklist item now for labeling the PR but not one for bumping the version number and the commit title tag.
