### ISSUE TITLE
Index AnVIL CMG snapshots

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#4342]

**Comment by hannes-ucsc** [comment]
For demo, show that the number of files in the `anvil` catalog of the `anvildev` deployment matches the number of files in those catalogs. Show that direct downloads and `curl` manifests work. If a Data Browser deployment fronting `anvildev` is available, use that for the download and manifest interactions, otherwise use the Swagger UI or `curl`.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"We moved the file count match requirement to #4599. Postponing demo until we get to that ticket."
