### ISSUE TITLE
Index CMG snapshots into personal AnVIL deployment

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4355]
- `ANVIL_CMG_UWASH_GRU_202208021157`
- `ANVIL_CMG_UWASH_DS_BAV_IRB_PUB_RD_202208021204`
- `ANVIL_CMG_UWASH_HMB_IRB_202208021207`

Rows 6-8 of [ANVIL tab in TDR Datasets and snapshots](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274).

Note: Snapshots may contain some orphaned files.

**Comment by theathorn** [comment]
Spike to review snapshots and decide which changes are needed to accommodate them.

**Comment by hannes-ucsc** [comment]
These snapshots don't have a `library` table so we need to pick another type of entity to define bundles. We should try `biosample` first. I'm undecided if we should switch ENCODE to `biosample`, too, or if we should add the necessary conditionals  so that ENCODE uses `library` while all other snapshots use `biosample`. Either way, we should first try indexing only the CMG snapshots (drop the ENCODE snapshot) to determine if using `biosample` works for the CMG snapshots. We'll add ENCODE back as part of #4367.

For ENCODE we used columns that are not in the "findability subset". It's possible that we now have to remove these columns from the queries to make them work for the CMG snapshots. Record the removed columns here. I asked Nate to populate all tables, even empty ones, and to create all FK columns, even those referring to empty tables. In other words, we should not need to remove any JOINs from the queries. Alert Trevor and me if that's not the case.

The workarounds for the missing dataset table and the dangling foreign keys should be removed. If there are still dangling foreign keys, we'll pause work on this, ask for new snapshots, and resume when those are available.

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "This was demoed to the Broad in one of the PM meetings in August."
