### ISSUE TITLE
Consider increasing page size for TDR's enumerateSnapshots request

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4382]
Currently there are approximately 450 public snapshots in `prod` requiring four round trips. See if we can use 500.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "I want to think a little more about ways to also avoid making that last request for an empty page. I will provide design then."

**Comment by hannes-ucsc** [comment]
I though the empty sentinel page was a defense against concurrent changes to the set of snapshots being paged through. That is not the case. There is a ticket open for that: #3979. Since time is of the essence in most situations, we want to minimize the number of TDR requests. One commit should eliminate the need for the last sentinel page, another commit should bump the page size to 500. This should essentially get us down to one TDR request.

**Comment by hannes-ucsc** [comment]
Spike to confirm if we can use 500.

**Comment by theathorn** [comment]
Changed to 1000 as part of #4659.
