### ISSUE TITLE
Revoke Clever Canary certs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4395]
https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1660938467433149?thread_ts=1660927749.110979&cid=C705Y6G9Z

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Considering the fact that we'll have to provision access for less technical people at the Broad, we will relax the security requirements so that I will be permitted to know the private keys of certain users I've provided access to the VPN for. Closing as obsolete. Clver Canary can hold onto their certificates."
