### ISSUE TITLE
Human Subjects Research Training

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4405]
Complete [CITI Training for Human Subjects](https://docs.google.com/document/d/18_UoOkT84AlbMrovhnV93aNjjlsv7SAkw3InZdmUeQc/edit#heading=h.pl536sghgugk) as per UCSC Office of Research [HSR Training Requirements](https://officeofresearch.ucsc.edu/compliance/services/irb06.03_apply_training.html)

According to @noah-aviel-dove's [certification](https://drive.google.com/drive/folders/12u4urNgnah03XuIADYVUoMUvDE8Zemdu) (citiCompletionCert.pdf) and Julian Lucas's [certification](https://drive.google.com/file/d/1YEogiBJ53F7hNSoCvFnWOuEtT08CuDqg/view), they both completed:

CITI Human Subjects Research (Curriculum Group)
Group 2: Human Subjects Researchers-Biomedical (Course Learner Group)
1 - Basic Course (Stage)

**Comment by achave11** [comment]
The [citiCompletionCert.pdf](https://drive.google.com/drive/u/0/folders/1M9Yef9ijlHNGXhHx87V17Fz18Cok1ky1) has been uploaded to my staff folder in Google Drive. However, the subsequent [step](https://docs.google.com/document/d/18_UoOkT84AlbMrovhnV93aNjjlsv7SAkw3InZdmUeQc/edit#heading=h.pl536sghgugk) `Email certificate to Rochelle Fuller` was not delivered due to `hrfuller@ucsc.edu` being a deactivated email.

**Comment by theathorn** [comment]
I have [notified](https://ucsc-gi.slack.com/archives/C02B4S0V6GH/p1662664127976369) @nolunwa to update the contact information  in the "[Security Training and Awareness Appendix 1](https://docs.google.com/document/d/18_UoOkT84AlbMrovhnV93aNjjlsv7SAkw3InZdmUeQc)" document.
