### ISSUE TITLE
Add antibody to AnVIL index

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4440]
Add an outer and inner entity type called `antibody` using the table of the same name.  Index that table's `target` column into a property of the same name in inner and outer entities of type `antibody`. Discover rows in that table by traversing the relation from the `assayactivity` table.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to define details.

**Comment by hannes-ucsc** [comment]
This can be deprioritized since there currently is no snapshot in the corpus in which that table is not empty. Supposedly the upcoming ENCODE snapshot has a non-empty `antibody` table. Once we have that snapshot we can look into this. We need to also understand the cardinality of the `target` column in order to decide if we'll include it as a property of inner entities, and make it a facet.

**Comment by hannes-ucsc** [comment]
Spike to confirm that the antibody table is either empty or absent from all of the snapshots currently on the spreadsheet. If confirmed, we'll park this ticket with a request to be notified by the Broad when a snapshot is added that does have a non-empty antibody table.

**Comment by nadove-ucsc** [comment]
The antibody table is present but empty for every snapshot currently on the spreadsheet (rows 3-83).

**Comment by achave11-ucsc** [comment]
@bvizzier-ucsc to confirm point person at the Broad.

**Comment by bvizzier-ucsc** [comment]
Check with Nate Calvanese.

**Comment by achave11-ucsc** [comment]
Noa asked Nate here: https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1691022243067239

**Comment by hannes-ucsc** [comment]
No response. We have too much else to do.
