### ISSUE TITLE
Dissolve `Clever Canary` team into parent `Azul Triagers`

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4444]

**Comment by hannes-ucsc** [comment]
Deleted team and inlined its members in the Azul Triagers team (formerly known as Azul Managers).

**Comment by hannes-ucsc** [comment]
Also added Azul Triagers, Azul Developers, Azul Admins and Azul Operators to the DataBiosphere/data-portal and DataBiosphere/data-browser repos where the Clever Canary team was listed explicitly.

Quirk: Azul Triagers as write access to the repos (because ZenHub doesn't have triage, only read or write). If Azul Triagers gets "triage" instead of "write" the Clever Canary people will lose write access to these two repos. At that point we need to make them Azul Developers.
