### ISSUE TITLE
S3 Block Public Access setting should be enabled

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4713]
```
{
    "GeneratorIds": [
        "aws-foundational-security-best-practices/v/1.0.0/S3.1"
    ]
}
```

https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html#s3-1

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
I thought we already addressed this. Assignee to spike to check finding again in all accounts.

**Comment by hannes-ucsc** [comment]
Assignee [reports](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1677632493551859?thread_ts=1667613240.016369&cid=C705Y6G9Z) that all buckets have the right settings but that we additionally need to make an account-level change.

**Comment by achave11-ucsc** [comment]
In `platform-hca-dev` the following buckets need to enable the public access setting:

- `data-browser.dev.lungmap.net`
- `dev.archive-preview.singlecell.gi.ucsc.edu`
- `dev.explore.lungmap.net`
- `dev.explore.singlecell.gi.ucsc.edu`
- `dev.singlecell.gi.ucsc.edu`

In `platform-anvil-dev` all buckets have the setting enabled.

In `platform-hca-prod` the following buckets need to enable the public access setting:

- `archive-preview.humancellatlas.org`
- `data-browser.explore.lungmap.net`
- `data-browser.lungmap.net`
- `org-humancellatlas-data-browser-dcp2-prod`
- `org-humancellatlas-data-portal-dcp2-prod`

In addition to each bucket having the specified setting enabled, "Block Public Access settings for account" is also required to satisfy the S3.1 security finding. This was proven yesterday, after the [setting was enabled](https://github.com/DataBiosphere/azul/pull/5013) and deployed to the `anvildev.shared` component. This has since resolved the finding as [compliant](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/aws-foundational-security-best-practices-1.0.0/S3.1) in that account.

**Comment by achave11-ucsc** [comment]
@theathorn to create blocking ticket(s) for Data Browser.

**Comment by achave11-ucsc** [comment]
We need to wait until [DB blocker](https://github.com/DataBiosphere/data-browser/issues/3143) is resolved.

**Comment by hannes-ucsc** [comment]
Blocker was resolved.

**Comment by hannes-ucsc** [comment]
For demo, show that finding is fixed in `anvildev`.
