### ISSUE TITLE
No logs in /aws/apigateway/azul-service-anvilbox

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4728]

**Comment by theathorn** [comment]
Spike to validate and diagnose.

**Comment by achave11-ucsc** [comment]
I was unable to reproduce. There are `/aws/apigateway/azul-service-anvilbox` and `/aws/apigateway/azul-indexer-anvilbox` logs available with time stamps from this past week, as well as logs preceding the date this issue was created when filtering for records from the past four weeks.
<img width="1667" alt="Screen Shot 2022-11-21 at 4 50 06 PM" src="https://user-images.githubusercontent.com/19215510/203187740-5c717aac-4154-42d0-8080-089ac1fec4c4.png">
<img width="1674" alt="Screen Shot 2022-11-21 at 4 50 38 PM" src="https://user-images.githubusercontent.com/19215510/203187747-cd2d2ccc-5a93-4a28-b31c-e0993959002a.png">


**NOTE**:
However, when looking at [APIGateway resources in the AWS console](https://us-east-1.console.aws.amazon.com/apigateway/main/apis?) the expected entries for the `anvilbox` resources were missing. This might be resolved when the [ongoing pipeline in GitLab](https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/5383) `anvibox` succeeds.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc to review spike results.
