### ISSUE TITLE
"Not authorized" error when logged into HCA dev Data Browser

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4733]
Sign in to dev Data Browser to get this error.
Sign out to get full access to all the data.
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/53524d33-4747-42dd-b9bf-4e4d04c68d35)

**Comment by theathorn** [comment]
Spike to diagnose (max 2 hrs).

**Comment by noah-aviel-dove** [comment]
Logs indicate that the user (Trevor) has not accepted Terra's terms of service according to SAM, causing a 401 response from TDR.


@ingestionTime | 1668024359854
-- | --
@log | 122796619775:/aws/lambda/azul-service-dev
@logStream | 2022/11/09/[$LATEST]9c227ce0f45b4ce4b76bb055e701eb73
@message | [DEBUG] 	2022-11-09T20:05:58.153Z	6568424e-09a5-48b1-a74c-220873e8a471	 azul.terra	_request('GET',  https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?offset=0&limit=1000&sort=created_date&direction=asc&filter=hca_dev_,  headers=None, timeout=5.0, body=None)
@requestId | 6568424e-09a5-48b1-a74c-220873e8a471
@timestamp | 1668024358153



@ingestionTime | 1668024359854
-- | --
@log | 122796619775:/aws/lambda/azul-service-dev
@logStream | 2022/11/09/[$LATEST]9c227ce0f45b4ce4b76bb055e701eb73
@message | [DEBUG] 	2022-11-09T20:05:58.489Z	6568424e-09a5-48b1-a74c-220873e8a471	 azul.terra	_request(…) -> 0.336s 401 b'{"message":"User has not  accepted the terms of service.","errorDetail":[]}'
@requestId | 6568424e-09a5-48b1-a74c-220873e8a471
@timestamp | 1668024358489
message | User has not accepted the terms of service.

We caught the exception and checked to see if Trevor was registered with SAM. Because he is registered, we re-raised the exception.

@ingestionTime | 1668024359854
-- | --
@log | 122796619775:/aws/lambda/azul-service-dev
@logStream | 2022/11/09/[$LATEST]9c227ce0f45b4ce4b76bb055e701eb73
@message | [DEBUG] 	2022-11-09T20:05:58.490Z	6568424e-09a5-48b1-a74c-220873e8a471	 azul.terra	_request('GET',  https://sam.dsde-dev.broadinstitute.org/register/user/v1, headers=None,  timeout=5.0, body=None)
@requestId | 6568424e-09a5-48b1-a74c-220873e8a471
@timestamp | 1668024358490


@ingestionTime | 1668024359854
-- | --
@log | 122796619775:/aws/lambda/azul-service-dev
@logStream | 2022/11/09/[$LATEST]9c227ce0f45b4ce4b76bb055e701eb73
@message | [DEBUG] 	2022-11-09T20:05:59.201Z	6568424e-09a5-48b1-a74c-220873e8a471	 azul.terra	_request(…) -> 0.711s 200  b'{"enabled":{"tosAccepted":false,"google":true,"ldap":true,"allUsersGroup":true,"adminEnabled":true},"userInfo":{"userEmail":"theathor@ucsc.edu","userSubjectId":"116409610201042670043"}}'
@requestId | 6568424e-09a5-48b1-a74c-220873e8a471
@timestamp | 1668024359201
enabled.adminEnabled | 1
enabled.allUsersGroup | 1
enabled.google | 1
enabled.ldap | 1
enabled.tosAccepted | 0
userInfo.userEmail | theathor@ucsc.edu
userInfo.userSubjectId | 116409610201042670043


Perhaps we need to explicitly handle the case where the user is registered but has not accepted the TOS. At the very least we should probably mention the TOS in the error message that we raise on a 401 (featured in Trevor's screenshot).

**Comment by theathorn** [comment]
Confirmed that once I accepted the Terra Terms of Service I can now login to the Data Browser and have access to all 105 projects, as expected.

**Comment by theathorn** [comment]
@hannes-ucsc :" As proposed by @noah-aviel-dove, we should enhance our error response to include the fact that the terms-of-service must be accepted. I do think that there is additional Data Browser work to check for SAM registration after login, such that we don't even get this far. It is unlikely that a regular user will be able to decipher a server error message, even if it includes the aforementioned fact."

**Comment by theathorn** [comment]
@theathorn to create Blocking Data Browser ticket.

**Comment by bvizzier-ucsc** [comment]
The Data Browser displays a warning if the user needs to accept the Terms of Service, so this is resolved.
