### ISSUE TITLE
`make clean` deletes too many files on Ubuntu

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4785]
Folders are left intact but files in `.venv/` and `deployments/*.local` are removed when running `make clean` on Ubuntu with git version `2.37.2` and bash version `5.2.2(1)-release`. This appears to be caused by `git ls-files` not reading from `/dev/stdin` when setting the `--exclude-from` parameter, due to [git closing the file after receiving a size of 0 from `fstat`](https://github.com/git/git/blob/45c9f05c44b1cb6bd2d6cb95a22cf5e3d21d5b63/dir.c#L1083).

**Comment by hannes-ucsc** [comment]
I looked a little bit more into this. It's actually a race between the two processes in the `sed … | git … /dev/stdin` pipe. If the `sed` process has already written some amount of text to the pipe when the `git` process calls `stat` on it, `git` will read that amount from the pipe (but no more). If `sed` hasn't written any text yet, `stat` will report the file to be of size zero and `git` won't even open or try to read from the pipe. This is a bug in `git`. It's bad practice to `stat` a file's size and then only read that amount. I know it's easier that way because you don't need to dynamically grow the buffer the file is being read into, but it renders the code incompatible with pipes and FIFOs, due to that race. To parse a file line by line, one doesn't even need a buffer. At the very least, `git` should explicitly refuse to read from a pipe. The type of a file is returned by the `stat` call. I might open a bug against `git`.

**Comment by hannes-ucsc** [comment]
For demo, show `make list_dirty` and `make clean` on Ubuntu. Using `git clean -Xdn`, show that there are files left that are `.gitignored` but have not been cleaned.
