### ISSUE TITLE
Create Athena tables for S3 and ALB access logs in logs bucket

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4883]
- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to fill in details.

**Comment by hannes-ucsc** [comment]
I played around with Athena a bit more today. It's relatively complicated to setup with Terraform because of the overlap with AWS Glue. Until recently creating Athena tables programmatically required CloudFormation templates:

https://stackoverflow.com/questions/64225241/create-athena-resources-with-terraform

More importantly, without partitioning, the Athena query running times would quickly exhaust our patience after just a few weeks of logs have accumulated. Furthermore, Athena table partition locations must end in a slash. This is not the case for S3 access logs where the URL look like `s3://edu-ucsc-gi-platform-anvil-dev-logs.us-east-1/s3/access/anvildev/storage/2023-01-11-00-13-37-A92A3C67633BD490`. Here we want the partition keys to be `anvildev`, `storage` and `2023-01-11` but there is no slash in the URL after `2023-01-11`.

All of this has me lean towards sticking with the original approach of forwarding the S3 and ALB access logs to CloudWatch where we can use a tried, trusted and centralized (albeit slightly more expensive) approach to querying the logs.
