### ISSUE TITLE
Add "Project Role" to Contributors in Project Detail API

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#498]
We need to remove wranglers from the Project detail page ui:

>Wranglers are indicated in the metadata by the field:value "project_role": "Human Cell Atlas wrangler" >in the project.json schema. Wrangler organization affiliations should not be included in the >"Collaborating Organizations" section.

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/c62482b9-447c-4930-a987-ca194a09eb8e)

This role does not yet exist in the contributors. 

Thanks,
D

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-326)
┆Project Name: azul
┆Issue Number: AZUL-326

**Comment by hannes-ucsc** [comment]
Implementation hint: Be sure to read the ticket this ticket is blocking. The filtering should be done in Azul and not the metadata-api, but the property on which the filtering is based might have to be added in metadata-api.

**Comment by Ben-Wu** [comment]
@hannes-ucsc Should the filtering be done on the service side or the indexer side?  At first I was thinking service so that we still store all the contributors if we need them for something else.  But we in the indexer we also create a list of all laboratories, contact names, and institutions in a project so it would be simpler to just filter everything out in the indexer.  If done in the service we would need to move the creation of the lists to the service.

i.e.: is there any need now or in the future to store HCA wranglers in ES?

**Comment by Ben-Wu** [comment]
Per our discussion we will go with doing filtering in the indexer

**Comment by NoopDog** [comment]
Why not let us filter it in the client? It could be useful to know who wrangled the data at some point. My preference would be for the role to be added to the /projects/id response for each contributor.

**Comment by Ben-Wu** [comment]
We are adding project role to the response but we can also let you filter it out.  I was thinking that we handle the logic in the backend.  One thing though is that in the response right now we also return the list of laboratories which would include the laboratories of the wranglers.  Are you using that array right now or do you just iterate through the contributors?  If we don't filter in the backend then you would need to create that list yourself but from what I can see it doesn't look like it used.
