### ISSUE TITLE
Terra pfb import fails on HCA prod with "Error importing data"

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#5045]
From Tim Tickle [Slack thread](https://humancellatlas.slack.com/archives/C015FPVADC1/p1678723240969949):

I attempted to use the Terra workspace handoff and received an error (import error in Terra after selecting the workspace).

Scenarios I ran:

Study: A Cellular Atlas of Pitx2-Dependent Cardiac Development.
Result: bdbag worked, pfb did not. (using fastq.gz 24 files)

Study: 1.3 Million Brain Cells from E18 Mice
Result: bdbag and pfb did not work for fastq (16k files)

![image](https://user-images.githubusercontent.com/38867406/224772392-cd8bd7d0-f2f3-4cd2-babe-66ab6977772e.png)

Link for the above manifest: https://app.terra.bio/#import-data?format=PFB&url=https%3A%2F%2Fservice.azul.data.humancellatlas.org%2Fmanifest%2Ffiles%3Fcatalog%3Ddcp24%26format%3Dterra.pfb%26filters%3D%257B%2522projectTitle%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522A%2BCellular%2BAtlas%2Bof%2BPitx2-Dependent%2BCardiac%2BDevelopment.%2522%255D%257D%252C%2B%2522fileFormat%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522fastq.gz%2522%255D%257D%252C%2B%2522genusSpecies%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522Mus%2Bmusculus%2522%255D%257D%257D%26objectKey%3Dmanifests%252F6b8d4f80-8d0b-5524-ba06-df5157463b87.ad738b13-97cf-556d-a2f5-be3e4b6b062c.avro

**Comment by dsotirho-ucsc** [comment]
@theathorn to see if other projects work and add screenshots for all failures.

**Comment by theathorn** [comment]
Project ProstateCellAtlas fastq.gz files import OK with bdbag, fail with pfb:
![image](https://user-images.githubusercontent.com/38867406/224825132-c299b79b-e268-405b-b6bd-2e1d83bd0aca.png)

mtx.gz files also fail with pfb:
![image](https://user-images.githubusercontent.com/38867406/224825582-7f470b2f-57f4-44a9-a790-e5f8f613975e.png)

**Comment by theathorn** [comment]
Tried filtering for just pdf files and then selected project Amulti-omicsatlasofthehumanretinaatsingle-cellresolution (4 files), which also failed pfb import:
![image](https://user-images.githubusercontent.com/38867406/224826637-5d09be86-4631-4f9d-b5ca-0128a02a6b86.png)

**Comment by theathorn** [comment]
Import of fastq.gz files for project 1M Neurons with bdbag format fails with a different type of error:
![image](https://user-images.githubusercontent.com/38867406/224827867-ba02de7b-e682-48aa-b34c-e0e40fc788c5.png)

**Comment by theathorn** [comment]
I can't get pfb import to work at all for any project or file selection.
Example: it failed for a single loom file (Human_RNA_processed.loom) for project "A human cell atlas of fetal gene expression" (bdbag import of the same file worked):
![image](https://user-images.githubusercontent.com/38867406/224830690-2e4f89e8-ada9-48a9-bef7-3dcfee4aa18c.png)

**Comment by hannes-ucsc** [comment]
I asked on Slack about this: https://humancellatlas.slack.com/archives/C018YPVKC73/p1678746644893839

**Comment by davidangb** [comment]
The issues with PFB and BDBag are separate, from my investigation.

PFB problems were caused because Terra's `import-service` was using an older version of `pypfb`. Updating to latest resolved the issue. This is now live in Terra prod, and my test imports succeeded.

The issue with BDBag not fixed in Terra prod. This issue is dataset-dependent. What I'm seeing is that in certain datasets, some rows in the TSVs inside the BDBag contain values that trip up the import. In the "1.3 Million Brain Cells from E18 Mice" dataset, for instance, the row with id `c928080f-7953-4cdb-8ef9-853212825b29.2019-05-16T211813.091000Z` has a value of `6e260905` in the column `__fastq_read1__file_crc32c`. The value of `6e260905` is being interpreted as scientific notation; within Java this becomes a `Double` of `Infinity`, and later in Terra's processing we attempt to convert this to a `BigDecimal` which doesn't support `Infinity`. We'll start on a fix for that issue.

**Comment by theathorn** [comment]
I've retested several of the pfb cases above, and they all work now.
The bdbag issue remains.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Broad reports that BDBag was also fixed. @theathorn to verify."

**Comment by theathorn** [comment]
Confirmed the bdbag hand-off is working for project "1.3 Million Brain Cells from E18 Mice" for fastq files.
