### ISSUE TITLE
Expose min and max age range on service side

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#512]
Need to make sure that min and max aggregation works as desired and that the service exposes the minimum and maximum age range fields.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-332)
┆Project Name: azul
┆Issue Number: AZUL-332

**Comment by theathorn** [comment]
@hannes-ucsc : From @NoopDog : Please combine age and age unit in the index. I started on this but don’t want to over specify it. The representation needs to support searching by one or more age ranges.

**Comment by NoopDog** [comment]
@GPelayo Thanks, can you add examples to the ticket on how this changes the API? Also is this a breaking change or just an extra field?

**Comment by GPelayo** [comment]
@NoopDog The change only exposes the age range field in the indexer, so it shouldn't be breaking change.

**Comment by GPelayo** [comment]
These `donorOrganisms. organismAgeRange` is now exposed as a double range datatype. Double range types have the subfields `gte` (greater than or equal) and `lte` (lesser than or equal) representing min and max ages, respectively. Also, the ages are only in seconds.

```
"organismAgeRange": [
        {
            "gte": 1734480000.0,
            "lte": 1860624000.0
        },
        {
            "gte": 1261440000.0,
            "lte": 1387584000.0
        }
],
```

This change also makes it possible to find documents that have number values that fall within a certain range.

For example, if you want to find entities with a `donorAgeRange` that falls between 6-14, then the filters param needs to be:
```
filters={“donorAgeRange”: {“within”: [[6, 14]]}}
```
`donorAgeRange` is the field name that is queried. 
`within` is the comparison operator (Explained in-depth below)
`[[6, 14]]` is the desired range. When querying number ranges, the value is always an array of number ranges arrays. In this case, `[[6, 14]]` means  a `donorAgeRange` between 6-14.

In the place of the `is` comparison modifier, there are also new comparison operators specifically for querying number ranges.

The `within` keyword will return results with a number range field that is within the queried range. For example, a user has `within` in their query to find donors within the age range 5-10. Then, Azul will return donors with ages between 7-8 or 6-9, since these age ranges are within the queried age range of 5-10.

The `contain` keyword is for returning results with a number range field that could contain the queried range. For example, a user has `contain` in their query to find donors containing the age range 5-10 years. Azul will then return donors with age ranges 4-11 or 1-18, since these age ranges could contain the queried age range 5-10.

The `intersect` keyword will return any donors with any age range that intersects with the queried age. Using the same examples as above, a user that has `intersect` in their query to find donors intersecting the age range 5-10 years would return both results from queries using `contains` and `within`, as well as donors with an age range 1-6 and 9-11.

**Comment by NoopDog** [comment]
Looking at the above it seems that both min and max are ranges so we have:

```
"organismAgeRange": [
        {
            "gte": 1734480000.0, - min  of the min
            "lte": 1860624000.0 - max of the min
        },
        {
            "gte": 1261440000.0, - min of the max
            "lte": 1387584000.0 - max of the max
        }
],
```

Is the above interpretation correct?
Of not  can you explain the correct interpretation?
If so, will min and max of the min ever be different in practice?

My understanding was that the age range of an donor might be given to help anonymize the data but it will be in the form more like:

```
"organismAgeRange": [
        {
            "min": 1734480000.0,
            "max": 1860624000.0
        },
],
```

And the query for multiple ranges is something like:

`filters={“donorAgeRange”: {“within”: [[10,25], [45,55]] }}`

The query above would ask for (donors that are between between the ages of 10 and 25 ) OR (donors that are between the ages of 45 and 55)

For example, to try to compare young donors with old donors and get both in a single query. 

Glad to see the ages are normalized to seconds (but I used years a above just for ease of representing the ages in a readable way for discussion)

**Comment by NoopDog** [comment]
Thinking about this a bit more. There is an additional use case to support where we sample the same donor over time. So, the "age" concept is really "the age of the donor at the time of specimen collection".

So, seem the age needs to be on the specimen and not the donor organism.

**Comment by GPelayo** [comment]
> Looking at the above it seems that both min and max are ranges so we have:
```
"organismAgeRange": [
        {
            "gte": 1734480000.0, - min  of the min
            "lte": 1860624000.0 - max of the min
        },
        {
            "gte": 1261440000.0, - min of the max
            "lte": 1387584000.0 - max of the max
        }
],
```
> Is the above interpretation correct?
> Of not can you explain the correct interpretation?
> If so, will min and max of the min ever be different in practice?

The above interpretation is not correct because the first age range is not limited to the having min of min and the max of min and second age range is not limited to having min of max and the max of max. `organismAgeRange` is only an unsorted list of age ranges and the above example should be interpreted as "the age this organism that could be anywhere between 1734480000.0 to 1860624000.0 seconds old or anywhere between 1261440000.0 to 1387584000.0 seconds old".

**Comment by NoopDog** [comment]
OK, sounds like we should discuss. I need some help understanding the intent here. 

Also, bear in mind that the key thing is that what is being modeled is the age of the organism at the time of specimen collection and that there can be multiple collection events spread over time. 

Donor_organism sounds like an "person" entity but really its a join between a person and a collection event.

**Comment by hannes-ucsc** [comment]
@NoopDog, lets discuss after stand-up tomorrow.
