### ISSUE TITLE
Use step functions to produce manifest

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#546]
The manifest endpoint has been bumping against API Gateway's 29s limit on request duration. So far we've managed to get by with various tweaks but those are not a long term solution. 

The manifest endpoint should kick off a step function execution and return a 301 redirect to itself with the execution ID encoded in an opaque token. The 301 response should also have a Retry-After header set to, say, 10s. The step function begins populating the manifest. For now the step function should have a single state in which it scans the ES results exhaustively and writes them to S3. In the future the step function could have a loop and perform a multipart upload (one per loop iteration). For that to work we would need to use `search_after` with the ES request.

```
GET /files/export 
301 Moved Permanently
Retry-After: 10
Location: /files/export?token=<base64_encoded_execution_id>
```

The client waits 10s and then requests the manifest endpoint again. The service checks if the execution is still running. Let's say it is and another self redirect is returned:

```
GET /files/export?token=<base64_encoded_execution_id>
301 Moved Permanently
Retry-After: 10
Location: /files/export?token=<base64_encoded_execution_id>
```

The client waits another 10s and then requests the manifest endpoint again. The service checks if the execution is still running. Let's say it is now done. We can assume that the manifest in S3 is now fully populated. The service returns a 302 redirect to a signed URL of the manifest in the S3 bucket.

```
GET /files/export?token=<base64_encoded_execution_id>
302 Moved Temporarily
Location: some-bucket.s3.amazon-aws.com/manifests/manifest-<UUID>.tsv
```

The token might have to include the manifest UUID as well..

We might also need to add a `&wait=1` parameter to the manifest endpoint URL. If it is set, the service sleeps 10s before returning and doesn't return a `Retry-After` header. This is for clients (like web browsers) that generally don't support `Retry-After`.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-351)
┆Project Name: azul
┆Issue Number: AZUL-351

**Comment by Ben-Wu** [comment]
Notes:
- Token parameter is a base64 encoding of the uuid of the execution from the execution arn; It would be good to make it an encoded json instead to include other information
- Input to state machine is json with filters and output is s3 url
- Check manifest creation completion by using boto3 `describe_execution`
- Use `/manifest/files` route because this change is not backwards compatible

**Comment by Ben-Wu** [comment]
If the manifest takes a very long time to generate the browser may stop redirecting and give an error.  This means if we use a 10 second timeout we are still limited to 10 seconds times however many redirects are allowed (It looks like the limit for firefox and chrome is 20 so 200 seconds).

A workaround for this is to not use the `Location` header and instead return a token as a response that the client can use to make another request.

@hannes-ucsc @shiroyuki Thoughts on this?

I also think 10 seconds per retry is too long and it should be at most 5 because a manifest typically only takes a few seconds to create and an extra 5 seconds to wait is annoying.

**Comment by hannes-ucsc** [comment]
> A workaround for this is to not use the Location header and instead return a token as a response that the client can use to make another request.

Excellent point. I think we should tweak this a little: We never return a redirect but instead return a 200 response with a JSON body that captures what would otherwise be returned as a header:

```
{
    "Status": 301,
    "Retry-After": 60,
    "Location": <complete URL to endpoint>
}
```

This has the advantage that clients don't need to worry about tokens. Instead the token is an opaque part of the `location` entry. We only need to instruct clients to obey `retry-after` and to use XHR for 301 statuses and `window.open()` for 302s. The latter is necessary to trigger the native download machinery in the browser.

We can use the exact same mechanism for the `/dss/files` proxy (https://github.com/DataBiosphere/azul/issues/551 and https://github.com/humancellatlas/data-browser/issues/354). 

> I also think 10 seconds per retry is too long and it should be at most 5 because a manifest typically only takes a few seconds to create and an extra 5 seconds to wait is annoying.

How about an exponential back-off strategy with a low exponent?

**Comment by Ben-Wu** [comment]
By `<complete URL to endpoint>` do you mean including `https://service...`?  It doesn't look like chalice has a way to get the base url.  Returning only the endpoint for 301s should be fine since the client is going to be handling the status codes differently.

Regarding the timeout, I'm not strongly opposed to exponential backoff but I'm not sure it makes sense in this case because we just want to find when the operation is done rather than retrying due to a throttling error for example.  The number of retries isn't really correlated with the amount of time left.  The lambda invocation isn't very expensive anyway.

But the other thing that I just thought of is that if we let the client handle all the timeouts we can save on lambda costs.  As it is now, using the `wait` parameter the check for manifest completion is running for the entire duration of the manifest generation.  Since the check really only takes some milliseconds we could save a lot if we return immediately.

**Comment by hannes-ucsc** [comment]
> By <complete URL to endpoint> do you mean including https://service...? It doesn't look like chalice has a way to get the base url.

That's correct but we can work around it. Take a look at how the `/dss/files` endpoint works. That  doesn't currently work with `chalice local` yet but we can figure that out later. It shouldn't be too hard to detect that we're not running in Lambda and special-case that. I want to make this as simple as possible for the client, and not requiring them to compose the URL is part of that aim.

> because we just want to find when the operation is done rather than retrying due to a throttling error for example.

I think it still makes sense. The longer an operation takes the less important it is to report its completion in a timely manner. If something takes 10min, it's acceptable to report that after 10min and 10s because that's just an inaccuracy of just 1.6%. If something takes 1 seconds it is unacceptable to report that after 10s because that is an inaccuracy of 900%. Essentially this is taking your argument for a shorter timeout, but generalizing it.

To be precise, I am proposing the following sequence of timeouts: 1s, 1s, 2s, 6s, 10s, 10s, 10s …

BTW: I prefer spelling out the sequence rather come up with a fancy equation for exponential back-off, especially when its capped and only takes a handful of iterations to hit the cap.

Cumulatively, this would mean the following sequence: 1s, 2s, 4s, 10s, 10s, …

What I want to avoid is that we'd get bogged down by many clients downloading large manifests. If a user wants to download a large manifest, it's OK to penalize them with an increased inaccuracy of the completion report, if that lowers the load on the server.

**Comment by hannes-ucsc** [comment]
Also, keep in mind that this is not just a cost savings concern. There are also limits on the request rate for the status of an step function, on the number of concurrently running lambdas. We have to be economical in the respect, too.

**Comment by Ben-Wu** [comment]
OK it looks like we can use `app.lambda_context.invoked_function_arn` to check if it's local or not.

I agree with those timeouts.  If it's capped at 10s it should be acceptable.
