### ISSUE TITLE
Alarm when WAF rate limit kicks in

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5554]
- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike for design.

**Comment by achave11-ucsc** [comment]
See also https://github.com/DataBiosphere/azul/issues/5286 PR https://github.com/DataBiosphere/azul/pull/5455

**Comment by hannes-ucsc** [comment]
We'll resolve this by enabling [WAF logging](https://docs.aws.amazon.com/waf/latest/developerguide/logging.html) of blocked requests. This is generally useful since requests blocked by the WAF are currently not logged at all. Allowed requests are already logged at the API Gateway (but are somewhat broken, see #4348) and by the AWS Lambda functions for indexer and service. We will also add an alarm on the WAFv2 metric for requests blocked by the rate limiting rule. We  already have an alarm on the WAFv2 metric for requests blocked for ANY reason but we've had to use a pretty generous threshold for those. The threshold for this alarm should be 0. A cursory look at `prod` shows that this metric was zero for the last week.

I'm making this a blocker of #4348 because we may want to disable API Gateway logging and replace it with WAF logging for all requests, blocked and allowed.

**Comment by hannes-ucsc** [comment]
For demo, trip rate limit and show resulting alarm notification in Slack and to the group. Show log group with blocked requests. Show that log group contains both, the rate-limited demo requests and requests blocked by other rules.
