### ISSUE TITLE
Handling WAF rate limit alarms is too much work

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5624]
The Azul REST API frequently scanned for common web application exploits. These scans often trip the rate limit and cause a notification. Our current policy is to research the IP,  post the WHOIS info and block the IP permanently. We get multiple notifications a day in each deployment, resulting in a lot of work.

**Comment by achave11-ucsc** [comment]
Spike for design.

**Comment by hannes-ucsc** [comment]
After #5246, we will programmatically (in the Lambda) monitor [the set of IPs currently rate limited](https://docs.aws.amazon.com/waf/latest/developerguide/listing-managed-ips.html), and automatically add IPs that remain in that list for longer than an hour into the list of permanently blocked IPs.

Until then, we will, monitor the notifications, triage them after stand-up, but not take any specific actions.

**Comment by bvizzier-ucsc** [comment]
@hannes-ucsc: "We stopped getting these alarms and need to figure out why. I suspect that we already increased a threshold, in which case this would already be fixed."

**Comment by achave11-ucsc** [comment]
Spike to determine why we are not getting that many notifications anymore.

**Comment by dsotirho-ucsc** [comment]
The reduction of WAF rate limit alarms is due to a few changes we made to the alarm, curl manifests, and 429 responses.
- We now have two WAF rate rules, one that starts blocking requests that exceed 1000 req / 5 min, and a second rate rule that additionally trips an alarm if the request rate exceeds 2000 req / 5 min.
- Requests that are WAF rate blocked get a 429 response along with a 30 second Retry-After header.
- Curl manifest command lines include `--retry` and `--retry-delay` options to help slow down the rate of retried requests.

Over the last six months, the only IPs to trip the WAF rate alarm have been `202.120.234.x` (Aug 15 to Sept 1) (currently blocked) and a few AWS IPs (July 29 and Sept 22). The Sept 22 event occurred because of a prod reindex https://groups.google.com/a/ucsc.edu/g/azul-group/c/_V9gXvtmQHA/m/DLVFYWetAQAJ

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: aws-waf-logs-azul-api_gateway-prod    
start-time: -15552000s    
end-time: 0s    
query-string:
  ```
  fields @timestamp, httpRequest.clientIp, httpRequest.httpMethod, httpRequest.uri, terminatingRuleId, responseCodeSent
| filter action = 'BLOCK'
| filter @message like 'RATE_BASED'
| filter terminatingRuleId = 'RateAlarmRule'
| parse httpRequest.uri /^(?<path>.+)\//
| stats count(*) by bin(7d) as datetime, httpRequest.clientIp, terminatingRuleId
| sort datetime asc

  ```
---
| datetime | httpRequest.clientIp | terminatingRuleId | count(*) |
| --- | --- | --- | --- |
| 2024-07-29 00:00:00.000 | 54.202.253.132 | RateAlarmRule | 2796 |
| 2024-08-15 00:00:00.000 | 202.120.234.179 | RateAlarmRule | 43752 |
| 2024-08-15 00:00:00.000 | 202.120.234.183 | RateAlarmRule | 23487 |
| 2024-08-15 00:00:00.000 | 202.120.234.186 | RateAlarmRule | 12614 |
| 2024-08-22 00:00:00.000 | 202.120.234.186 | RateAlarmRule | 19088 |
| 2024-08-22 00:00:00.000 | 202.120.234.179 | RateAlarmRule | 29580 |
| 2024-08-22 00:00:00.000 | 202.120.234.183 | RateAlarmRule | 49621 |
| 2024-09-01 00:00:00.000 | 202.120.234.15 | RateAlarmRule | 32372 |
| 2024-09-01 00:00:00.000 | 202.120.234.24 | RateAlarmRule | 10124 |
| 2024-09-01 00:00:00.000 | 202.120.234.21 | RateAlarmRule | 22986 |
| 2024-09-01 00:00:00.000 | 202.120.234.12 | RateAlarmRule | 22466 |
| 2024-09-01 00:00:00.000 | 202.120.234.31 | RateAlarmRule | 31943 |
| 2024-09-01 00:00:00.000 | 202.120.234.34 | RateAlarmRule | 14020 |
| 2024-09-22 00:00:00.000 | 44.243.24.205 | RateAlarmRule | 2045 |
| 2024-09-22 00:00:00.000 | 52.12.15.219 | RateAlarmRule | 3319 |
| 2024-09-22 00:00:00.000 | 34.217.83.56 | RateAlarmRule | 1942 |
| 2024-09-22 00:00:00.000 | 35.92.220.247 | RateAlarmRule | 1103 |
---

**Comment by hannes-ucsc** [comment]
We always include the query when posting CloudWatch Logs results. Please fix.

**Comment by dsotirho-ucsc** [comment]
> We always include the query when posting CloudWatch Logs results. Please fix.

Amended query results in [comment](https://github.com/DataBiosphere/azul/issues/5624#issuecomment-2549243750).
