### ISSUE TITLE
Indexing a document automatically creates an index

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5675]
Expected behavior: calling `ElasticSearch.index` with a nonexistent index name raises an error.
Observed behavior: an index is created with the name specified in the request.

Probably a manifestation of https://github.com/elastic/elasticsearch/issues/23745 affecting https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation

There is no mention of this setting in the AWS console but presumably it should be configurable via Terraform.

**Comment by hannes-ucsc** [comment]
We should try to use https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/cluster_settings#action_auto_create_index. The most likely problem with that would be the fact that the provider configuration would depend on another resource attribute, the URL of the ES domain.

**Comment by hannes-ucsc** [comment]
This patch looks promising

```diff
Subject: [PATCH] WIP
---
Index: terraform/elasticsearch.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/elasticsearch.tf.json.template.py b/terraform/elasticsearch.tf.json.template.py
--- a/terraform/elasticsearch.tf.json.template.py	(revision bb273eaac725ce07cb9678583aadf18125819fcd)
+++ b/terraform/elasticsearch.tf.json.template.py	(date 1711145438650)
@@ -17,6 +17,13 @@
 domain = config.es_domain
 
 emit_tf(None if config.share_es_domain else {
+    'provider': [
+        {
+            'opensearch': {
+                'url': '${aws_elasticsearch_domain.index.endpoint}'
+            }
+        }
+    ],
     "resource": [
         *({
             "aws_cloudwatch_log_group": {
@@ -138,6 +145,11 @@
                     }
                 }
             },
+            "opensearch_cluster_settings": {
+                "index": {
+                    "action_auto_create_index": False
+                }
+            },
             "aws_security_group": {
                 "elasticsearch": {
                     "name": config.qualified_resource_name("elasticsearch"),
Index: terraform/providers.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/providers.tf.json.template.py b/terraform/providers.tf.json.template.py
--- a/terraform/providers.tf.json.template.py	(revision bb273eaac725ce07cb9678583aadf18125819fcd)
+++ b/terraform/providers.tf.json.template.py	(date 1711145306660)
@@ -25,6 +25,10 @@
                 'source': 'hashicorp/aws',
                 'version': '5.11.0'
             },
+            'opensearch': {
+                'source': 'opensearch-project/opensearch',
+                'version': '2.2.0'
+            }
         },
     },
     'provider': [
```

It result in the following plan (excerpt): 

```
  # opensearch_cluster_settings.index will be created
  + resource "opensearch_cluster_settings" "index" {
      + action_auto_create_index = "false"
      + id                       = (known after apply)
    }

Plan: 2 to add, 9 to change, 1 to destroy.
```

I didn't go through with it.

**Comment by dsotirho-ucsc** [comment]
Spike to try above patch in the `dev` deployment.

**Comment by achave11-ucsc** [comment]
Trying the above patch resulted in an unsuccessful test, Terraform failed with the following error…

[5675-spike-try.txt](https://github.com/DataBiosphere/azul/files/14781671/5675-spike-try.txt)

```
╷
│ Error: HEAD healthcheck failed: This is usually due to network or permission issues. The underlying error isn't accessible, please debug by disabling healthchecks.
│ 
│   with opensearch_cluster_settings.index,
│   on elasticsearch.tf.json line 147, in resource[5].opensearch_cluster_settings[0].index:
│  147:                     }
│ 
╵
make: *** [apply] Error 1
``` 

Furthermore, the cluster setting seems to be effective in automatically creating an index if is non-existent. So for the given patch, a successful Terraform execution would only create an index called `false` and not disable the automatic creation of the indices.

To achieve the desired behavior, I found the following potential alternatives.
1) [Configure the cluster-templates](https://forum.opensearch.org/t/turn-off-automatic-index-construction/13446) so that only documents with the appropriate shape are indexed. Or,
2) [Directly put the cluster setting](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-index_.html#index-creation) that disables automatic index creation in the ES domain. As per the [SO post](https://stackoverflow.com/questions/33491042/aws-elasticsearch-service-disable-index-auto-creation-auto-create-index).

**Comment by hannes-ucsc** [comment]
> Trying the above patch resulted in an unsuccessful test, Terraform failed with the following error…

That's probably because the patch doesn't configure credentials for the new provider. I was hoping that the provider supports AWS request signing automatically, but it looks like it doesn't and that we need to provide auth explicitly.

> Furthermore, the cluster setting seems to be effective in automatically creating an index if is non-existent. So for the given patch, a successful Terraform execution would only create an index called false and not disable the automatic creation of the indices

If the plan applied successfully, an `opensearch_cluster_settings` resource would be created, with the TF resource name `index` and a property called `action_auto_create_index` set to false. The new provider would apply that resource by configuring the `auto_create_index` setting on the ES domain configured for the provider.

> To achieve the desired behavior, I found the following potential alternatives.
>
>   1. Configure the cluster-templates so that only documents with the appropriate shape are indexed. Or,
>   2. Directly put the cluster setting that disables automatic index creation in the ES domain. As per the SO post.

Option 2 is exactly what this patch is supposed to achieve.

**Comment by achave11-ucsc** [comment]
Assignee to modify patch to supply credentials to the provider.

**Comment by hannes-ucsc** [comment]
Unit and integration tests suffice for demo.
