### ISSUE TITLE
Create HCA pilot catalog in `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5781]
The catalog name should be `pilot`. It should have a small selection of non-MA snapshots from the most recent `dcpNN` catalog. Someone needs to decide which and how many. We don't currently have any MA snapshots for the pilot in TDR production, so this is the best we can do.

**Comment by achave11-ucsc** [comment]
Assignee to nominate non-managed access projects to include in the pilot.

**Comment by bvizzier-ucsc** [comment]
I have selected these because they are smaller (overall size) and appear to have a relatively complete set of files and file types.

https://explore.data.humancellatlas.org/projects/520afa10-f9d2-4e93-ab7a-26c4c863ce18
https://explore.data.humancellatlas.org/projects/8559a8ed-5d8c-4fb6-bde8-ab639cebf03c

**Comment by hannes-ucsc** [comment]
For demo, show new catalog in prod using an `/index` endpoint and the `/index/catalogs` endpoint.
