### ISSUE TITLE
Add managed-access snapshots to `pilot` catalog in `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5785]
There are supposed to be snapshots for three MA project but we don't know yet which ones.

**Comment by achave11-ucsc** [comment]
Assignee to stay in touch with HCA and put ticket back to triage as soon as the snapshots are available.

**Comment by bvizzier-ucsc** [comment]
I have selected these because they are smaller (overall size) and appear to have a relatively complete set of files and file types.

https://explore.data.humancellatlas.org/projects/520afa10-f9d2-4e93-ab7a-26c4c863ce18
https://explore.data.humancellatlas.org/projects/8559a8ed-5d8c-4fb6-bde8-ab639cebf03c

**Comment by bvizzier-ucsc** [comment]
Requesting review of this ticket with respect to #6156

**Comment by achave11-ucsc** [comment]
Duplicate of #6156. See PR #6157 ([e61cf78](https://github.com/DataBiosphere/azul/commit/e61cf78376257ed6127efceab601de7aab66c5f2))
