### ISSUE TITLE
Review of any Azul cloud native services interfaces requiring user identity

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5845]
As part of the discussion on the migration to Microsoft Azure B2C, the question was raised if there are any Azul interfaces to cloud native services that require the end user's identity as part of the search process.  This issue is to obtain an authoritative answer to that question.

**Comment by hannes-ucsc** [comment]
User identity is currently represented using an Google OAuth access token. AWS does not accept those, so that immediately rules out any AWS services. Azul uses the following Google Cloud services:

- BigQuery
- OAuth
- IAM (manage service accounts, permissions)
- GCS (indirectly through TDR's DRS endpoint)

Only OAuth and TDR's DRS are used with user credentials.

Whatever the Azure equivalents is for these two services are would likely user identity.

**Comment by hannes-ucsc** [comment]
@bvizzier-ucsc please find my response in the above comment.
