### ISSUE TITLE
Elevated rate of Terra DRS timeouts in `prod`

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5870]
![Screen Shot 2024-01-19 at 10 53 31 AM](https://github.com/DataBiosphere/azul/assets/19215510/8dbc45e2-75b1-4052-9fbb-23135de7294d)

Here's the same table with the count of daily 5xx returned by the service due to Terra taking longer than 5s.

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: /aws/lambda/azul-service-prod    
start-time: -2592000s    
end-time: 0s    
query-string:
  ```
  fields @timestamp, @message
| filter @message like "No response from https://data.terra.bio"
| parse @message 'body.\n{*}' as err
| parse err '* 5 seconds' as msg0
| parse msg0 '*.bio*/*/v1* within' as msg, _, __, ___
# | filter status like /5\d+/
| sort @timestamp asc
| stats count(*) as count by msg, bin(1d)
| limit 200
  ```
---
| msg | bin(1d) | count |
| --- | --- | --- |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-19 | 208 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-18 | 204 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-17 | 54 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-16 | 1987 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-15 | 84 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-14 | 19 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-13 | 36 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-12 | 21 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-11 | 45 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-10 | 30 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-09 | 48 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-08 | 48 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-07 | 24 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-06 | 39 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-05 | 37 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-04 | 63 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-03 | 48 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-02 | 56 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2024-01-01 | 14 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-31 | 9 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-30 | 13 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-29 | 21 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-28 | 14 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-27 | 17 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-26 | 13 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-25 | 3 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-24 | 5 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-23 | 3 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-22 | 10 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-21 | 20 |
| "Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio | 2023-12-20 | 1 |
---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Assignee to contact BI.

**Comment by hannes-ucsc** [comment]
https://humancellatlas.slack.com/archives/C01360XN04S/p1705708692011039

**Comment by achave11-ucsc** [comment]
Seeing this issue in other Terra components that affect `dev` and `anvildev` and causes the `post_deploy_tdr.py` script to fail during the deploy job.

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/85822

https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/33752

**Comment by achave11-ucsc** [comment]
Ongoing issue causes IT jobs in GitLab `hammerbox` and `anvilprod` to fail,

https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22118 &
https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22108

Confirmed via CW Logs,

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: /aws/lambda/azul-service-anvilprod, /aws/lambda/azul-service-hammerbox    
start-time: 2024-02-15T23:58:03.574Z    
end-time: 2024-02-16T00:17:52.340Z    
query-string:
  ```
  fields @timestamp, @message
| parse @log 'lambda/*' as lambda
| filter @message like /Returning|Received/
| parse "Received * request for '*'" as method, path
| parse "Returning * response" as status
| parse 'catalog": "*"' as catalog
| parse `headers.x-forwarded-for` '*,' as sourceIP
| parse @message '{"Code": "*",' as err
| parse @message 'https://*/*/*/*/* within' as domain, e1, e2, ,e3, e4, _
| count(*) as count_ by lambda, sourceIP, method, path, catalog, status, err, domain, concat('/', e1, '/', e2, '/', e3, '/') as endpoint
| sort lambda, @timestamp, count_ asc
# | parse @requestId '*-' as rId
# | display rId
| filter @requestId like /466b4cef|d2a2a8fe|f0f2b7b9|22d5b84d|b638c1e8|1987c5a3|9b6e2b9d|a7261553|9fd6ff1f|5650a99f|59a49b9e|83f8ce65|e17193ea|79de2ae/
  ```
---
| lambda | sourceIP | method | path | catalog | status | err | domain | endpoint | count_ |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| azul-service-anvilprod | 35.168.152.160 | GET | /repository/files/c3cbc69b-e68a-432d-99dc-c1e0e2f2bea3 | anvil4-it |  |  |  | //// | 2 |
| azul-service-anvilprod | 35.168.152.160 | GET | /fetch/repository/files/ccd10d8f-d3a0-4164-b027-24564d3f519d | anvil4-it |  |  |  | //// | 6 |
| azul-service-anvilprod |  |  |  |  | 503 | ServiceUnavailableError | data.terra.bio | /ga4gh/drs/v1/ | 8 |
| azul-service-hammerbox | 35.168.152.160 | GET | /fetch/repository/files/5ccfd5b6-1419-485d-bc0a-57865ae7bcf3 | anvil4-it |  |  |  | //// | 6 |
| azul-service-hammerbox |  |  |  |  | 503 | ServiceUnavailableError | data.terra.bio | /ga4gh/drs/v1/ | 6 |
---

**Comment by achave11-ucsc** [comment]
This happened again in `anvilprod`, https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22193

**Edit:**
x2 https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22198
x3 https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22210

**Comment by achave11-ucsc** [comment]
This happened again in `anvilprod`, https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22259

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: /aws/lambda/azul-service-anvilprod    
start-time: -10800s    
end-time: 0s    
query-string:
  ```
  fields @timestamp, @message
| parse @log 'lambda/*' as lambda
| filter @message like /Returning\s|Received/
| parse "Received * request for '*'" as method, path
| parse "Returning * response" as status
| parse 'catalog": "*"' as catalog
| parse `headers.x-forwarded-for` '*,' as sourceIP
| parse @message '{"Code": "*",' as err
| parse @message 'https://*/*/*/*/* within' as domain, e1, e2, ,e3, e4, _
# | filter status = '503'
| stats count(*) as count_ by lambda, sourceIP, method, path, catalog, status, err, domain, concat('/', e1, '/', e2, '/', e3, '/') as endpoint
# | sort lambda, @timestamp, count_ asc

# | parse @requestId '*-' as rId
# | display rId
| filter @requestId like /c59544aa|076f9239|f8ee9676|0c784016|5ee8d11f|d2c3b01d|d659fd01|2e17b9e1|eef39762|bb7309c7|1c05b8d5|5e9989b7|2e80d529/
  ```
---
| lambda | sourceIP | method | path | catalog | status | err | domain | endpoint | count_ |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| azul-service-anvilprod |  |  |  |  | 503 | ServiceUnavailableError | data.terra.bio | /ga4gh/drs/v1/ | 13 |
| azul-service-anvilprod | 35.168.152.160 | GET | /repository/files/9e87eb1a-0611-4883-bb74-d731e163ce29 | anvil4-it |  |  |  | //// | 6 |
| azul-service-anvilprod | 35.168.152.160 | GET | /fetch/repository/files/32a1f635-4200-4cc0-88fe-faf2fd88999d | anvil4-it |  |  |  | //// | 6 |
| azul-service-anvilprod | 35.168.152.160 | GET | /fetch/repository/files/0006ca88-c2e1-44b7-8ffb-42c7b2789119 | anvil4-it |  |  |  | //// | 1 |
---

**Edit:**

x2 https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22260

---
| lambda | sourceIP | method | path | catalog | status | err | domain | endpoint | count_ |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| azul-service-anvilprod |  |  |  |  | 503 | ServiceUnavailableError | data.terra.bio | /ga4gh/drs/v1/ | 7 |
| azul-service-anvilprod | 35.168.152.160 | GET | /repository/files/6997044e-d039-4496-891f-0882b714314d | anvil4-it |  |  |  | //// | 1 |
| azul-service-anvilprod | 35.168.152.160 | GET | /fetch/repository/files/ef246bbe-d129-4cd3-b718-fb5f5025f2a4 | anvil4-it |  |  |  | //// | 6 |
---

x3 https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22263

**Comment by achave11-ucsc** [comment]
This made a recurrence in `hammerbox` and  caused the `managed_access_repository_files` IT test to transiently fail:
https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/24583#L1575
```
ERROR: test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [managed_access_repository_files] (catalog='anvil4-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 427, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1306, in _test_managed_access
    files = self._test_managed_access_repository_files(catalog, managed_access_source_ids)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/test/integration_test.py", line 1417, in _test_managed_access_repository_files
    response = self._get_url_unchecked(GET, file_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/test/integration_test.py", line 847, in _get_url_unchecked
    response = http.request(method=method,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/request.py", line 77, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/request.py", line 99, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/google/auth/transport/urllib3.py", line 385, in urlopen
    response = self.http.urlopen(
               ^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/http.py", line 42, in urlopen
    return self._inner.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/http.py", line 68, in urlopen
    response = super().urlopen(method, url, body=body, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/http.py", line 42, in urlopen
    return self._inner.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 884, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='service.hammerbox.explore.anvilproject.org', port=443): Max retries exceeded with url: /repository/files/fae79227-6e6a-4c5a-a0fc-63b9da8416be?catalog=anvil4-it&version=2022-06-01T00%3A00%3A00.000000Z (Caused by ResponseError('too many 503 error responses'))
----------------------------------------------------------------------
```

[CW Logs](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2024-03-23T05*3a10*3a32.990Z~start~'2024-03-23T05*3a06*3a57.643Z~timeType~'ABSOLUTE~tz~'UTC~editorString~'fields*20*40timestamp*2c*20*40message*0a*7c*20filter*20*40requestId*20like*20*2f33bd55fc*7cad1c9b8d*7cd441c553*7c6f2392cf*7cad219d63*7c5eb3343c*2f*0a*7c*20filter*20*40message*20like*20*2fMessage*2f*0a*7c*20parse*20*27Code*22*3a*20*22*2a*22*2c*20*22Message*22*3a*20*22No*20response*20from*20*2a*22*27*20as*20code*2c*20no_res_from*0a*7c*20stats*20count*28*2a*29*20as*20count*20by*20code*2c*20no_res_from*0a*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*201000~queryId~'51eec95972125650-2db2d19-442f7b-6f47583e-1dc3cd6544b786752b29cb89~source~(~'*2faws*2flambda*2fazul-service-hammerbox~'*2faws*2fapigateway*2fazul-service-hammerbox))) indicate this was due to Terra not responding withing the allotted 5s:

---
| code | No response from | count |
| --- | --- | --- |
| ServiceUnavailableError | https://data.terra.bio/ga4gh/drs/v1/objects/v2_693b382e-18ec-39c1-8cd2-3e6fa49c2d23 within 5 seconds | 6 |
---

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
So looking closely at the traceback, the IT logs and the service logs, it is apparent that the IT did indeed retry five times as expected. Urllib3 retries by recursion and the nested calls to `urlopen` are evident in the traceback. It's also worth noting that only 9s pass while urllib3 retries the request:

```
2024-03-23 05:08:32,111    INFO MainThread azul.oauth2: Making GET request to 'https://service.hammerbox.explore.anvilproject.org/repository/files/fae79227-6e6a-4c5a-a0fc-63b9da8416be?catalog=anvil4-it&version=2022-06-01T00%3A00%3A00.000000Z'
2024-03-23 05:08:32,111   DEBUG MainThread azul.oauth2: … without request body
2024-03-23 05:08:39,290    INFO MainThread test.integration_test: Failed sub-test [managed_access_repository_files] {'catalog': 'anvil4-it'}

  test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [managed_access_repository_files] (catalog='anvil4-it') ... ERROR
```

If these were timeouts, each request would take 5s and an overall 25s would pass. There are also five requests logged by the service lambda. Here are the logs from one such request:

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: /aws/apigateway/azul-service-hammerbox, /aws/lambda/azul-service-hammerbox    
start-time: 2024-03-23T05:08:07.048Z    
end-time: 2024-03-23T05:09:47.361Z    
query-string:
  ```
  fields @timestamp, @message
# | filter @message like 'fae79227-6e6a-4c5a-a0fc-63b9da8416be'
| filter @requestId = 'ad1c9b8d-a40e-4a6c-b107-6545b60f6bde'
| sort @timestamp asc
| limit 1000
  ```
---
| @timestamp | @message |
| --- | --- |
| 2024-03-23 05:08:33.970 | START RequestId: ad1c9b8d-a40e-4a6c-b107-6545b60f6bde Version: $LATEST |
| 2024-03-23 05:08:33.971 | [INFO] 2024-03-23T05:08:33.971Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.chalice Received GET request for '/repository/files/fae79227-6e6a-4c5a-a0fc-63b9da8416be', with {"query": {"catalog": "anvil4-it", "version": "2022-06-01T00:00:00.000000Z"}, "headers": {"accept-encoding": "identity", "authorization": "Bearer ya29.c.c0AY_VpZjlRrJpmZSidsY_nRDZbxDXOiriY8q18gHqc8TiG1BgFqfWii2gdg93gtWX7HohxAEgyVfeMvfngkG93ozOxb7VgvPFemrE6vEo8E35X0X_FGMKa7SdAKmQwg15d787GDyhGjEi-I2cvP5wMMbqUfd4nkv-mAkf1zdzaWrUxvQKUppAGxv0x8yRey_rY4TdqVcLMb-z4Ip5hrcJJLs8mUNHglw8Yd0r8v-85r_uTzPF-Poioy8LSfeeG6dh6fwmcByxuz30VtVDPJdtj8KdxurxSpYejSd8asHvzyEs_XWtpLHLJWpHfiiU7CGoWEaB1e3Z1i21-s3hCBlaAPEq0uYgTgtpIFQr4w0IcVKKMNdZZGChf7JiRSpCRBAE392KR6eWi1O0o1V-28JU-ox8Jh6gkitoXd_VVn4nZmkvRM0XYxoyjiugay69BZmipa_eo0e5xo72WSdI4O5uhWSVUqJUZ9jgqo-FfvvQW4F1MycgajJv28Q0VvZUVyqIy5BQIiqMBWrg3l_Vb18id2ujt6BlVykpqhI71dyBS3gt4V2nv96M3WSB7RF7o3vFSWJBQMm01qJvFm4b-8Rbftwj0F6bX6OcioW6ZohYU7r4mJpv-gek5q05qg-zxZ5MFXkwwgMw6zzZkX4BWVYx1rVcaRlrq0lmakuUc_jlBSrvIwlzemz3lblmnxV3QzJ4WgBQ2qQOdiipJM2JB_q_7W_VY7wI_eF2zn32iOOxi6cd_7QUJoW-11762m2wO2pczXMeiZdw_F82sZpYffwQBzlVmr6gkukbhxtpgmvQulYenl52By6RkdO3-zuaRqxOiftkhIFFY5suRZUd3006U3X5rwyFwkQfaRV7ntUIM2Iyfvnn7V-Ikohw05UOcfywv2-JUB4RkxZuoXsW2b5ub0f2QUJf80vJOesfgJwVSaXvY_3wB-ve7kMtX6Q_vyBb3a-lqZ2vSp24kv85ywbJglI7cYodI41SQiYd1eoWr28Qj7UF5vRUccn", "cloudfront-forwarded-proto": "https", "cloudfront-is-desktop-viewer": "true", "cloudfront-is-mobile-viewer": "false", "cloudfront-is-smarttv-viewer": "false", "cloudfront-is-tablet-viewer": "false", "cloudfront-viewer-asn": "14618", "cloudfront-viewer-country": "US", "host": "service.hammerbox.explore.anvilproject.org", "user-agent": "python-urllib3/1.26.18", "via": "1.1 4a91a321d4c2ab7334c6f285093956ae.cloudfront.net (CloudFront)", "x-allowed-locations": "0x0", "x-amz-cf-id": "BRVfFRJ-FXKDqcweKprIJEFJwz18u9r9fYfDUEqm0NMOSwGl18I2Iw==", "x-amzn-trace-id": "Root=1-65fe63d1-165d81ba03bce9ee64a2bb92", "x-forwarded-for": "35.168.152.160, 15.158.50.37", "x-forwarded-port": "443", "x-forwarded-proto": "https", "x-goog-api-client": "cred-type/sa"}}. |
| 2024-03-23 05:08:33.971 | [INFO] 2024-03-23T05:08:33.971Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.chalice Authenticated request as OAuth2(access_token='ya29.c.c0AY_VpZjlRrJpmZSidsY_nRDZbxDXOiriY8q18gHqc8TiG1BgFqfWii2gdg93gtWX7HohxAEgyVfeMvfngkG93ozOxb7VgvPFemrE6vEo8E35X0X_FGMKa7SdAKmQwg15d787GDyhGjEi-I2cvP5wMMbqUfd4nkv-mAkf1zdzaWrUxvQKUppAGxv0x8yRey_rY4TdqVcLMb-z4Ip5hrcJJLs8mUNHglw8Yd0r8v-85r_uTzPF-Poioy8LSfeeG6dh6fwmcByxuz30VtVDPJdtj8KdxurxSpYejSd8asHvzyEs_XWtpLHLJWpHfiiU7CGoWEaB1e3Z1i21-s3hCBlaAPEq0uYgTgtpIFQr4w0IcVKKMNdZZGChf7JiRSpCRBAE392KR6eWi1O0o1V-28JU-ox8Jh6gkitoXd_VVn4nZmkvRM0XYxoyjiugay69BZmipa_eo0e5xo72WSdI4O5uhWSVUqJUZ9jgqo-FfvvQW4F1MycgajJv28Q0VvZUVyqIy5BQIiqMBWrg3l_Vb18id2ujt6BlVykpqhI71dyBS3gt4V2nv96M3WSB7RF7o3vFSWJBQMm01qJvFm4b-8Rbftwj0F6bX6OcioW6ZohYU7r4mJpv-gek5q05qg-zxZ5MFXkwwgMw6zzZkX4BWVYx1rVcaRlrq0lmakuUc_jlBSrvIwlzemz3lblmnxV3QzJ4WgBQ2qQOdiipJM2JB_q_7W_VY7wI_eF2zn32iOOxi6cd_7QUJoW-11762m2wO2pczXMeiZdw_F82sZpYffwQBzlVmr6gkukbhxtpgmvQulYenl52By6RkdO3-zuaRqxOiftkhIFFY5suRZUd3006U3X5rwyFwkQfaRV7ntUIM2Iyfvnn7V-Ikohw05UOcfywv2-JUB4RkxZuoXsW2b5ub0f2QUJf80vJOesfgJwVSaXvY_3wB-ve7kMtX6Q_vyBb3a-lqZ2vSp24kv85ywbJglI7cYodI41SQiYd1eoWr28Qj7UF5vRUccn') |
| 2024-03-23 05:08:33.972 | [INFO] 2024-03-23T05:08:33.972Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.boto3 dynamodb.GetItem: Making POST request to https://dynamodb.us-east-1.amazonaws.com/ |
| 2024-03-23 05:08:33.972 | [INFO] 2024-03-23T05:08:33.972Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.boto3 dynamodb.GetItem: … with request body b'{"TableName": "azul-sources_cache_by_auth-hammerbox", "Key": {"identity": {"S": "anvil4-it:ya29.c.c0AY_VpZjlRrJpmZSidsY_nRDZb...' |
| 2024-03-23 05:08:33.979 | [INFO] 2024-03-23T05:08:33.979Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.boto3 dynamodb.GetItem: Got 200 response |
| 2024-03-23 05:08:33.979 | [INFO] 2024-03-23T05:08:33.979Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.boto3 dynamodb.GetItem: … with response body b'{"Item":{"expiration":{"N":"1711170549"},"sources":{"S":"[\\"89385f75-353c-480a-9925-09cab5767f95\\", \\"d091a2a6-53e7-4721-82b8...' |
| 2024-03-23 05:08:33.983 | [INFO] 2024-03-23T05:08:33.983Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde elasticsearch Making POST request to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil4-it_files_aggregate/_search |
| 2024-03-23 05:08:33.983 | [INFO] 2024-03-23T05:08:33.983Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde elasticsearch … with request body b'{"query":{"bool":{"must":[{"constant_score":{"filter":{"terms":{"contents.files.uuid.keyword":["fae79227-6e6a-4c5a-a0fc-63b9d...' |
| 2024-03-23 05:08:34.003 | [INFO] 2024-03-23T05:08:34.003Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde elasticsearch Got 200 response after 0.020s from POST to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil4-it_files_aggregate/_search |
| 2024-03-23 05:08:34.003 | [INFO] 2024-03-23T05:08:34.003Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde elasticsearch … with response body '{"took":10,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":…' |
| 2024-03-23 05:08:34.004 | [INFO] 2024-03-23T05:08:34.004Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.drs Resolved prefix 'drs.anv0' to namespace ID '3571' |
| 2024-03-23 05:08:34.004 | [INFO] 2024-03-23T05:08:34.004Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.drs Obtained URL pattern 'https://data.terra.bio/ga4gh/drs/v1/objects/{$id}' from resource 'National Human Genome Research Institute' |
| 2024-03-23 05:08:34.004 | [INFO] 2024-03-23T05:08:34.004Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.terra Making GET request to 'https://data.terra.bio/ga4gh/drs/v1/objects/v2_693b382e-18ec-39c1-8cd2-3e6fa49c2d23' |
| 2024-03-23 05:08:34.004 | [DEBUG] 2024-03-23T05:08:34.004Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.terra … without request body |
| 2024-03-23 05:08:35.575 | [DEBUG] 2024-03-23T05:08:35.575Z ad1c9b8d-a40e-4a6c-b107-6545b60f6bde azul.chalice Returning 503 response with headers {"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key", "Strict-Transport-Security": "max-age=31536000; includeSubDomains", "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY"}. See next line for the first 1024 characters of the body. {"Code": "ServiceUnavailableError", "Message": "No response from https://data.terra.bio/ga4gh/drs/v1/objects/v2_693b382e-18ec-39c1-8cd2-3e6fa49c2d23 within 5 seconds"} |
| 2024-03-23 05:08:35.576 | END RequestId: ad1c9b8d-a40e-4a6c-b107-6545b60f6bde |
| 2024-03-23 05:08:35.576 | REPORT RequestId: ad1c9b8d-a40e-4a6c-b107-6545b60f6bde Duration: 1606.21 ms Billed Duration: 1607 ms Memory Size: 2048 MB Max Memory Used: 183 MB |
---

Again, only 1.5s pass between the time the TDR request is logged and when Azul returns the a 503. This can only mean that TDR must have returned a 500, 502 or 503 response. The timeout would only have kicked in much later, after 5s. Unfortunately, we don't see that response in the logs, because urllib3 raises a MaxRetryError which causes the response logging code to be skipped. So technically speaking, this incident does not constitute a timeout. 

We need to improve the retry code so that the error response is logged before Azul returns its 503, and so that we can better distinguish between timeouts and 5xx status responses from TDR. I'll probably file a partial PR against this issue to address that.

**Comment by hannes-ucsc** [comment]
For partial demo, show that a 500, 502 or 503 response from TDR still causes a 503 response from Azul, but that the TDR response is logged.

**Comment by hannes-ucsc** [comment]
I demoed the fact that we log the Terra response before returning a 503 from Azul. We are currently not observing an elevated rate of error responses so I am going to close this ticket.
