### ISSUE TITLE
Have Orange join the Grafana board

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#59]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-44)
┆Project Name: azul
┆Issue Number: AZUL-44
┆Epic: Data Browser integration with logging and analytics

**Comment by hannes-ucsc** [comment]
Tell Matt about /health and /version endpoints for service and indexer.

**Comment by theathorn** [comment]
See https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/66

**Comment by theathorn** [comment]
See SOW-4 M-2.3 "Implement infrastructure to integrate Indexeer with Grafana for analytics and monitoring".

**Comment by theathorn** [comment]
See also azul/#258.

**Comment by shiroyuki** [comment]
@theathorn I have looked into:
* Azul #258
* [DCP #66](https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/66)
* [DCP API Health Checks on Google Drive](https://docs.google.com/document/d/15dGnWzMH3tpc5zCBLf0KiIvFh8lJvjGw9urT54XhFL4/edit#)

However, it is not clear what we are expecting from the endpoint.

Currently, both the indexer and the web service have the `/health` endpoint which shows some information like in the following examples.

```javascript
// From https://service.dnastack.dev.explore.data.humancellatlas.org/health
{
    "status": "UP",
    "elasticsearch": {
        "status": "UP",
        "domain": "azul-index-dev"
    }
}
```

```javascript
// From https://indexer.dnastack.dev.explore.data.humancellatlas.org/health
{
    "status": "UP",
    "elasticsearch": {
        "status": "UP",
        "domain": "azul-index-dev"
    },
    "queues": {
        "notify": {
            "status": "UP",
            "messages": {
                "queued": "0",
                "delayed": "0",
                "invisible": "0"
            }
        },
        "fail": {
            "status": "DOWN",
            "message": "The specified queue does not exist or you do not have access to it."
        }
    }
}
```

Could you provide us more detailed information what is needed to be done for this ticket and #258?

(Side note: We also don't have access to Grafana at https://metrics.data.humancellatlas.org/d/v4-0_FWiz/dcp-health?orgId=1 but we don't believe we need the access to it to complete the task.)

(CC @hannes-ucsc)

**Comment by mweiden** [comment]
@shiroyuki please direct your discussion of health checks to https://github.com/DataBiosphere/azul/issues/258 These are two separate (but related) concerns.

**Comment by mweiden** [comment]
@shiroyuki Let me clarify what needs to be done here.

## User story

* As an operator of azul,
* I want a [dashboard](https://en.wikipedia.org/wiki/Dashboard_(business)) of key system performance metrics
* so that I know and visualize when when system failures occur.

## Key metrics to system performance

* API request rates (breaking this down by HTTP status classes--2xx, 3xx, 4xx, 5xx--is great)
* Cloud service API request rates and statuses (e.g. lambda invocation and failure rates)
* Elasticsearch performance metrics (current JVM pressure, remaining disk etc)

## What is Grafana?

Grafana is simply a metrics visualization layer. Read more about it [here](https://github.com/HumanCellAtlas/metrics).

## Definition of Done

* Prototype a dashboard on https://metrics.dev.data.humancellatlas.org/ that visualizes your system's performance. A good example of this is the [DSS Dashboard](https://metrics.dev.data.humancellatlas.org/d/dss-dev/dss-dev?refresh=1m&orgId=1)
* Once you are happy with your dashboard, follow the steps for templating it in [dcp-monitoring](https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/README.md#dashboards)
* Upload your dashboard to all your deployment environments

**Comment by shiroyuki** [comment]
@mweiden I don't have access to Grafana. Can you grant an access to the service?

**Comment by shiroyuki** [comment]
Reference: https://github.com/DataBiosphere/azul/issues/258#issuecomment-442311150

**Comment by shiroyuki** [comment]
@mweiden @hannes-ucsc Can you check if [the dashboard](https://metrics.dev.data.humancellatlas.org/d/ZzSq60Yik/azul-dashboard?panelId=12&orgId=1&from=now-7d&to=now&tab=metrics) is good enough?

> There is no stat from Route53 Health Checks which are covered by https://humancellatlas.github.io/.

![azul dashboard 2018 11 29 r001](https://user-images.githubusercontent.com/226612/49243900-7ff64200-f3dc-11e8-97a6-1c4bb944400d.jpg)

**Comment by shiroyuki** [comment]
The name of the dashboard in the final TF file will `"Azul Dashboard [${upper(var.env)}]"`.

**Comment by mweiden** [comment]
@shiroyuki that looks good!

I've made some small edits to your dashboard and saved it as a copy on grafana. Check them out [here](https://metrics.dev.data.humancellatlas.org/d/DT-Tn-Lik/azul-dashboard-mw_edits?orgId=1) and use them if you like, otherwise go ahead with your version. Edits below.

* Made the graphs the width of the page for better visibility
* Add a templated variable `interval` so that you can change the period over which the statistics are gathered in each graph in one go

**Comment by shiroyuki** [comment]
@mweiden Your version looks better.

**Comment by shiroyuki** [comment]
@mweiden I forgot to ask earlier today. With the work on https://github.com/HumanCellAtlas/dcp-monitoring/pull/11 and https://github.com/HumanCellAtlas/dcp-monitoring/pull/12, could you verify if there is anything else needed to be done for this ticket?

**Comment by mweiden** [comment]
@shiroyuki on a surface level, yes, this is complete. Of course, in operating the software you may need more insights into the system's behavior. Done right, you'll be updating your monitoring configuration regularly as the system matures.

**Comment by shiroyuki** [comment]
@theathorn  @hannes-ucsc the dashboard for `dev`, `integration` and `staging` are available.

* [Azul Dashboard [DEV]](https://metrics.dev.data.humancellatlas.org/d/dcp-health-dev/azul-dashboard-dev?orgId=1)
* [Azul Dashboard [INTEGRATION]](https://metrics.dev.data.humancellatlas.org/d/dcp-health-integration/azul-dashboard-integration?orgId=1)
* [Azul Dashboard [STAGING]](https://metrics.dev.data.humancellatlas.org/d/dcp-health-staging/azul-dashboard-staging?orgId=1)

**Comment by mweiden** [comment]
@shiroyuki I've also uploaded your prod dashboard for you

* [Azul Dashboard [PROD]](https://metrics.data.humancellatlas.org/d/dcp-health-prod/azul-dashboard-prod?orgId=1)

**Comment by shiroyuki** [comment]
@mweiden Thank you, sir. 😃
