### ISSUE TITLE
Increased error rate due to conflicts related to replicas

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5975]

**Comment by dsotirho-ucsc** [comment]
Spike to diagnose and propose solution.

**Comment by nadove-ucsc** [comment]
The conflicts are due to mismatches in the [sequence number](https://www.elastic.co/guide/en/elasticsearch/reference/current/optimistic-concurrency-control.html) of the replica documents during scripted updates. This is presumably due to multiple lambdas trying to update the same replica concurrently. (I didn't realize that optimistic concurrency control also applied to update operations, but in retrospect, I should have).

```
There was a conflict with document
    ReplicaCoordinates(
        entity=EntityReference(entity_type='replica', entity_id='5ee7f632-0135-46af-a016-e9d84022adf1'),
        doc_type=<DocumentType.replica>,
        content_hash='66bfb0f8a647f737f54a04007ec9f90762e32af1'
    ):

    ConflictError(409, 'version_conflict_engine_exception', {'error': {
        'root_cause': [
            {
                'type': 'version_conflict_engine_exception',
                'reason': '[5ee7f632-0135-46af-a016-e9d84022adf1_66bfb0f8a647f737f54a04007ec9f90762e32af1]: version conflict, required seqNo [101850], primary term [1]. current document has seqNo [101852] and primary term [1]',
                'index_uuid': 'DMrsChEhTmKQoChzy4qSBA',
                'shard': '14', 
                'index': 'azul_v2_anvilprod_anvil4_replica'
            }
        ], 
        'type': 'version_conflict_engine_exception', 
        'reason': '[5ee7f632-0135-46af-a016-e9d84022adf1_66bfb0f8a647f737f54a04007ec9f90762e32af1]: version conflict, required seqNo [101850], primary term [1]. current document has seqNo [101852] and primary term [1]', 
        'index_uuid': 'DMrsChEhTmKQoChzy4qSBA',
        'shard': '14',
        'index': 'azul_v2_anvilprod_anvil4_replica'
    }, 'status': 409}).

    Total # of errors: 2, giving up
```

We [configure our IndexWriter to give up after a single conflict](https://github.com/DataBiosphere/azul/blob/01cd726999041be10b1e3eab650e96e920514239/src/azul/indexer/index_service.py#L805). The provided rationale makes sense for contributions, but not for replicas. Because every primary and supplementary AnVIL bundle is expected to contain an identical replica of the `dataset` entity, we should expect a relatively high rate of conflicts for updates to these replicas.

Furthermore, whenever we attempt a scripted update, the quota of a single retry has already been filled by the initial attempt to create the replica. Therefore, the effective conflict retry limit for replicas is actually _zero_, instead of one.

**Comment by nadove-ucsc** [comment]
The most obvious solution is to increase the conflict retry when writing replicas to an experimentally determined value. Currently, we create separate IndexWriter's for handling contributions and replicas. I'm not sure if that's intentional, but it does make it convenient to configure the retry limit separately for them. 

Alternatively, we may be able to avoid these conflicts using the [refresh parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html) at the cost of performance. But it's not entirely clear to me how `refresh` interacts with scripted update.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Assignee to create one partial PR that makes the conflict retry limit for replicas configurable, with a default value of 10. We will test this PR as soon as possible in anvilprod using another full reindex. While the reindex is ongoing compare the throughput to the reindex to that of the reindex that exhibited the increased number of conflicts. If it is back to normal, we will consider this problem fixed. Otherwise we will decide on next steps as we go. Meanwhile, assignee to also create a second PR potentially chained on the first one. In this PR we should try to combine the initial scriptless insert with the subsequent scripted update. Supposedly there is a scripted upsert in Elasticsearch. This would shave off one potential round trip."

**Comment by hannes-ucsc** [comment]
For demo, compare running time and error rate to an equivalent reindex prior to this change in both `prod` and `anvilprod`.
