### ISSUE TITLE
Default manifest name is `hca` for AnVIL

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6101]
@hannes-ucsc: "We should use the atlas name from `AZUL_CATALOGS` instead of the hard coded `hca` prefix for the default manifest file name."

**Comment by hannes-ucsc** [comment]
For demo, generate two compact manifests in `anvildev` or `anvilprod`. One manifest should be filtered to exactly one project, the other one should use a filter that spans two or more projects. The name of the first manifest should be derived from the project name, the second one should have the default name, now with `anvil` instead of `hca`.

Repeat on `dev` or `prod`. 2nd manifest name should start with `hca-`, as before.

Repeat on `dev` or `prod` with a `lungmap` catalog.
