### ISSUE TITLE
Deletions break during reindexing

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#611]
Follow-up on #86/#600

Deletions currently don't work when they occur during a reindexing because they rely on listing all contributions by that bundle. If the bundle is currently being (re)indexed, the listing may miss contributions. Note that not only the first indexing of a bundle introduces new contributions, even a *re*indexing of a bundle may introduce entities that weren't present in the index before (due to code changes). If the new entities are then later processed by the `-write` lambda, the bundle will be reintroduced into the index.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-384)
┆Project Name: azul
┆Issue Number: AZUL-384

**Comment by jessebrennan** [comment]
Here are potential solutions summarized from a discussion with @hannes-ucsc. We need to make sure that deletions do not cause any race conditions. The root of the problem is as follows: while processing deletion notifications Azul gets all of the information it has about a bundle from its own index. Thus a bundle will only be deleted after it's original notification has been fully processed. Otherwise the bundle won't be deleted at all, or else only partly deleted. (FIXME: fact check the first clause of previous sentence)

There are a couple potential solutions.

1. **Serialize everything**. This is probably impractical because all activity in all lambdas would need to be stopped before a single deletion could be processed. Unless deletions were stored in a separate queue and batched to be handled only once a day this would probably be too disruptive.

2. **Contain bundle metadata in deletion notifications**. The most elegant implementation to this solution would involve changes to the DSS. Azul would need a guaranteed way to get access to the notification that is being tombstoned. Azul then indexes the bundle as normal, but also includes the deleted flag (as it currently exists). Now, instead of searching its own index for the bundle, Azul can search the original source that is always guaranteed to be correct. Part of this solution also needs to hadle the case in which a bundle is processed after a deletion. Regular duplicate notifications should be ideptotent, but a single deletion should last forever.

3. **Directly access bundle metadata from DSS**. This involves no changes to the DSS. Instead Azul with get the bundle information that it needs by directly accessing the bundle metadata from the AWS buckets that serve the DSS.

Options 2. and 3. will become problematic when data is actually deleted from DSS. Hopefully a delay between TOMBSTONE and DELETE notifications would be enought for everything to be fully processed. 

On further research it seems like there are some DSS issues related to this:
- https://github.com/HumanCellAtlas/data-store/issues/805
- https://github.com/HumanCellAtlas/data-store/issues/821

https://github.com/HumanCellAtlas/data-store/issues/821 proposes another solution:

4.  **Have a completely separate deletion index**. So make sure that Azul is _eventually_ complient with deletions, a deletion notification could trigger a periodic rerunning of the deletion which could be enough to ensure that deletion is complete. This solution needs more thinking to become fully fleshed out.

**Comment by jessebrennan** [comment]
The plan is to do direct access for both deletions and additions. The document ID of contributions is extended to include the deleted flag. When aggregating contributions, deletions contributions have priority over addition contributions.

This also solves out of order indexing of deletions because of the sorting during aggregation.
