### ISSUE TITLE
Support for HCA data_use_restriction

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6131]
Index [project.data_use_restriction](https://github.com/HumanCellAtlas/metadata-schema/blob/226a9135bb4ba2dbe53216cbb80f5b7fea6dc27f/json_schema/type/project/project.json#L169C10-L169C30), expose in all `/index/…` responses, add term facet, ability to sort and filter by that field.

~Index [project.duos_id](https://github.com/HumanCellAtlas/metadata-schema/blob/226a9135bb4ba2dbe53216cbb80f5b7fea6dc27f/json_schema/type/project/project.json#L181C10-L181C17), expose in all `/index/…` responses.~ https://github.com/DataBiosphere/azul/issues/6131#issuecomment-2073279195

**Comment by NoopDog** [comment]
Hi @hannes-ucsc, 

What are you thinking the values will be?

For `project.data_use_restriction`, I can propose that you just pass through what you get and that the values we will see will be:

- `null` when the `data_use_restriction` is not specified on the project.
- otherwise, `NRES,` `GRU,` or `GRU-NCU`

Similarly, for `project.duos_id`, will you just pass this field through when it is specified and send `null` when it is unspecified?

Cheers,
D

cc: @bvizzier-ucsc

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "We will use the values from the metadata verbatim."

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "The current mock MA snapshot (hca_prod_edc54c5d82404681844462a086d1d1be__20240410_dcp2_20240410_dcpPilot) does not contain the `duos_id` field, so we will postpone that work until the field can be observed in the wild. See #6196."

**Comment by hannes-ucsc** [comment]
For demo, show the new field in the response, using `prod`. Show filtering, sorting and facet.
