### ISSUE TITLE
Create FedRAMP 3PAO pen test deployment

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6246]
To avoid disruption of the production environments, it has been decided that we will setup a instance for the 3PAO to conduct their penetration testing against.  

This instance will use mock managed access datasets.

**Comment by hannes-ucsc** [comment]
Azul and Data Browser deployments are up. Build-status is not green due to https://github.com/DataBiosphere/azul/issues/6263 but a manual reindex was done to work around that.

Sign-in doesn't work because the GCP project for the new deployment wasn't allow-listed yet. We need to request for project `platform-temp-dev` with project # 807674395527 to be allow-listed in the Terra dev instance ASAP.

**Comment by achave11-ucsc** [comment]
- [x] @hannes-ucsc to update the ATT
- [x] @bvizzier-ucsc  to coordinate allow-listing with the broad
- [x] @nolunwa-ucsc to collect updated list of pen-testing IPs & Gmail accounts and update ATT with that information
- [x] @hannes-ucsc to allow-list pen testing IP(s) in `tempdev`
- [x] @hannes-ucsc to notify @nolunwa-ucsc that the pen test can begin
- [ ] @hannes-ucsc to add pen-testing Gmail account to the `azul-anvil-dev` Terra group when accessor requests it

**Comment by hannes-ucsc** [comment]
https://temp.gi.ucsc.edu/

**Comment by bvizzier-ucsc** [comment]
Beth Sheets has taken ownership of allow-listing this instance.  I'll mark it as complete once I know it is done.

**Comment by bvizzier-ucsc** [comment]
[The allow-listing is believed to be complete](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1715886427495629?thread_ts=1715823530.936159&cid=C03TPJS54DC).
