### ISSUE TITLE
Docker docker image cannot be scanned by AWS Inspector

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6311]
The updated docker docker image added by PR #6290 cannot be scanned by AWS Inspector.

> Image not supported UnsupportedImageError: The operating system and/or package manager are not supported.

![may28](https://github.com/DataBiosphere/azul/assets/46407464/ac9afa38-806b-4cc1-9e1b-46f32101b5a7)

**Comment by hannes-ucsc** [comment]
Upstream blocker: ~`https://github.com/aws/containers-roadmap/issues/2358`~ https://github.com/aws/containers-roadmap/issues/2357

~`https://github.com/aws/containers-roadmap/issues/2358#issuecomment-2141363006`~ https://github.com/aws/containers-roadmap/issues/2357#issuecomment-2161323407

**Comment by dsotirho-ucsc** [comment]
Assignee to periodically check upstream blocker.

**Comment by rgoltz** [comment]
Hi @hannes-ucsc & @dsotirho-ucsc - Could you please correct your link to the upstream blocker? - Since you are using AWS Inspector (so called Enhanced Scan in AWS ECR), it's https://github.com/aws/containers-roadmap/issues/2357 you are waiting for - The other issue is related to the Basic Scan in AWS ECR. From my testing your docker image-tag (25.0.5-alpine3.20) is already scanable in Basic, but not in Enhanced Scan (unfortunately - please see the linked discussion)

**Comment by hannes-ucsc** [comment]
Done. Thanks for the pointer, @rgoltz

**Comment by rgoltz** [comment]
@hannes-ucsc & @dsotirho-ucsc : AWS ECR Inspector updated the docs with support for Alpine 3.20. It's working on your end? (in case yes, I would close the linked github issue)

**Comment by dsotirho-ucsc** [comment]
Thank you @rgoltz 
I've confirmed AWS Inspector scan results are now available for our image.

![Screenshot 2024-06-20 at 9 12 52 AM](https://github.com/DataBiosphere/azul/assets/46407464/da68c1cf-7a9b-41b2-8a41-41a24df4da9f)

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "For demo, show that findings are detected for the Docker images in the screenshot of the inspector findings spreadsheet from the most recent upgrade issue."
