### ISSUE TITLE
FedRAMP inventories review issues are created without labels

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6461]
https://github.com/DataBiosphere/azul-private/issues/157

<img width="608" alt="Screenshot 2024-08-01 at 11 56 22 AM" src="https://github.com/user-attachments/assets/6382bc98-004b-4ebf-a054-9355f199c3d7">

**Comment by dsotirho-ucsc** [comment]
Spike to diagnose

**Comment by achave11-ucsc** [comment]
Comparing the GitHub Action job logs for both issues created on schedule yield no evidence of an ineffective or malformed command. This was done for #6455 (Correctly labeled) in Azul and DataBiosphere/azul-private#157 in azul-private (which lacks the labels & user assignment established by the template), [Scheduled jobs #16421](https://github.com/DataBiosphere/azul/actions/runs/10165842210/job/28114620675#step:3:8) and [Scheduled jobs #16534 ](https://github.com/DataBiosphere/azul/actions/runs/10193658708/job/28198683989#step:3:9) respectively. Both of this produced a similar `gh` command which was followed by a URL to the newly created issues.

This may be a permissions issue associated with the GitHub token being used by the `azul-group` "user."  More details about the permission scope of the token are require to make a determination. 
In an experiment, this …
<img width="618" alt="Screenshot 2024-08-01 at 4 54 00 PM" src="https://github.com/user-attachments/assets/89038354-6a4b-41bd-8491-95194c56c428">
… was the minimum set of permissions my personal access token required in order to be able to list the issues in the `azul-private` repository and to be able to edit (remove/add) its tags.
```
GITHUB_TOKEN=[Spike.Azul#6461] gh issue edit --repo=DataBiosphere/azul-private 120 --add-label=-
https://github.com/DataBiosphere/azul-private/issues/120
```

Also, the azul-group user doesn't seem to have a special designation in the Azul teams for the [DataBiosphere teams](https://github.com/orgs/DataBiosphere/teams) overview, however this may not be relevant until we determine the permission scopes of the GitHub access token being used by the GitHub Actions for the scheduled issues.

**Comment by achave11-ucsc** [comment]
This was due to the `@azul-group` user not having at minimum `triage` permissions in the `azul-private` repository which enables it to perform actions like applying tags to issues. See [this Slack discussion](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1722559597429069?thread_ts=1722557833.939449&cid=C705Y6G9Z) for details on resolution.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "The GitHub issue creation should error when it doesn't succeed in creating the issue including applying labels or any other properties that are specified in the template. Assignee to either split the label application into a separate GitHub CLI invocation (assuming that it fails if the labels can't be applied), ditto with the other properties. If that doesn't work, assignee to add CLI invocations that verify the successful and complete creation of the issue."

**Comment by hannes-ucsc** [comment]
For demo, temporarily modify the permissions of the azul-group user so that it lacks permission to apply labels. Temporarily modify the workflow script so that it will attempt to create an FedRAMP inventory issue on the next invocation. Run the script with the token of the azul-group user. The script should fail with a non-zero exit status and a descriptive error message. Undo the permission change. Modify the front matter in the FedRAMP inventory issue template to specify an entry for `repository` without a value. Run the script again. The script should fail with a non-zero exit status and a descriptive error message. Undo the issue template change. Run the script again. It should succeed in creating the issue. Undo any script changes. Invalidate the token and update the corresponding repository secret.

**Comment by hannes-ucsc** [comment]
I demoed this to myself and will be pushing this to `develop` directly. With the `azul-group` token and insufficient permissions, the issue is created without labels or assignees …

<img width="1285" alt="image" src="https://github.com/user-attachments/assets/cebab3c2-5624-4678-b5e9-cad6adefdb98">

… and the script fails as follows …

```
2024-08-23 18:25:37,921    INFO azul.github.schedule: … created 'https://github.com/DataBiosphere/azul-private/issues/181', verifying labels and assignees …
2024-08-23 18:25:37,921    INFO azul.github.schedule: Running ['gh', 'issue', 'view', '--repo=DataBiosphere/azul-private', '--json=labels,assignees', '181'] …
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.github/workflows/schedule.py", line 246, in <module>
    main(sys.argv[1:])
  File "/Users/hannes/workspace/hca/azul/.github/workflows/schedule.py", line 240, in main
    self.create_issue(now.date())
  File "/Users/hannes/workspace/hca/azul/.github/workflows/schedule.py", line 216, in create_issue
    assert set(assignees) == actual_assignees, (assignees, actual_assignees)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: (['hannes-ucsc'], set())
```

With the necessary permissions, the script creates the issue as intended:

<img width="1267" alt="image" src="https://github.com/user-attachments/assets/100ce02a-9af9-4978-92d2-c7a9ae8b8f51">
