### ISSUE TITLE
Save query made on the browser

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#66]
As a user I would like to do CRUD on queries I've made against the browser.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-37)
┆Project Name: azul
┆Issue Number: AZUL-37
┆Epic: Save search queries

**Comment by theathorn** [comment]
Save a search query as a shortened url for sharing.

**Comment by theathorn** [comment]
See SOW-3 M-1(c) "This service includes search saving as an immutable URL".

The Browser already generates a long URL for search terms that can be shared. However the URL gets too long if many facets are selected. Instead a short URL should be generated which refers to the long form URL stored in e.g. DynamoDB.

For an example see https://dcc.icgc.org and click on "Advanced Search", select e.g. "Blood" and "Breast" and then click on the "Share" button which will generate a URL such as "https://icgc.org/ZH5".

Clevery Canary @NoopDog will implement a similar button in the Data Browser.
This ticket is to provide an API which will generate the immutable short URL from the long form.

**Comment by shiroyuki** [comment]
@theathorn: Is any link supposed to be available forever? If not, how long is the link supposed to be available for?

@hannes-ucsc ↓ Here is my idea on saving query and shortening the URL.

### Endpoint Implementation

Currently, there are two approaches to get this.

> Suppose we define **a shortener key** (AKA *code*) as the Base64 encoded string of the byte representation of the version 4 UUID.

#### Approach 1: Lambda + DynamoDB

* We will have an endpoint `POST /query` to save the query.
  * This will **create an entry on DynamoDB** where the hash key is a shortener key.
  * The final returning URL would be something like `https://service.explore.data.humancellatlas.org/r/{code:str}`.
  * The endpoint must be protected. (Required #58)
* There will be a corresponding endpoint `GET /r/{code:str}` where the endpoint will just do the reverse lookup.
* In this approach, we only need to store the filters (perhaps and/or the request path).

This is probably the most straight-forward approach in term of implementation. The only constraint of this method is the provisioned read throughput of the DynamoDB and the associated cost.

#### Approach 2: Lambda + S3

* We will have an endpoint `POST /query` to save the query.
  * This will create an object on S3 where the object key is a shortener key where:
    * The host bucket is **publicly readable** has **static website hosting** enabled.
    * The object metadata `x-amz-website-redirect-location` is specified as the full URL for S3 to redirect back to the data browser.
    * The object may have TTL defined.
    * The body of the object can be empty.
  * The final returning URL would be something like `https://s3.amazonaws.com/{host_bucket:str}/{code:str}` or anything equivalent (e.g., `https://h.ca/{code:str}` via DNS redirect with Route 53.
  * The endpoint must be protected. (Required #58)
* To access to the save query, the user/client can just open the URL given by the previous endpoint.
* In this approach, we can only store the full URL for redirection.

Here is an example:

```python
session = boto3.Session(profile_name='hca-id', region_name='us-east-1')
s3 = session.client('s3')
s3.put_object(
  Bucket='azul-url-shortener-experimental',
  Key='shiroyuki.com',
  Body=b'',
  Metadata={'x-amz-website-redirect-location': 'https://www.shiroyuki.com/'}
)
```

In comparison to the first approach, this approach is less straight-forward from the source code but it is probably the most economical one as it would cost almost nothing to just have S3 redirect to any given destination.

### Deployment

We have at least two options:

* Deploy the code as part of the web service. (Preferred)
  * Minimal additions to infrastructure.
* Deploy the code as a new micro service.
  * This will be reusable by any services in the future.
  * More suitable to the S3 approach.

### Bit.ly and Firebase Dynamic Links?

To use either of them will be identical to implement the S3 approach. However, unlike the S3 approach, both services require an API key which might make it difficult to manage with Terraform.

**Comment by hannes-ucsc** [comment]
Thank you for the research, @shiroyuki. Using S3's 'x-amz-website-redirect-location' is clever.

But we should derive the key by hashing the URL instead of allocating a UUID to avoid creating multiple objects in S3 for the same URL.

I'm confident that the first eight bytes of the SHA-1 of the URL would be sufficient to push the probability of collisions low enough to not have to handle that possibility other than detecting it and raising an error.

However, I researched a bit and it seems that we can do better (shorter keys) by using open addressing (maybe this is what @Ben-Wu had in mind):

1) Hash the URL using SHA1
2) Encode the binary hash using base62 (a-zA-Z0-9) or URL-safe base64 if that's easier
3) Use the first N digits from the encoded hash as a key to probe
4) Read the full URL from the S3 object (either metadata or object content)
5) If the URL is identical, use the key to build the shortened URL (either point directly to the bucket or point to a proxy endpoint in our service, haven't decided yet)
6) Otherwise, increment N and goto 3

There are tons of potential variations on the probing. For example we could increment the N-digit base64 number (0aM to 0aN, for example) instead of increasing N. This would keep URLs shorter, increasing the load factor on the hash table.

**Comment by hannes-ucsc** [comment]
Oh, and the initial value for N should be 3.

@shiroyuki

**Comment by hannes-ucsc** [comment]
I also inserted a step in position 6.

**Comment by hannes-ucsc** [comment]
@NoopDog to address your comment from stand-up, we should NOT just allocate a UUID for the key because 1) hashing the URL is just as easy and 2) it ensures that we don't store the same long URL in more than one short URL object. There is value in enabling users to infer that two different short URLs represent to two distinct long URLs. I feel strongly about this.

To use base64 instead of hexadecimal encoding is also an easy win in my opinion as it is straight-forward to do and creates shorter URLs. If we use base64, we should not base64 a hexadecimal UUID, but instead a random binary. UUID4s are random binary numbers encoded in hex so one can get the same collision probability with a shorter key by generating a random binary number and encoding it straight to base64. I also feel strongly about this.

With respect to using open addressing and probing to shorten the URL as I describe [here](https://github.com/DataBiosphere/azul/issues/66#issuecomment-442596970), I don't feel strongly about it. I think it would be cool and fun to implement but I agree that it would make testing more complicated. I'll leave it to the implementer to make the call.

@theathorn was going to ask @briandoconnor to weigh in on how important URL brevity is.

**Comment by briandoconnor** [comment]
Hey @hannes-ucsc and @NoopDog (and @theathorn ).  For me I think there's little difference between, say:

http://icgc.org/its93

and 

http://icgc.org/57d876a6-3dc8-4762-a9e3-2cc249dd57ff 

The URLs don't have to be super short, we just don't want them to be longer than, say, 80 characters so it's easier/safer to copy and paste them around.  

Personally, I'd prefer something that's a hash so if I shorten the same URL in the future I get the same shortened URL back.  It makes it obvious if I'm passing around the same query as someone else.

**Comment by Ben-Wu** [comment]
- Requesting a shortened url that does not exist should go to the data browser 404 page
- Endpoint should take a full url and check the url against a whitelist (`*humancellatlas.org*`)

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/pull/583#issuecomment-447221769
