### ISSUE TITLE
Replace Specimens tab with Samples tab

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#707]
The Samples tab will consist of entities that are "up one" from "cell suspension":
  - organoid
  - cell line
  - specimen

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-438)
┆Project Name: azul
┆Issue Number: AZUL-438
┆Epic: Improve or Replace Specimens Tab

**Comment by hannes-ucsc** [comment]
Despite this being a lot of work, I don't think this can be further broken down into subtickets. The specimens outer entity should be replaced with a sample outer entity. The sample entity type is artificial (no equivalent entity type exists in the metadata schema) and polymorphic (a sample could represent either an organoid, a specimen, or a cell line). One could call it an *abstract entity type*.

For each cell suspension in a bundle, a sample entity should be created for each parent biomaterial, ignoring any processes in between. If the ancestry chain of a cell suspension is `process` - `specimen` - `process` - `donor`, a sample should only be created for the `specimen` since `donor` is a grand parent.
