### ISSUE TITLE
Review/reduce AWS Elasticsearch costs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#781]
@hannes-ucsc :

CZI (Andrey and MattW) have requested we start using AWS Cost Explorer to monitor, and hopefully reduce, Azul's Elasticsearch costs which are currently running at ~$8400/month.

Our first step should be to make a first pass analysis of cost breakdown and see if there any easy reductions.

CZI also requests we tag all AWS assets with "owner" (email address of hca-id user) and "project" (e.g. service and/or team).

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-483)
┆Project Name: azul
┆Issue Number: AZUL-483

**Comment by hannes-ucsc** [comment]
The predominant factor in ES cost are instance-hours. Azul is the only component that uses r4.2xlarge which makes it easy to distinguish ES cost incurred by Azul from that by other components. Azul uses 4 nodes for its `dev` deployments, and 2 nodes for each of the other three deployments.

The r4.2xlarge cost for the lesser deployments for February was $4215, the cost for other instance types (and therefore other components) was $1542 adding up to a total of $5757. This covers 8 nodes (4 in `dev`, 2 in `integration` and 2 in `staging`). An r4.2xlarge costs $0.785/h. 8 nodes * 24h * 28d * $0.785 = $4220.16 which is close to the actual cost of $4215.

In `prod` the situation in February is analogous: $1055 for the two Azul nodes, $1614 for other components, and a total of $2669.

March is projected to be on par with February.

At least two instances per cluster is a generally recommended practice.

There is no waste, except for the fact that most of the time, those instances are idle. When they are not idle, during reindexing and when scale testing the consumer side (queries), those instances are 100% of the recommended memory pressure. This is why we chose that type.

Here are a few ideas on how to reduce ES cost. Like everything in engineering, this is a trade-off. We cannot reduce cost without A) incurring cost somewhere else, like developer time or B) reducing scale. There is no free lunch. However, we probably haven't optimized these trade-offs very well.

The Azul team recently optimized the number of shards which significantly increased the number of concurrent queries the cluster was able to process. This optimization may allow for a reduction of the instance type. This needs more research and experimentation which we can schedule for the next sprint.

Another, optimization is the purchase of reserved instances. For 1 year upfront the cost per instance hour drops by one third, e.g. from $0.785 to $0.51. This should be done as soon as we settle on an instance type and minimum size of a cluster.

A very simple first step is to reduce the size of the `dev` cluster from 4 to 2. We initially sized it up from 2 to 4 nodes because it hosts the personal deployments by most Azul team members. However, we recently dramatically cut down the index size for these personal deployments making a 4 node cluster unnecessary. This would save $1000 per month. 

A more significant saving could be achieved by consolidating the lesser deployments to use a single cluster of four (two) nodes, a savings of $2000 ($4000). Using a single cluster for all lesser deployments would require careful coordination when running a bundle processing scale test so as prevent operations in other deployments (reindexing or consumer-side scale tests) from interfering with it.

Another optimization would be dynamically scaling the cluster. However, I think that two nodes are the minimum so this solution would only be used for scaling the `prod` cluster up under load and wouldn't save any cost right now.

**Comment by theathorn** [comment]
Superseded by DCP/2 - closing.
