### ISSUE TITLE
Design HCA data resolution flow for HCA handoff to Terra MVP

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#864]
Design the flow for resolving an HCA-provided file DOS/DRS URI to a format that can be used by Cromwell for workflow execution. To the best of our current knowledge, this is a Google cloud native URL ("gs://") and Google service account key.
This involves collaboration with multiple parties/components, including:
* HCA Azul webservice
* Broad Martha DRS resolver service
* (Future?) Broad/DataBiosphere Bond service

This design is for the initial/MVP flow for the HCA handoff to Terra. The objective is to get the data flowing reliably, as quickly (and with a few substantial changes) as possible for the MVP.
Some consideration should be given to the design of the longer-term/final flow, which may include support for security/authN/Z, possibly including Bond and Fusillade.

Done when:
A design for HCA data resolution flow for HCA handoff to Terra MVP has been created and agreed upon by:
* HCA Azul team
* Broad key team members working on the HCA handoff to Terra

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-537)
┆Project Name: azul
┆Issue Number: AZUL-537
┆Epic: Terra hand-off

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

This plan was developed and reviewed with Alex Baumann and [~hannes-ucsc]:
[Terra/Cromwell Access to Files Identified by DRS URIs for the HCA/Terra MVP
|https://docs.google.com/document/d/18WDYr3uS82Eu1GhHmeH6PX7tFY6Zk8piKd3ixOoE8Bg/edit#]

Since then, however, Andrey has said that the checkout buckets should not be changed to provide open/public access to them (Provide public access to HCA DSS checkout buckets #2055 ( https://github.com/HumanCellAtlas/data-store/issues/2055#issuecomment-487204894 )), so this plan now needs to be updated to address data access credentials/management.

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

The design and deployment approach for the final piece (HCA credential access) for the HCA/Terra MVP was co-developed and agreed-upon with the Broad developers and devsec on 6/6-7/19. This needs to be documented, and a debrief given to Hannes and Trevor.
