### ISSUE TITLE
Add bundle and file version info to metadata tsv file

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#945]
Request from @briandoconnor to add the bundle uuid, bundle version and file version to each row in the per-project metadata tsv files (which currently contain file path) to allow correlation with the information in the manifest download file.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-589)
┆Project Name: azul
┆Issue Number: AZUL-589
┆Epic: Maintain a full, per-project metadata TSV file

**Comment by hannes-ucsc** [comment]
Adding humancellatlas/dcp-cli#239 as a blocker because the only ways to determine the bundle version is by 1) consulting the manifest or 2) parsing it out of the download directory name that the DCP CLI creates for every bundle.

#945 will involve a simpler resolution for this issue. But to minimize risk, we've decided to move forward having @GPelayo implement this in https://github.com/HumanCellAtlas/hca_bundles_to_csv. If #945 progresses more quickly than I expect, we'll abandon @GPelayo's implementation.
