### ISSUE TITLE
Specify metadata format for per-project Matrix Service output file bundles

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#972]
The Matrix Service will (manually/on a schedule/via DSS notifications) generate/update all possible matrix output formats (loom, csv, etc.) on a per project basis.
These files will be stored in DSS via the "put bundle" interface which will generate a notification to Azul to index the bundle thus allowing the Data Browser to implement a "direct download matrix output" link for each project.
This ticket is to specify the metadata json format so that the Matrix Service team can implement the bundle generation.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-603)
┆Project Name: azul
┆Issue Number: AZUL-603
┆Epic: Use the DSS to store per-project matrix files

**Comment by hannes-ucsc** [comment]
Yes, @briandoconnor proposes that we use the DSS to store a canned matrix for each project.

Azul will need to be able to distinguish these special matrix bundles from regular primary or secondary bundles. In a way the matrix bundles are akin to tertiary bundles. The matrix file in the bundle should be accompanied by two metadata files: `analysis_file.json` and `project.json`. The former should minimally describe the matrix file similarly to how this metadata file is used to describe output files in secondary bundles. The `project_0.json` file could either be a copy of the `project_0.json` file from the input primary bundles (preferred) or a reduced version with dummy values for the required fields. The only field that shouldn't be faked is `provenance.document_id` because that's what we would use to associate the matrix with the project.

Ideally, we could also include `analysis_process.json` and `analysis_protocol.json` but Azul would probably ignore them. If `analysis_process.json` is present, it should not declare an input bundle.

The Azul indexer would then assume that every bundle with a single matrix file and no declared primary input bundle is a per-project matrix bundle and associate the matrix file with the project.

Updates to the matrix bundle should reuse the same UUID but allocate a new version.

Note that DSS allows for specifying a bundle UUID during `PUT /bundles`. The UUID of the matrix bundle could be set to the project's UUID but this is only a convenience. Azul will not depend on it.

**Comment by mckinsel** [comment]
Hey Hannes, this makes sense. I have one question: each matrix comes in three (or in the future more) formats. Would you want each of these in a single bundle and an `analysis_file_{0,1,2,...}.json`?

**Comment by briandoconnor** [comment]
So if I understand correctly, there will be one bundle per project (and it can contain multiple files)

@hannes-ucsc and @mckinsel is the next step to have Marcus put together a sample bundle with json files and just confirm with Hannes it looks good?

Also @hannes-ucsc why not take this as an opportunity to start including a bundle.json file where you can cleanly define a bundle type?  You can't control that for green or purple box but it would be a good example you can point them to and say "this is super helpful to define what type this bundle is from a controlled vocabulary rather than constantly guessing..."

Are we on track for doing this before end of Q2?  I think researchers will really find this useful so I would be super excited to see it get done ASAP.

**Comment by hannes-ucsc** [comment]
@mckinsel 

I think one bundle per project with all three formats in the same bundle makes the most sense.

@briandoconnor

> why not take this as an opportunity to start including a bundle.json file where you can cleanly define a bundle type?

We can make up a schema for `bundle.json` but I would rather give MD a chance to chime in. cc:@malloryfreeberg what's the best way to propose a schema addition? Should we include what we think a `bundle.json` should look like in these matrix bundles, but omit a schema reference, or should we PR the schema addition against the MD repo first?

**Comment by malloryfreeberg** [comment]
@hannes-ucsc Please use the [New schema](https://github.com/HumanCellAtlas/metadata-schema/issues/new?labels=content&template=new_schema.md) GH ticket template to request a new schema. It asks for information about the fields that should go in the schema.

**Comment by hannes-ucsc** [comment]
Matrix Service is EOL.
